### ISSUE TITLE
Some clusters data is incomplete in cluster_gold

### ISSUE THREAD

**Issue by gueniai** [databrickslabs/overwatch#1000]
In our internal deployment, `num_workers` and `driver_node_type` are NULL for a few clusters (interactive, not new, and active) We should review

**Comment by sriram251-code** [comment]
After investigation found out 2 things.
1)All the audit log cluster ids are not present in Cluster snapshot.
2)The cluster which has been created or edited before primordial-date the details of these cluster are coming as null in cluster_spec_silver as the driving table for cluster_spec_silver is audit log not cluster_snapshot_bronze.
