### ISSUE TITLE
Feature Request: Costs for runs of that execute SQL/DBT/DLT tasks

### ISSUE THREAD

**Issue by followingell** [databrickslabs/overwatch#1003]
As per Overwatch's [documentation](https://databrickslabs.github.io/overwatch/dataengineer/definitions/#unsupported-scenarios-2):

> **Unsupported Scenarios:**
> - Costs for runs of that execute SQL/DBT/DLT tasks

Are there any timeframes on when this functionality may be available?

Thank you!

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,

Expecting to be release by end of next week.

Thanks!

**Comment by followingell** [comment]
> Hi @followingell ,
> 
> Expecting to be release by end of next week.
> 
> Thanks!

@mohanbaabu1996 Amazing stuff, thank you!
