### ISSUE TITLE
Gold Tables are not created (job, jobRun, clusterStateFact etc)

### ISSUE THREAD

**Issue by uhcdemo** [databrickslabs/overwatch#1006]
**Overwatch Version**
0.7.2

**Describe the bug**
Overwatch notebook not creating Gold Tables like job, jobRun, clusterStateFact etc in elt db. Some bronze, silver tables are created (notebook_silver, audit_log_bronze).
Screenshot of tables created attached.
![etldb](https://github.com/databrickslabs/overwatch/assets/125291629/0e720438-5b20-4ddf-aff0-b58bc106aa3d)

Logs attached
[overwatch_logs.csv](https://github.com/databrickslabs/overwatch/files/12230459/overwatch_logs.csv)

**Comment by mohanbaabu1996** [comment]
Hi @uhcdemo ,

Can you share with me the pipeline_report to validate.

`select * from overwatchetl.pipeline_report order by Pipeline_SnapTs desc`

**Comment by mohanbaabu1996** [comment]
Thanks for the report.
One issue i found out that, primordial date is keep changing that we should not do. I would suggest do the clean up and start as fresh with proper configuration. Below are the details to clean the existing data,

`drop database overwatchETL cascade`
`drop database overwatchDB cascade`
`%fs rm -r /mnt/workspace-300087250309354`

Once done, please modify the primordial date as 7 days before when you're ready to run overwatch and don't change the primordial date from the config.

Let me know if you've any doubts and i'm from IST timezone.

**Comment by mohanbaabu1996** [comment]
Hi @uhcdemo,

The report look good and no failed modules. To get those spark tables, you need to enable the cluster logging path in all the clusters and make sure overwatch cluster should have read/write access.

Docs - https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/securityconsiderations/#recommended-authorizations-approach

**Comment by mohanbaabu1996** [comment]
Hi @uhcdemo ,

Let me know if you've any issues.
Thanks!
