### ISSUE TITLE
Impute automated clusters termination as a last resort

### ISSUE THREAD

**Issue by gueniai** [databrickslabs/overwatch#1020]
There have been a few issues with the platform where we might miss the terminating event for an automated cluster. Can we investigate if it would be possible to impute the cluster termination from the job termination timestamp?

**Comment by hazearias** [comment]
It is okay to me for guenia@databricks.com to access to https://adb-5025981572092596.16.azuredatabricks.net/?o=5025981572092596#

**Comment by dougspadotto** [comment]
I'm trying to build a view that will have this ready, and would like to check if it is just a matter of coalescing into having a record on clusterstatefact with termination time (state=TERMINATING and a timestamp_state_start) or a record on jobRun time_detail. completionTime?
