### ISSUE TITLE
Overwatch Job not refreshing SparkJob table while other tables are populated

### ISSUE THREAD

**Issue by AbrahamBabu** [databrickslabs/overwatch#1024]
**Sensitive Content Alert**
Not a sensitive content

**Overwatch Version**
com.databricks.labs:overwatch_2.12:0.7.2.0.2

**Describe the bug**
1. sparkjob table not refreshed after 06/182023 but other tables are populated   

2. Hence, unable to fetch Notebook level insight in Overwatch for below workspace after 06/18/2023: 
workspace_name = 'databricks-ea2-edaa-etl'
https://adb-5260747060712541.1.azuredatabricks.net

**Screenshots**
![Databricks_Overwatch_SparkJobs_DataLoad_For_One_Workspace_not_happening](https://github.com/databrickslabs/overwatch/assets/39529204/ba2f85a1-bf7d-4812-9172-1c9166f92160)

**Issue Reports**
Filed a ticket to Databricks team TrackingID#2308090040005608 (Microsoft ticket), but Databricks team directed us to log a GitHub ticket since Overwatch being a lab product.

**Comment by mohanbaabu1996** [comment]
Hi @AbrahamBabu ,

Did you have a salesforce number after converting the Microsoft ticket, so that i can login and troubleshoot ?

**Comment by AbrahamBabu** [comment]
Hi @mohanbaabu1996 

Salesforce number is 00364103

**Comment by mohanbaabu1996** [comment]
Thanks @AbrahamBabu , we can communicate over the ticket. 

Thank you!
