### ISSUE TITLE
Missing tables on overwatch 

### ISSUE THREAD

**Issue by hazearias** [databrickslabs/overwatch#1035]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
(com.databricks.labs:overwatch_2.12:0.7.2.0.2)

**Describe the bug**
Missing tables related with jobs

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/97481906/20b20404-d9c6-48ff-917a-6c91235ac75a)

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by Arfa-1999** [comment]
Hi, 

Could you kindly share the pipeline report? To do so, run the command 'select * from ETL_DB.pipeline_report order by pipeline_snapTs desc;' to generate the report. Thank you!

Regards,
Syeda Arfa

**Comment by mateuszkulak** [comment]
Hello, I'm working on this project with @hazearias. Unfortunately, we cannot send you this report here due to our company's sensitive data policy. Is there any alternative for that?

**Comment by williamdphillips** [comment]
@hazearias I faced the same issue with DBR 12.2 LTS but resolved it by switching the 11.3 LTS. Can you confirm which DBR you are using? 

We also had to run the job a few times for the tables to all come up. After the first run, only a few of the tables in the consumer db tables were created/populated.

**Comment by hazearias** [comment]
@williamdphillips In Fact is the same issue, I tried to change the cluster but still have the same error for I few time.

I know that is working right now, Can be due the change of the cluster or work from Guenia?

With the purpose of documenting this issue and not replicate the error in the automation of the implementation @gueniai do you know what was the root cause and how to avoid it?

**Comment by mohanbaabu1996** [comment]
Hi @hazearias ,

I hope you're doing good and everything is working fine. 
Please let us know we can close the ticket, if you don't have any issues
Thank you!

**Comment by mohanbaabu1996** [comment]
Hi @hazearias,

Kindly let us know if you've got any issues.
Thank you!
