### ISSUE TITLE
Can't extract value from parsedBody#1996: need struct type but got void

### ISSUE THREAD

**Issue by hazearias** [databrickslabs/overwatch#1041]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
Tell us the version of Overwatch used when you received the issue

**Describe the bug**

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by mohanbaabu1996** [comment]
Hi @hazearias , this issue is similar to #1043 and we can discuss on another ticket.
Thanks!

**Comment by hazearias** [comment]
Perfect, Thank you Mohan
