### ISSUE TITLE
NotebookCommands Scope not Included by Default

### ISSUE THREAD

**Issue by williamdphillips** [databrickslabs/overwatch#1042]
**Overwatch Version**
0.7.2.0.4

**Describe the bug**
The documentation indicates that all scopes will be included by default, but the newer NotebookCommands scope is missing from the generated configuration during job execution.

Documentation link: https://databrickslabs.github.io/overwatch/dataengineer/modules/

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/67801903/bc8b1c38-5fcc-4dca-8638-c19c5cfe1e9c)

**Comment by gueniai** [comment]
Hey Drew! Make sure you use the latest version (0721)

**Comment by williamdphillips** [comment]
Hi Guenia! Ah thanks, was looking in the central maven repo and didn't see the version popup a couple days ago. I see it there now, thanks for clarifying!

![image](https://github.com/databrickslabs/overwatch/assets/67801903/97b2b8ee-5093-44a4-9a6a-239e3719e5a1)

**Comment by williamdphillips** [comment]
Marking as closed
