### ISSUE TITLE
Missing Table: "instancedetails"

### ISSUE THREAD

**Issue by williamdphillips** [databrickslabs/overwatch#1044]
**Overwatch Version**
0.7.2.1

**DBR**
11.3 LTS

**Describe the bug**
After running overwatch successfully (a few times) on the latest version, the table "instancedetails" is not getting created. Attempted to utilize the [available dashboards](https://databrickslabs.github.io/overwatch/dashboards/) but they seem to be dependent on this table for retrieving the workspaces upon which the overwatch job has run. The [dependent tables](https://databrickslabs.github.io/overwatch/dataengineer/pipeline_management/) in the overwatch_etl db are available.

Possibly related to #1035

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/67801903/ed1b7128-4922-45ba-93e1-0932c517009f)
![image](https://github.com/databrickslabs/overwatch/assets/67801903/13c4c5fb-0032-43c8-94d3-be135fa701b1)
![image](https://github.com/databrickslabs/overwatch/assets/67801903/e783fdb4-15a4-4484-bb48-e2ab2750f1f6)

**Comment by williamdphillips** [comment]
After reading through the [custom costs page](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/customcosts/), I see this is created upon the first run of the pipeline. While we were setting up overwatch and troubleshooting issues, we cleared all tables a couple times. Is there a way to force overwatch to recreate the missing table(s)?

**Comment by mohanbaabu1996** [comment]
Hi @williamdphillips ,

Is dashboard worked after creating the instancedetails table manually ?
According to the snippet, all the main tables are present inside the consumer database.

**Comment by williamdphillips** [comment]
Hi @mohanbaabu1996,

Yes, the dashboard is working after creating both the tables (etl db) and views (consumer db) manually. Since this is now working I'll go ahead and close the issue.
