### ISSUE TITLE
Issue with cluster cost information 

### ISSUE THREAD

**Issue by YitianLiu9** [databrickslabs/overwatch#1049]
Hi, we are having trouble understanding the cluster costs presented in overwatch. 

We are using version 7.2.0.3 (Upgraded weeks ago). 

The cost of clusters from overwatch doesn't match what we see from the Azure reservation billing information. The cost shown by overwatch can be higher from 10% to 295% of the other one. The data is compared on weekly level. Could you please help us with this issue. Thank you!

**Comment by Neha-vs123** [comment]
Hi @YitianLiu9 ,

Could you please file a Microsoft support ticket for this issue, so that we can login and troubleshoot.

Regards,
Neha

**Comment by Neha-vs123** [comment]
Hi @YitianLiu9,

I am closing this ticket for now. For cost issues, we need a cloud support ticket to be able to login and troubleshoot. 
Please raise the ticket and it will be assigned to our team for resolving.

Regards,
Neha
