### ISSUE TITLE
Error in running pipeline

### ISSUE THREAD

**Issue by YatharthKaushik** [databrickslabs/overwatch#1050]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.7.2.0

**Describe the bug**
Facing an error in running script.

I did a complete clean-up and used the latest 0.7.2.0 version of config csv. But I am facing the following error while running the pipeline.
Notebook Used : 071x_Runner

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/49161779/3c124bde-662b-4163-9958-50fa9a24b131)

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by sriram251-code** [comment]
resolution: please restart the cluster it will solve the issue.
