### ISSUE TITLE
Tables not being generated

### ISSUE THREAD

**Issue by YatharthKaushik** [databrickslabs/overwatch#1051]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.7.2.0

**Describe the bug**
Did a complete clean-up and upgraded from 0.7.1.0 version to 0.7.2.0 version. The pipeline ran successfully but only the tables/views present in the screenshot below are being generated.

Notebook Used : 071x_Runner

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/49161779/ceeef1ac-a780-43c5-89dc-5418b39246d0)

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by Neha-vs123** [comment]
Hi @YatharthKaushik ,

Can you please send the pipeline_report over to my mail ID: neha.vs@databricks.com

`select * from ETL_DB.pipeline_report order by Pipeline_SnapTs desc`

**Comment by YatharthKaushik** [comment]
Hi @Neha-vs123,

I cannot share the Pipeline Report with you due to company policy but as for the latest run either the status in Pipeline Report is 'SUCCESS' or similar to the below message:

`
EMPTY: 3013-Gold_SparkExecution Module: No new data found. This does not appear to be an error but simply a lack of data present for the module. Progressing module state. Module Dependencies: 2005 ALERT: No New Data Retrieved for Module 3013-Gold_SparkExecution! Skipping com.databricks.labs.overwatch.utils.NoNewDataException: ALERT: No New Data Retrieved for Module 3013-Gold_SparkExecution! Skipping 	at com.databricks.labs.overwatch.pipeline.Module.validateSourceDF(Module.scala:317) 	at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:376) 	at com.databricks.labs.overwatch.pipeline.Gold.processSparkEvents(Gold.scala:292) 	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1(Gold.scala:346) 	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1$adapted(Gold.scala:315) 	at scala.collection.immutable.List.foreach(List.scala:431) 	at com.databricks.labs.overwatch.pipeline.Gold.executeModules(Gold.scala:315) 	at com.databricks.labs.overwatch.pipeline.Gold.run(Gold.scala:408) 	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startGoldDeployment(MultiWorkspaceDeployment.scala:256) 	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:454) 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659) 	at scala.util.Success.$anonfun$map$1(Try.scala:255) 	at scala.util.Success.map(Try.scala:213) 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292) 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33) 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33) 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:750)`


Also, now the following tables are being generated:

**ETL Database :**

- account_login_gold
- account_login_silver
- account_mods_silver
- accountlogin
- audit_log_bronze
- audit_log_raw_events
- cluster_events_bronze
- cluster_events_errors_bronze
- cluster_gold 
- cluster_spec_silver
- cluster_state_detail_silver
- clusters_snapshot_bronze
- clusterstatefact_gold
- job_gold
- job_status_silver
- jobrun_gold
- jobrun_silver
- jobs_snapshot_bronze
- libs_snapshot_bronze
- notebook_gold
- notebook_silver
- pipeline_report
- pipreport
- policies_snapshot_bronze
- spark_events_bronze
- spark_events_processedfiles
- spark_executions_silver
- spark_executors_silver
- spark_jobs_silver
- spark_stages_silver
- spark_tasks_silver
- sql_query_history_gold
- sql_query_history_silver
- tokens_snapshot_bronze

**Consumer Database:**

- cluster
- clusterstatefact
- job
- jobrun
- notebook
- sqlqueryhistory

Also, _clusterstatesfact_ table and _instancedetails_ table are not being generated now.

My current cluster DBR version is 11.3. Any help is really appreciated.

**Comment by Neha-vs123** [comment]
Hi @YatharthKaushik,

I want to see the full pipeline report to analyse the issue. Since you cannot send it, can we have a meeting for a detailed understanding and tests? I am from the IST timezone. Available for meeting tomorrow at 9 am EST (if you are from EST).
Please let me know your availability and send a meeting invite to me `neha.vs@databricks.com`.

Regards,
Neha

**Comment by Neha-vs123** [comment]
Hi @YatharthKaushik ,

Please send an invite for 4 pm if it's okay for you.

Regards,
Neha

**Comment by YatharthKaushik** [comment]
Hi @Neha-vs123,

I have shared the invite with you.

Thanks and Regards,
Yatharth

**Comment by YatharthKaushik** [comment]
Hi @Neha-vs123,

Are you available for a call?

Thanks,
Yatharth

**Comment by Neha-vs123** [comment]
Hi @YatharthKaushik,

I hope your issue is fixed. I am closing this ticket for now. Feel free to reopen if the issue persists. 

Regards,
Neha
