### ISSUE TITLE
Unable To Find Policy ID For All-Purpose Clusters

### ISSUE THREAD

**Issue by coolbeans201** [databrickslabs/overwatch#1052]
I'm trying to query our workspace to see all clusters that don't have a policy ID attached to them. I was able to find this for job clusters (using the jobrun table), but am unable to find this for all-purpose clusters based on the predefined schema. Any idea on what I may be missing (or is it just missing for some reason?)

Thanks!

**Comment by mohanbaabu1996** [comment]
Hi @coolbeans201,

You can find the policyID for the all the clusters from the `clusters_snapshot_bronze` table in ETL database.

**Comment by coolbeans201** [comment]
Awesome, thanks Mohan!
