### ISSUE TITLE
Performance problem, Gold tier

### ISSUE THREAD

**Issue by nprospero** [databrickslabs/overwatch#1054]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
New clients

**Describe the bug**
What can I do to improve the performance of the Gold tier?  It currently takes 3 hours to run this layer

**Screenshots**

**Issue Reports**

**Comment by mohanbaabu1996** [comment]
Hi @nprospero ,

- Please follow the cluster [configurations](https://databrickslabs.github.io/overwatch/deployoverwatch/runningoverwatch/clusterconfig/#cluster-config-recommendations) for the daily job

- If you've not created the optimizer [job](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics/#externalize-optimize--z-order-as-of-060), please enable it for the optimization purpose
- How many parallelism have you configured ? It should be based on number of workspaces deployed
<img width="1304" alt="image" src="https://github.com/databrickslabs/overwatch/assets/87074323/25ada08c-01df-4133-a8e8-6b45f9741b29">

**Comment by mohanbaabu1996** [comment]
Hi @nprospero,

Please let me know  whether the above process gets worked ?

**Comment by moucode** [comment]
Hi @mohanbaabu1996, 
I currently have the same problem with the Overwatch job. 

Overwatch is running into a timeout error daily (the timeout was manually set to 3 hours). The processing of the Bronze and Silver data in the job runs without problems. As soon as the processing of the Gold data starts in the job, there comes a point where no more activity is recorded in the job. The job indicates that it is still running, but the cluster's Ganglia data indicates that the cluster is no longer performing any actions until the timeout is reached.

I have set the configurations as described in the documentation. Can you help here?
