### ISSUE TITLE
SparkEventLogs table not populating

### ISSUE THREAD

**Issue by Mpicca** [databrickslabs/overwatch#1055]
**Overwatch Version**
0.7.2.1
Using Azure.

**Describe the bug**
Bronze_SparkEventLogs not populating

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/24516226/d24d0920-5021-48fa-bbf5-556a95db5b03)

Full Validation Report:
![image](https://github.com/databrickslabs/overwatch/assets/24516226/3f9482f6-6441-4249-96d9-2f9a5a7b7d1f)

**Comment by mohanbaabu1996** [comment]
Hi @Mpicca,

- How many workspaces have you configured ?
- Does all the cluster have logging path enabled and have necessary read, write permission ?
- Can you able to display the one of the logs from the overwatch master workspace ?
`display(dbutils.fs.head("cluster_logging_path"))`

Please have an look into the [documentation](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/securityconsiderations/#recommended-authorizations-approach)

**Comment by Mpicca** [comment]
@mohanbaabu1996 
1 workspace configured
All cluster have have logging path enabled.
Unable to display 3 bullet point i receive the following: 
IllegalArgumentException: Cannot head a directory: dbfs:/mnt/<storagename>/monitoring/overwatch

**Comment by mohanbaabu1996** [comment]
Thanks!
Are you sure this path is the cluster logging path ?

dbfs:/mnt/storageaccountname/monitoring/overwatch

If yes, can you drill down the sub folders and check do you have .gz files

**Comment by mohanbaabu1996** [comment]
Hi @Mpicca 

Did you get a chance to check the above test case ?
Thank you!

**Comment by Mpicca** [comment]
@mohanbaabu1996 yes, the spark tables look to be populating now after multiple runs of the job. A new issue has arisen where the job looks to be completing but the gold tables are not processing / generating through the job, only bronze and silver:
Is there any way we can get on a quick call?

**Comment by Mpicca** [comment]
@mohanbaabu1996 i'm unable to share due to company policy. There are no failures in any modules. Will be happy to share on call.
I'm free anytime, please let me know soonest time you are available.

**Comment by mohanbaabu1996** [comment]
Google Meet joining info
Video call link: https://meet.google.com/ufy-psmm-kxk
Or dial: ‪(US) +1 252-843-1062‬ PIN: ‪584 907 704‬#
More phone numbers: https://tel.meet/ufy-psmm-kxk?pin=3437854930262

Can you please join here now ?

**Comment by mohanbaabu1996** [comment]
Let me know if this works for you

**Comment by joaoaugusto05** [comment]
What was the solution in this case? I'm facing the same problem :(

**Comment by mohanbaabu1996** [comment]
Hi @joaoaugusto05 What is the status message for 1006 moduleID in the pipeline_report?

`select * from ETL_DB.pipeline_report order by Pipeline_SnapTs desc
`

**Comment by joaoaugusto05** [comment]
Hi @mohanbaabu1996, it was actually quite strange.
The error message where, actually, that there was no new data.

I tried to run again but I got the same message.
At the end, I solved rolling it back. It was a little expensive but worked :))
