### ISSUE TITLE
Long-running overwatch job - 41h 45m 30s

### ISSUE THREAD

**Issue by hazearias** [databrickslabs/overwatch#1072]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
com.databricks.labs:overwatch_2.12:0.7.2.2 (Maven)

**Describe the bug**
Long-running overwatch job 
41h 45m 30s

This is the normal behavior on overwatch job in this workspace 
![image](https://github.com/databrickslabs/overwatch/assets/97481906/6ab4c448-7c89-408a-b498-753d587341b7)

The overwatch job here has stopped working for more than 2 weeks, we want to know if is normal if the duration.
and as we cancelled the job what is the behavior expected if we run it again

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/97481906/ec1f78aa-ff3f-443a-a116-d29ad114dba3)

**Issue Reports**
On this workspace: https://adb-8755884253711570.10.azuredatabricks.net/?o=8755884253711570#
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by Mahalakshmi1305** [comment]
HI @hazearias,

Can you remove dbsql:notebookcommands from the excluded scope column in the config sheet? 
Is there an optimizer job running?


Regards,
mahalakshmi

**Comment by Mahalakshmi1305** [comment]
Hi 

Can we have a call today at 8 AM PST? We can resolve this problem using screensharing.
My mail id - mahalakshmi.rajendran@databricks.com

Regards,
mahalakshmi

**Comment by hazearias** [comment]
Invitation sent

**Comment by Mahalakshmi1305** [comment]
Hi 

Sorry, I was on another call and didn't catch the invitation. Please reschedule it for tomorrow morning at the same timing.

Thanks

**Comment by hazearias** [comment]
Invitation updated!

**Comment by Mahalakshmi1305** [comment]
Hi
 
 Just to follow up, are you still having problem with the job run?
 
 Regards,
 Mahalakshmi

**Comment by hazearias** [comment]
Join on your computer, mobile app or room device 
[Click here to join the meeting](https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTVhNTRmNTQtNTJlMS00MGI0LTgxNjctYWFkY2IyODMwOGNk%40thread.v2/0?context=%7b%22Tid%22%3a%223596192b-fdf5-4e2c-a6fa-acb706c963d8%22%2c%22Oid%22%3a%22b60ef4d2-1dc1-4192-b6d3-2fe10aa731dd%22%7d)

**Comment by hazearias** [comment]
Hello!

After our check meeting yesterday we have the same result!
The job is still being stuck

**Comment by mohanbaabu1996** [comment]
Hi @hazearias ,

I hope you're doing well and everything is working fine.
Please let us know so we can close the ticket if you don't have any issues
Thank you!

**Comment by mohanbaabu1996** [comment]
Hi @hazearias,

Kindly let us know if you've got any issues.
Thank you!
