### ISSUE TITLE
`v0.7.2.2.1 (Patch)` upgrade script does not work with Unity Catalog

### ISSUE THREAD

**Issue by followingell** [databrickslabs/overwatch#1082]
**Overwatch Version**
`v0.7.2.2.1`

**Describe the bug**
In the [`v0.7.2.2.1` CHANGELOG notes](https://databrickslabs.github.io/overwatch/changelog/#07221-patch) you note that:

> If you ran versions 0721 or 0722, you need to run the upgrade script in order to repair the data.
> 
> Upgrade script: [HTML](https://databrickslabs.github.io/overwatch/assets/ChangeLog/07221_upgrade.html) | [DBC](https://databrickslabs.github.io/overwatch/assets/ChangeLog/07221_upgrade.dbc)

However, this script has not been sufficiently paramaterized to work with the 3-level namespaces (`catalog.schema.table`) found in [Unity Catalog](https://learn.microsoft.com/en-us/azure/databricks/data-governance/unity-catalog/#--the-unity-catalog-object-model) deployments.

I _believe_ the issue lies in the fact that the `rollbackPipelineForModule` function in `src/main/scala/com/databricks/labs/overwatch/utils/Tools.scala` only takes the [`config.databaseName`](https://github.com/databrickslabs/overwatch/blob/ceab5559796f91a8eb83e5e7750185bcb9bc7b9a/src/main/scala/com/databricks/labs/overwatch/utils/Tools.scala#L976) and not a combination of both `config.etlCatalogName` and `config.databaseName` when interacting with Unity Catalog-based deployments.

As such, the script fails with `AnalysisException: Table or view not found: databaseName.pipeline_report;` because it does not consider that a `etlCatalogName` value may also need to be considered should Unity Catalog be in use: `etlCatalogName.databaseName.pipeline_report`.

**Comment by mohanbaabu1996** [comment]
Thanks @followingell , Yes we've noticed and working on the script

**Comment by followingell** [comment]
@mohanbaabu1996 No problem. Do you have an ETA for when a working upgrade script will be made available? _I ask because this is blocking our upgrade leaving us on a version that required "critical fixes."_

**Comment by mohanbaabu1996** [comment]
Let me know from which version you're trying to upgrade to 07221. And this upgrade will fix only `warehouse_spec_silver` and `warehouse_gold` modules.

If you are looking for another table, you can upgrade to 07221. Once the script is ready, we can run it anytime.

**Comment by followingell** [comment]
@mohanbaabu1996 I would be upgrading from `v0.7.2.2`.

Given the CHANGELOG comment:

> If you ran versions 0721 or 0722, you need to run the upgrade script in order to repair the data.

...I would prefer to 'clean' the problematic data and then upgrade to start fresh from `v0.7.2.2.1`.

**Comment by mohanbaabu1996** [comment]
I got it; the team has already started work on that script, and it will be available before the end of this week.
I'll let you know.

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,
How many workspaces has been deployed so far?

**Comment by followingell** [comment]
> Hi @followingell , How many workspaces has been deployed so far?

Hey @mohanbaabu1996,

Our Overwatch deployment covers multiple (2) workspaces.

**Comment by mohanbaabu1996** [comment]
Thanks. Could you please delete the records for the `warehouse_spec_silver` and `warehouse_gold` tables and run the job with the latest JAR (0.7.2.2.1)? It will re-create the records from the primordial date based on the latest version.

-  `delete from CATALOG.ETL_DB.pipeline_report where moduleId in (2021, 3018)`
-  `delete from CATALOG.ETL_DB.warehouse_spec_silver`
-  `delete from CATALOG.ETL_DB.warehouse_gold`

Replace the catalog and overwatch etl database names in the above code.

Let me know if you've any questions.

**Comment by followingell** [comment]
> Thanks. Could you please delete the records for the `warehouse_spec_silver` and `warehouse_gold` tables and run the job with the latest JAR (0.7.2.2.1)? It will re-create the records from the primordial date based on the latest version.
> 
> * `delete from CATALOG.ETL_DB.pipeline_report where moduleId in (2021, 3018)`
> * `delete from CATALOG.ETL_DB.warehouse_spec_silver`
> * `delete from CATALOG.ETL_DB.warehouse_gold`
> 
> Replace the catalog and overwatch etl database names in the above code.
> 
> Let me know if you've any questions.

Hey @mohanbaabu1996, would doing the above negate the need to run the upgrade script that your team developed? What's the  difference between the two (upgrade script vs manual)?

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,

The upgrade script contains the rollback function, and that function helps to delete the old data from the tables and update the pipeline report. We're also doing the same process manually.
Here's the [docs](https://databrickslabs.github.io/overwatch/dataengineer/pipeline_management/#reloading-data) that explains rollback functionality.

**Comment by followingell** [comment]
> Hi @followingell ,
> 
> The upgrade script contains the rollback function, and that function helps to delete the old data from the tables and update the pipeline report. We're also doing the same process manually.
> Here's the [docs](https://databrickslabs.github.io/overwatch/dataengineer/pipeline_management/#reloading-data) that explains rollback functionality.

I thought you mentioned that a new, working upgrade script would be made available:

> I got it; the team has already started work on that script, and it will be available before the end of this week. I'll let you know.

Is that now not the case? _I would much rather utilize a tested script rather than doing manual adjustments as a non-service principal user._

**Comment by mohanbaabu1996** [comment]
[07221_upgrade_new.html.zip](https://github.com/databrickslabs/overwatch/files/13350878/07221_upgrade_new.html.zip)

Hi @followingell ,

Can you please run the latest upgrade script and run the job using the 07221 version?

**Comment by mohanbaabu1996** [comment]
@followingell Let us know if the script works and if you are able to run the Overwatch job.
