### ISSUE TITLE
Silver_WarehouseSpec failing

### ISSUE THREAD

**Issue by varungoran1992** [databrickslabs/overwatch#1084]
Hello,
I am deploying overwatch for Unity Catalog to a single dev workspace. I am able to see all the tables being created with the exception of the warehouse tables. The module Silver_WarehouseSpec is failing with the following error:
Silver_WarehouseSpec: Validating Input Schemas Silver_WarehouseSpec -- First run detected, will impute warehouse state from bronze to derive current initial state for all existing warehouses. FAILED: 2021-Silver_WarehouseSpec Module: Failed [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `channel` cannot be resolved. Did you mean one of the following? [`name`, `health`, `size`, `state`, `tags`].; 'Project [organization_id#XXXXX, warehouse_id#1020506, warehouses AS serviceName#1021808, snapImpute AS actionName#1021809, name#1020509 AS warehouse_name#1021810, state#1020514 AS warehouse_state#1021811, size#1020512, cluster_size#1020501, min_num_clusters#1020508L, max_num_clusters#1020507L, auto_stop_mins#1020500L, auto_resume#1020499, creator_id#1020502L, spot_instance_policy#1020513, enable_photon#1020504, get_json_object(to_json('channel, Some(Etc/UTC)), $.name) AS channel#1021812, tags#1020468, enable_serverless_compute#1020505, warehouse_type#1020515, num_clusters#1020511L, num_active_sessions#1020510L, jdbc_url#1020450, odbc_params#1020451, (unix_timestamp(Pipeline_SnapTS#1020496, yyyy-MM-dd HH:mm:ss, Some(Etc/UTC), false) * cast(1000 as bigint)) AS timestamp#1021813L, ... 2 more fields] +- Project [organization_id#XXXXX, warehouse_id#1020506, health#1020449, jdbc_url#1020450, odbc_params#1020451, Pipeline_SnapTS#1020496, Overwatch_RunID#1020497, workspace_name#1020498, auto_resume#1020499, auto_stop_mins#1020500L, cluster_size#1020501, creator_id#1020502L, creator_name#1020503, enable_photon#1020504, enable_serverless_compute#1020505, max_num_clusters#1020507L, min_num_clusters#1020508L, name#1020509, num_active_sessions#1020510L, num_clusters#1020511L, size#1020512, spot_instance_policy#1020513, state#1020514, tags#1020468, warehouse_type#1020515]

I am able to see data being loaded for warehouses_snapshot_bronze and audit_log_bronze so the dependencies are there. Due to this failing, I believe this is causing warehouse_gold to fail. I am using version 0.7.2.2. Please let me know if you need anything else.
Thanks for your time and help

**Comment by Sandhya-ravindranath** [comment]
Hi varungoran1992,

Run the 07221 upgrade script and run job with 07221

**Comment by Sandhya-ravindranath** [comment]
If you ran versions 0721 or 0722, you need to run the upgrade script in order to repair the data.

By adding the latest library, we can address the following bugs:

1. Fixed lookup to ensure there are no NULL notebook_ids in NotebookCommands.
2. Resolved the issue of duplicated audit log columns when certain new services in EventHub are activated.
3. Improved the performance of the WarehouseSpec table and resolved schema discrepancies in Warehouse Gold to prevent failures.
4. Enhanced the coverage of job_run_cluster_util to compute it for jobs submitted using SparkSubmit.
5. Fixed a dashboard bug related to the metric "DBU Spend by the top 3 expensive Interactive clusters" in the Clusters 
dashboard.

**Comment by varungoran1992** [comment]
I updated to the latest version 0.7221, ran the upgrade script, and reran the job but I am still facing the same error.

**Comment by varungoran1992** [comment]
I updated to the latest version 0.7221, ran the upgrade script, and reran the job but I am still facing the same error. I am using the following link for the jumpstart notebook-https://databrickslabs.github.io/overwatch/deployoverwatch/runningoverwatch/notebook/
Here are the steps I followed

Deleted the Unity catalog dev workspace using single_workspace_cleanup notebook
Used 0.7204 and ran 071x_Runner notebook
Used 0.7221 and ran the upgrade script
Also ran the following commands- delete from CATALOG.ETL_DB.pipeline_report where moduleId in (2021, 3018). Note that the warehouse_spec_silver and warehouse_gold tables were not created
I reran the Runner notebook with 0.7221 and still got the same error
Silver_WarehouseSpec: Validating Input Schemas
Silver_WarehouseSpec -- First run detected, will impute warehouse state from bronze to derive current initial state for all existing warehouses.
FAILED: 2021-Silver_WarehouseSpec Module: Failed
[UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name channel cannot be resolved. Did you mean one of the following? [name, health, size, state, tags].;
'Project [organization_id#xxxxx, warehouse_id#257165, warehouses AS serviceName#258768, snapImpute AS actionName#258769, name#257168 AS warehouse_name#258770, state#257173 AS warehouse_state#258771, size#257171, cluster_size#257160, min_num_clusters#257167L, max_num_clusters#257166L, auto_stop_mins#257159L, auto_resume#257158, creator_id#257161L, spot_instance_policy#257172, enable_photon#257163, get_json_object(to_json('channel, Some(Etc/UTC)), $.name) AS channel#258772, tags#257127, enable_serverless_compute#257164, warehouse_type#257174, num_clusters#257170L, num_active_sessions#257169L, jdbc_url#257109, odbc_params#257110, (unix_timestamp(Pipeline_SnapTS#257155, yyyy-MM-dd HH:mm:ss, Some(Etc/UTC), false) * cast(1000 as bigint)) AS timestamp#258773L, ... 2 more fields]

*** WARNING: skipped 57759 bytes of output ***

Please let me know if you need anything else.
Thanks for your time and help

**Comment by varungoran1992** [comment]
I was able to edit the sql warehouse and verified that the channel attribute was being placed in the audit logs. When querying the bronze audit log table in overwatch_etl, I am able to see three entries there where channel is being included for requestParams. However after deleting and re deploying, I am still facing the same error.
Thanks for your time and help

**Comment by mohanbaabu1996** [comment]
Hi @varungoran1992 ,

Did you cleaned completely and re-deployed with 07221 version ?

**Comment by varungoran1992** [comment]
After cleaning, I redeployed with 07204 version and then ran 07221 version. A lot of the components fail if I run it with the 07221 version after cleaning so I ran it with 07204.

**Comment by mohanbaabu1996** [comment]
Thanks, did you clean up everything and ran with 07221 ?

**Comment by varungoran1992** [comment]
Yes, getting this error for 07221

**Comment by varungoran1992** [comment]
I am using the single_workspace_cleanup config and the primordial date is 2023-10-02 which is the first date of audit logs.

**Comment by varungoran1992** [comment]
Yes, I am.

**Comment by mohanbaabu1996** [comment]
Is that module failing?

**Comment by varungoran1992** [comment]
Yes, not seeing warehouse silver table in the catalog

**Comment by mohanbaabu1996** [comment]
Hi, @varungoran1992 ,

What's the message for 2021 in the pipeline report?

`select * from CATALOG.ETL_DB.pipeline_report where moduleId = 2021 order by Pipeline_SnapTs desc`

**Comment by varungoran1992** [comment]
Hello,
I was able to resolve this issue. Seeing the tables now.
Thanks for your time and help

**Comment by mohanbaabu1996** [comment]
Thanks for the update!
