### ISSUE TITLE
Overwatch non-empty directory error

### ISSUE THREAD

**Issue by YitianLiu9** [databrickslabs/overwatch#1093]
Hi, 

we are running on overwatch 0.7.2.2.1 for a single workspace. 

I encouter this error below: 

AzureException: hadoop_azure_shaded.com.microsoft.azure.storage.StorageException: This operation is not permitted on a non-empty directory. Caused by: StorageException: This operation is not permitted on a non-empty directory.

I discovered that it is the tempworkingdir folder that is not emptied, causing the problem. If I delete the content in this folder the job can run without error. Could you maybe help me solve this problem? Thank you!

**Comment by mohanbaabu1996** [comment]
Hi @YitianLiu9 ,

- Is this a fresh deployment?
- Are you using a Unity Catalog workspace?
- Have you added the relevant spark [configuration](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/securityconsiderations/#event-hub-access-azure-only)?

**Comment by YitianLiu9** [comment]
Hi @mohanbaabu1996 , 

Thanks for getting back. Turns out the issue was with the mount point that we mounted with wasbs using a SAS key earlier. The issue was solved with a mount point on abfss using an SPN. You can close this ticket now. Thanks!! 

Yitian

**Comment by mohanbaabu1996** [comment]
Thanks for the response
