### ISSUE TITLE
fs.azure.account.key error with unity catalog

### ISSUE THREAD

**Issue by YitianLiu9** [databrickslabs/overwatch#1096]
Hi, 

We are trying to deploy overwatch in unity catalog. The external location is set up and given proper permission required in the documentation. But we are getting this error: 

KeyProviderException: Failure to initialize configuration for storage account az21q1datalakewe.dfs.core.windows.net: Invalid configuration value detected for fs.azure.account.key
Caused by: InvalidConfigurationValueException: Invalid configuration value detected for fs.azure.account.key

<img width="703" alt="Screenshot 2023-11-27 at 18 50 52" src="https://github.com/databrickslabs/overwatch/assets/120654490/01edd9bc-722e-4b4d-9989-6801293c83b8">

The storage_prefix value in the config file is as follows: 
abfss://<container name>@<sa name>.dfs.core.windows.net/overwatch/overwatch_dir

The external location is pointing to abfss://<container name>@<sa name>.dfs.core.windows.net

The job is running on 0.7.2.0.4 and DBR 13.3 LTS 

Could you please help? Thank you!

**Comment by Mahalakshmi1305** [comment]
Hi,

1. Can you please share your input CSV file for review?
2. Did you follow the steps for the UC Configuration(https://databrickslabs.github.io/overwatch/deployoverwatch/ucedeployment/uceconfiguration/), which are mentioned in the Overwatch documentation?
3. Are you in the 7.2.0.4 version?
4. Can you run the job using the DBR 11.3LTS?

Regards,
Mahalakshmi

**Comment by mohanbaabu1996** [comment]
Hi @YitianLiu9 ,

Let us know if you're facing an issue.
Thanks!
