### ISSUE TITLE
Multiple streaming queries are concurrently using metadata

### ISSUE THREAD

**Issue by pcocko** [databrickslabs/overwatch#1106]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.7.2.0

**Describe the bug**
Sometimes there is a connectivity problem when is trying to read from eventhub. The validation step shows that there is a problem when is "Consuming data from EventHub".
The exception is:
Unable to retrieve data from ehName:overwatch scope:kv-overwatch eh_scope_key:xxx-wspace-dbricks-prd-we-008-ehub-key
Multiple streaming queries are concurrently using metadata.
org.apache.spark.SparkConcurrentModificationException: Multiple streaming queries are concurrently using metadata.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.multiStreamingQueriesUsingPathConcurrentlyError(QueryExecutionErrors.scala:2322)

This eventhub is not being read from other streaming process

**Screenshots**
<img width="701" alt="image" src="https://github.com/databrickslabs/overwatch/assets/2462035/67de36aa-ea5c-4311-b566-ded36868afdd">

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by Mahalakshmi1305** [comment]
Hi,
Can you run the below code to test whether the event hub messages are flowing or not?

```import org.apache.spark.eventhubs.{ConnectionStringBuilder, EventHubsConf, EventPosition}

val EHSECRETSCOPE = "secret_scope"
val EHCONNSTRINGKEYNAME = "eh_connection_string"
val EHNAME = "event_hub_name" 

val connectionString = ConnectionStringBuilder(dbutils.secrets.get(EHSECRETSCOPE, EHCONNSTRINGKEYNAME))
  .setEventHubName(EHNAME)
  .build

val ehConf = EventHubsConf(connectionString)
  .setMaxEventsPerTrigger(100)
  .setStartingPosition(EventPosition.fromStartOfStream)

val rawEHDF = spark.readStream
  .format("eventhubs")
  .options(ehConf.toMap)
  .load()
  .withColumn("deserializedBody", 'body.cast("string"))

display(rawEHDF)```

**Comment by pcocko** [comment]
Hi @Mahalakshmi1305 ,

This issue was solved using a parallelism equals to 1. But it requires to process each workspace in sequence order.

On the other hand, I found that the overwatch process takes so much time in this part:
"Audit Logs Bronze: Land Stream Beginning for WorkspaceID: xxxxxxxxx"

I am started thinking that i have something wrong in our eventhubs. It is possible?

**Comment by Mahalakshmi1305** [comment]
Hi @pcocko,

How many workspaces do you have? Set the parallelism equal to the count of workspaces.

Can you run the below code to test whether the event hub messages are flowing or not?

"""
val EHSECRETSCOPE = "secret_scope"
val EHCONNSTRINGKEYNAME = "eh_connection_string"
val EHNAME = "event_hub_name" 

val connectionString = ConnectionStringBuilder(dbutils.secrets.get(EHSECRETSCOPE, EHCONNSTRINGKEYNAME))
  .setEventHubName(EHNAME)
  .build

val ehConf = EventHubsConf(connectionString)
  .setMaxEventsPerTrigger(100)
  .setStartingPosition(EventPosition.fromStartOfStream)

val rawEHDF = spark.readStream
  .format("eventhubs")
  .options(ehConf.toMap)
  .load()
  .withColumn("deserializedBody", 'body.cast("string"))

display(rawEHDF)
"""

**Comment by mohanbaabu1996** [comment]
Hi @pcocko 

I hope you're doing good!
Let us know if you're facing an issue.
Thanks!
