### ISSUE TITLE
Not able to pull audit logs and other spark metrics

### ISSUE THREAD

**Issue by abhishek021** [databrickslabs/overwatch#1107]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.7.2.2.1

**Describe the bug**
primordial_date is 2023-11-25 and max_days=30 but still, I can see in the table fromTS and untilTS the same.

**Screenshots**
<img width="986" alt="image" src="https://github.com/databrickslabs/overwatch/assets/14111116/046a4887-7b08-4f59-9e83-3c5ac5313b43">

**Issue Reports**
[GenericTicket_Diagnostics - Databricks.pdf](https://github.com/databrickslabs/overwatch/files/13528002/GenericTicket_Diagnostics.-.Databricks.pdf)

**Comment by mohanbaabu1996** [comment]
Hi @abhishek021 ,

Is this the same status message for all the latest runs for the 3001 module?

**Comment by mohanbaabu1996** [comment]
Hi @abhishek021 ,

I hope you're doing good!
Let us know if you're facing an issue.
Thanks!
