### ISSUE TITLE
Overwatch job is taking less time than the average in that workspace

### ISSUE THREAD

**Issue by hazearias** [databrickslabs/overwatch#1108]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
com.databricks.labs:overwatch_2.12:0.7.2.2

**Describe the bug**

Overwatch job is taking less time than the average. The possible errors here:

1. **Received response code 429: Too many request per second**
API call Endpoint: https://eastus2-c2.azuredatabricks.net/api/2.0/sql/history/queries
queryString: {"max_results":"50","include_metrics":"true","filter_by.query_start_time_range.start_time_ms":"1675497600000","filter_by.query_start_time_range.end_time_ms":"1675501200000"}
Server Busy Count:1
Total Sleep Time:2 seconds
Successful api response count:0
Current action: Sleeping for 2 second

2. **GOLD VIEW: CREATE VIEW FAILED: Cannot create view: overwatch_etl.cluster_gold** --> [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `gcp_attributes` cannot be resolved. Did you mean one of the following? [`hive_metastore`.`delta`.`/mnt/optimum/overwatchglobal/global_share/cluster_gold`.`date`, `hive_metastore`.`delta`.`/mnt/optimum/overwatchglobal/global_share/cluster_gold`.`action`, `hive_metastore`.`delta`.`/mnt/optimum/overwatchglobal/global_share/cluster_gold`.`autoscale`, `hive_metastore`.`delta`.`/mnt/optimum/overwatchglobal/global_share/cluster_gold`.`timestamp`, `hive_metastore`.`delta`.`/mnt/optimum/overwatchglobal/global_share/cluster_gold`.`cluster_id`]; line 5 pos 51

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/97481906/1147d048-0252-462c-bd56-cab46ae4623c)

![image](https://github.com/databrickslabs/overwatch/assets/97481906/aeacb223-ca00-4767-baa0-04dfef430922)

**Issue Reports**

**Comment by hazearias** [comment]
Hello 

My Time zone is UTC-6

**Comment by hazearias** [comment]
Hello @Mahalakshmi1305, 

after our call to check this issue, you told me that I needed to create a support ticket in order to have access to the workspace and take a look.
this is the No Support Ticket: 2401020030003075.

as it have been 3 weeks since I opened this issue, I have a different result in the output of the overwatch, the issue is the same, still taking less time than the average in that workspace.

These are the error I got:

**1. Job aborted due to stage failure**
Bronze_SparkEventLogs: Validating Input Schemas
FAILED: 1006-Bronze_SparkEventLogs Module: Failed

Job aborted due to stage failure: Total size of serialized results of 54007 tasks (4.0 GiB) is bigger than spark.driver.maxResultSize 4.0 GiB.
org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 54007 tasks (4.0 GiB) is bigger than spark.driver.maxResultSize 4.0 GiB.

2. **GOLD VIEW: CREATE VIEW FAILED**: Cannot create view: overwatch_etl.job_gold

**Comment by Mahalakshmi1305** [comment]
Hi Hazel,
I think this is the workspace ID: 2401020030003075. Can you send me the
case number, which will contain an 8-digit number? Please see the attached
screenshot.

[image: image.png]

Regards,
Mahalakshmi

**Comment by hazearias** [comment]
we just have this 
![image](https://github.com/databrickslabs/overwatch/assets/97481906/8cf362c5-ca34-4ada-84c4-4ccd94da248c)

**Comment by hazearias** [comment]
Following up this issue

**Comment by hazearias** [comment]
Following up again

**Comment by Mahalakshmi1305** [comment]
Hi Hazel,

Still, that ticket has not been converted into an SF ticket. Once it appears on the SF ticket list, our team will start working on it.

Regards,
Mahalakshmi

**Comment by hazearias** [comment]
@gueniai Is something we can do different ?

We create a Microsoft ticket in order to @Mahalakshmi1305 be able to access to the workspace and fix the issue. I remember one time that I granted the permission to access the workspace in the comment here.

Can we do that time this?


I am reaching you because the issue has been open since december.

**Comment by gueniai** [comment]
Hi @hazearias! We certainly can! Can you please send us an email with the workspace ID and your approval to our databricks email? We can take it from there.

**Comment by hazearias** [comment]
Done!
Thanks Guenia

**Comment by hazearias** [comment]
@Mahalakshmi1305 What is the status of the job ?

**Comment by Mahalakshmi1305** [comment]
Hi Hazel,

We are fixing the issue (Gold View), and once it is done, I will provide you updates through the ticket.

**Comment by Mahalakshmi1305** [comment]
Hi @hazearias,

Yesterday, I submitted a solution via the sales force ticket. However, I am unable to log in to the workspaces, as it indicates that the ticket has already been closed.Please check

<img width="1397" alt="p g" src="https://github.com/databrickslabs/overwatch/assets/146411068/4103175d-7cb4-4d6c-adcb-bc3fca9abb7c">

**Comment by Mahalakshmi1305** [comment]
Hi @hazearias 

I sent you an email regarding the updates and access issues. Let's continue our communication through email for further discussions.

Thanks,
Mahalakshmi
