### ISSUE TITLE
Bronze layer with error

### ISSUE THREAD

**Issue by nprospero** [databrickslabs/overwatch#1109]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.7.2.x

**Describe the bug**
When running the command:

try {
    MultiWorkspaceDeployment(configCsvPath, tempLocation).deploy(parallelism,"Bronze")
} catch {
    case e: Exception => println("###### Exception Occurred : " + e)
}

**This ERROR occurs:**

ParallelismLevel: 1
Configuration source: overwatch_etl.overwatch_prod_config delta table
IMPLEMENTATION FAILED WITH EXCEPTION
**###### Exception occurred: java.lang.IllegalStateException: could not find any delta file for version 159**
import com.databricks.labs.overwatch.MultiWorkspaceDeployment
configCsvPath: String = overwatch_etl.overwatch_prod_config
tempLocation: String = /archived/monitor/temp/overwatch/deployment_temp_dir
parallelism: Int = 1

**Screenshots**
![ERROR_OVERWATCH_BRONZE](https://github.com/databrickslabs/overwatch/assets/31243541/24c1ecaa-b618-47fb-b9be-82f57eea481a)

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by mohanbaabu1996** [comment]
Hi, @nprospero ,

Can you create the delta table using the csv configuration in a different database than "overwatch_etl"?

**Comment by nprospero** [comment]
Good morning, thanks for getting back to us.
I can even create another database besides overwatch_etl.
My configuration file is not a csv, I created a delta table according to the instructions in the manual "Converting Your Config From CSV To Delta".

But I would like to understand if there is any way for the error message to be more specific, indicating which delta table is missing sequence 159 in the delta tables.

Because I did a select * from
delta.`......../global_share/clusterstatefact_gold` in all tables and none reported a sequence error in delta tables

What can you recommend me to do to solve this problem, as I would not like to have to reinstall everything again, because I already have a database with historical information.

**Comment by mohanbaabu1996** [comment]
HI @nprospero ,

The way of converting a CSV to a delta table is correct, but create the config table in a different database. Don't create under "overwatch_etl" database

**Comment by nprospero** [comment]
@mohanbaabu1996 
Good afternoon, how are you?
I created the configuration table in a different database. I didn't create it in the "overwatch_etl" database.
But I keep getting the error message:
FAILED DEPLOYMENT WITH EXCEPTION
###### Exception Occurred : java.lang.IllegalStateException: Could not find any delta files for version 159

One question: is there any way to identify which table does not have delta files for version 159? When a failure occurs in the execution of the Bronze layer, is the error description recorded in a table or file? Is there a way to identify where or which table is having a problem?
I have already checked using the select ... from delta.nome_tabela command and none failed due to lack of delta log.

**Comment by mohanbaabu1996** [comment]
Hi, @nprospero ,

I'm good, thank you!

- Did you remove the config table from the ETL database?
- You can check the delta version to all the etl tables using sql and check which table is missing 159
     `describe history ETL_DB.TABLE_NAME`

I'm not sure whether I'm correct but please check once

**Comment by mohanbaabu1996** [comment]
Hi @nprospero,

can you please check whether delta log files for `overwatch_prod_config` table are present under `global_share` folder?

**Comment by nprospero** [comment]
@mohanbaabu1996 
Good afternoon, how are you?
yes, the delta log files from the overwatch_prod_config table are present in the global_share container

**Comment by mohanbaabu1996** [comment]
Hi @nprospero ,

Can you remove the path "overwatch_prod_config" completely from the global_share folder?

**Comment by mohanbaabu1996** [comment]
Hi @nprospero ,

I hope you are able to make the changes and that everything is working fine.
Please reply to this ticket if you're facing an issue.
Thank you!
