### ISSUE TITLE
Missing tables

### ISSUE THREAD

**Issue by letssamu** [databrickslabs/overwatch#1139]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
Tell us the version of Overwatch used when you received the issue

0.7.2.2.1

**Describe the bug**

Not all the tables deployed

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

![image](https://github.com/databrickslabs/overwatch/assets/6296797/f7546d29-d7ea-4455-ac22-25cd2c640dd5)

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by Mahalakshmi1305** [comment]
Hi @letssamu ,

Can you share with me the pipeline_report to validate?

"""select * from overwatchetl.pipeline_report order by Pipeline_SnapTs desc"""

**Comment by letssamu** [comment]
Hi @Mahalakshmi1305 ,

I'm attaching the results:

[New_query_2024_01_24.xlsx](https://github.com/databrickslabs/overwatch/files/14043613/New_query_2024_01_24.xlsx)

**Comment by Mahalakshmi1305** [comment]
Hi @letssamu,

Could you please grant us access to your workspace so that we can look into the issue more deeply? Kindly send us an email with the workspace ID and your approval to our DataBricks email address. We can take it from there.

Regards,
Mahalakshmi

**Comment by letssamu** [comment]
Hi @Mahalakshmi1305,

Please can you tell me the email? 

Thank you.

**Comment by Mahalakshmi1305** [comment]
Hi @letssamu,
 
Please find my email id: mahalakshmi.rajendran@databricks.com

Regards,
Mahalakshmi
