### ISSUE TITLE
[INVESTIGATE] Investigate reasons for Job Run vs JRCP discrepancies

### ISSUE THREAD

**Issue by gueniai** [databrickslabs/overwatch#1150]
There are cases where there are missing JobRuns in JRCP. We know one of the reasons is jobs running on warehouses, investigate and document any other reasons, along with a validation function that customers can run that ensures only runs under the identified reasons are missing. This second part can probably be part of the validation framework

**Comment by souravbaner-da** [comment]
@gueniai Upon running the validation framework on top of the 0811 deployments, the issue seems to be fixed now.
