### ISSUE TITLE
Externalize Optimize - Concurrent delete exception

### ISSUE THREAD

**Issue by pcocko** [databrickslabs/overwatch#1152]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.7.2.0

**Describe the bug**
In order to optimize the tables and following this link https://databrickslabs.github.io/overwatch/gettingstarted/advancedtopics/#externalize-optimize--z-order-as-of-060 i am having the following error:
```
java.util.concurrent.ExecutionException: io.delta.exceptions.ConcurrentDeleteDeleteException: This transaction attempted to delete one or more files that were deleted (for example organization_id=1564699590970904/part-00000-8016eebd-22e4-46e9-9513-d9be972f1ab1.c000.snappy.parquet) by a concurrent update. Please try the operation again.
Conflicting commit: {"timestamp":1706803520302,"operation":"OPTIMIZE","operationParameters":{"predicate":[],"zOrderBy":[],"batchId":0,"auto":false},"readVersion":21926,"isolationLevel":"SnapshotIsolation","isBlindAppend":false,"operationMetrics":{"numRemovedFiles":"6","numRemovedBytes":"679796","p25FileSize":"154058","numDeletionVectorsRemoved":"0","minFileSize":"154058","numAddedFiles":"3","maxFileSize":"227445","p75FileSize":"227445","p50FileSize":"175563","numAddedBytes":"557066"},"tags":{"preservedRowTracking":"false"},"engineInfo":"Databricks-Runtime/13.3.x-photon-scala2.12","txnId":"02c94462-2480-4c9a-9629-8d5a11853b43"}
Refer to https://docs.microsoft.com/azure/databricks/delta/concurrency-control for more details.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.databricks.sql.transaction.tahoe.commands.optimize.OptimizeExecutor.$anonfun$executeOptimizeBatch$5(OptimizeExecutor.scala:171)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
```
At the end, the process fails.

Can someone guide me in solving this issue?

Thanks in advance

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by dipayan-dutta** [comment]
Hi @pcocko,

Can you please confirm that the Overwatch optimizer job is configured properly as per the documentation?
If yes, Can you please swap the jar to the latest version - 0.8.0.0 & try it once.

**Comment by pcocko** [comment]
Hi @dipayan-dutta,
For running that version i will need to have Overwatch with 0.8.0.0 as well ?

**Comment by gueniai** [comment]
Hi @pcocko, is the issue happening every time when you run the optimizer job? Also, is there any chance the optimizer was running at the same time as the Overwatch job? (The exception you linked above suggest there was an attempt at a concurrent deletion)

**Comment by pcocko** [comment]
Hi @gueniai, we have run the job several times for checking if it was something specific but the same error happens each time. Regarding running Overwatch and Optimizer at the same time, i can assure that it's not happening

**Comment by dipayan-dutta** [comment]
Hi @pcocko ,

I am working on this issue, I will provide you the update through the SF ticket / Email. I will soft-close the ticket from here.
