### ISSUE TITLE
Missing job runs

### ISSUE THREAD

**Issue by varungorantla** [databrickslabs/overwatch#1153]
Hello,
When trying to compute the cost of overwatch, I am noticing some missing runs. We are currently running Overwatch as a job. I see some dates showing in the jobruncostpotentialfact_gold however certain dates are missing. I tried querying the dependent modules with a cluster id that is in jobruncostpotentialfact_gold and a cluster id that is not. I am seeing data being returned in the tables for jobrun_gold, clusterstatefact_gold, sparkjob_gold, and sparktask_gold. There’s no data for cluster_gold for both cluster ids. I also verified that cluster logs are available and have data for both cluster ids. Please let me know if you need more information.
Thanks for your time and help

**Comment by varungorantla** [comment]
For the latest overwatch job run, I am noticing that it’s now not showing in the tables for jobrun_gold, sparkjob_gold, and sparktask_gold. The job did successfully complete and I am seeing data being returned in clusterstatefact_gold. However I don’t see a terminating event. I just see ADD_NODES_FAILED, Running, and Creating. The cluster size is m6i.32xlarge.

**Comment by dipayan-dutta** [comment]
Hi Varun,

Please let me know what is your current Overwatch version.

**Comment by varungorantla** [comment]
Hi,
The overwatch version is com.databricks.labs:overwatch_2.12:0.8.0.0 (Maven)

**Comment by varungorantla** [comment]
I have also tried running the job using 0.7.2.2.1 and still facing the same issue.

**Comment by varungorantla** [comment]
I also ran the GenericTicket_Diagnostics notebook and I see the Gold_jobRunCostPotentialFact as a success with the following:
{"numTargetRowsCopied": "21475", "numTargetRowsDeleted": "0", "numTargetFilesAdded": "47", "numTargetBytesAdded": "7637287", "numTargetBytesRemoved": "6662409", "numTargetDeletionVectorsAdded": "0", "numTargetRowsMatchedUpdated": "22", "executionTimeMs": "513897", "numTargetRowsInserted": "850", "numTargetRowsMatchedDeleted": "0", "scanTimeMs": "2334", "numTargetRowsUpdated": "22", "numOutputRows": "22347", "numTargetDeletionVectorsRemoved": "0", "numTargetRowsNotMatchedBySourceUpdated": "0", "numTargetChangeFilesAdded": "0", "numSourceRows": "872", "numTargetFilesRemoved": "15", "numTargetRowsNotMatchedBySourceDeleted": "0", "rewriteTimeMs": "13578"}

**Comment by varungorantla** [comment]
Another thing I noticed is that it only logs the job cost details for Overwatch when it fails. I dont see any successful overwatch runs logged in Gold_jobRunCostPotentialFact.

**Comment by shravanshibu90** [comment]
Hi @varungorantla ,

We may need to open a ticket, that we can login to workspace and have a closer look to issue. Kindly confirm.If yes, I can send mail request for the same where you share further details.

**Comment by varungorantla** [comment]
Hello,There is already a support ticket where I provided the workspace url. Thanks,VarunSent from my iPhoneOn Feb 13, 2024, at 12:42 AM, shravanshibu90 ***@***.***> wrote:﻿
Hi @varungorantla ,
We may need to open a ticket, that we can login to workspace and have a closer look to issue. Kindly confirm.If yes, I can send mail request for the same where you share further details.

**Comment by dipayan-dutta** [comment]
Hi @varungorantla,

I got the ticket and I am looking into this issue. And I replied to you in the SF ticket.

**Comment by dipayan-dutta** [comment]
Hi @varungorantla ,

I am working on this issue, I will provide you the update through the SF ticket. I will soft-close the ticket from here.
