### ISSUE TITLE
Validate that all billable cluster states have `total_cost` > 0 and not null

### ISSUE THREAD

**Issue by gueniai** [databrickslabs/overwatch#1156]

**Comment by souravbaner-da** [comment]
@gueniai 
cluster_ids for which databricks_billable is true and total_cost is Null or 0 are commonly Serverless SQL Warehouses. Currently OW dont support computing for those type of clusters. So this is expected result we are getting from validation framework.
Have changed the validation Framework for this rule like below:
```
        (validationStatus, quarantineStatus) == validateRuleAndUpdateStatus(
          RuleSet(clsf_df.where("cluster_name is not null").where("databricks_billable is true")).add(validateRules(4)),
          tableName, key, validationStatus, quarantineStatus, "validate_greater_than_zero", Overwatch_RunID)
```
With the above code change validation rule will run for all cluster_ids which are currenly in scope of OW.

**Comment by souravbaner-da** [comment]
@gueniai  Upon running the validation framework on top of the 0811 deployments, the issue seems to be fixed now.
