### ISSUE TITLE
Module Failure Errors

### ISSUE THREAD

**Issue by mikekimlovelytics** [databrickslabs/overwatch#1177]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.8.0

**Describe the bug**
Getting the following module failure errors for different workspaces and overwatch runs:

```FAILED --> ERROR: FAILED: 1006-Bronze_SparkEventLogs Module: Failed Job aborted due to stage failure: Total size of serialized results of 17260 tasks (4.0 GiB) is bigger than spark.driver.maxResultSize 4.0 GiB.```

```FAILED --> ERROR: FAILED: 3015-Gold_jobRunCostPotentialFact Module: Failed Unsupported component type interface scala.collection.Seq in arrays. ```

```FAILED --> ERROR: FAILED: 1004-Bronze_AuditLogs Module: Failed TABLE LOCK TIMEOUT - The table logging._overwatch_internal.audit_log_bronze remained locked for more than the configured max timeout of 1200000 millis. ```

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

GenericTicket_Diagnostics is attached.
[GenericTicket_Diagnostics.html.zip](https://github.com/databrickslabs/overwatch/files/14906333/GenericTicket_Diagnostics.html.zip)

**Comment by Mahalakshmi1305** [comment]
Hi @mikekimlovelytics 

Please add the following commands to the cluster spark configuration: For more, please see the documentation. 
Here is the link:
https://databrickslabs.github.io/overwatch/faq/#q11-an-api-call-is-resulting-in-job-aborted-what-can-i-do

overwatch.tableLockTimeout 7200000
spark.rpc.message.maxSize 1024
spark.driver.maxResultSize 32G

Regards,
Mahalakshmi

**Comment by Mahalakshmi1305** [comment]
1. Is this a fresh deployment? if yes, try to reduce the max days load
2. Which cloud are you in, and what is the size of your cluster?

**Comment by mikekimlovelytics** [comment]
1. Yes fresh deployment. What max days to you recommend? Can I just rerun from the beginning primordial date? Will it reattempt the failed tables? Will the above config settings take care of all the errors?
2. Cloud is AWS. The cluster configurations are as follows:

Bronze:
-Runtime 14.3 LTS
-Photon enabled
-Worker - i3.4xlarge (2 workers)
-Driver - same as worker
-Local storage autoscaling enabled

Silver/Gold:
-Runtime 14.3 LTS
-Photon enabled
-Worker - i3.4xlarge (2 - 8 workers)
-Driver - same as worker
-Autoscaling enabled
-Local storage autoscaling enabled

**Comment by mikekimlovelytics** [comment]
> 1. Is this a fresh deployment? if yes, try to reduce the max days load
> 2. Which cloud are you in, and what is the size of your cluster?

@Mahalakshmi1305 Could you chime in on my response above? Also, I am still running into this error:

```FAILED --> ERROR: FAILED: 1004-Bronze_AuditLogs Module: Failed TABLE LOCK TIMEOUT - The table logging._overwatch_internal.audit_log_bronze remained locked for more than the configured max timeout of 1200000 millis. ```

Please help troubleshoot.

**Comment by Mahalakshmi1305** [comment]
Hi @mikekimlovelytics 
Could you kindly share the pipeline report?To do so, run the following command to generate the report:

select * from ETL_DB_NAME.pipeline_report where status like "%FAILED%" order by PipelineSnapTs desc

Thanks,
Mahalakshmi

**Comment by Mahalakshmi1305** [comment]
@mikekimlovelytics 

Can you try to use Runtime Version 13.3LTS? 

If you are still having any issues, please share your availability on Friday. We need to get on a call to analyze the issue.I am from the IST timezone, available from 8 am to 11 am EST. Here is my mail id, mahalakshmi.rajendran@databricks.com

Thanks,
Mahalakshmi

**Comment by mikekimlovelytics** [comment]
@Mahalakshmi1305 13.3 LTS fixed it! Thank you so much, everything is populating now. Thank you so much; I will close this ticket.
