### ISSUE TITLE
job workflow takes too much time

### ISSUE THREAD

**Issue by letssamu** [databrickslabs/overwatch#1182]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.8.0.0

**Describe the bug**
job workflow takes too much time, more than 10 hours in most cases

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/6296797/3659a63e-3704-48f3-9c46-2eff36a2df30)

**Issue Reports**
Please share an email to send the report

**Comment by mohanbaabu1996** [comment]
Hi @letssamu 

Please make sure to follow the cluster [recommendations ](https://databrickslabs.github.io/overwatch/deployoverwatch/runningoverwatch/clusterconfig/#cluster-config-recommendations)

- How many workspaces are passing as an input?
- How many parallelisms are provided in the job's [parameters](https://databrickslabs.github.io/overwatch/deployoverwatch/runningoverwatch/jar/#parameters)?

**Comment by letssamu** [comment]
Hi @mohanbaabu1996 

The primordial_date is 2024-04-04 and max_days is 30, I didn't change those values since first deployment.

**Comment by mohanbaabu1996** [comment]
It seems like the initial days of load is taking time to run. Can you check what the job runtime is for April 16 and 17?
Let me know your time zone as well. I'm from the IST timezone.

**Comment by letssamu** [comment]
Hi @mohanbaabu1996 

![image](https://github.com/databrickslabs/overwatch/assets/6296797/cf0d8c61-23a5-4595-aec1-f6b93bd5d751)

I have stopped runs from yesterday because of high DBU consumption.

My timezone is Peru (GMT-5)

**Comment by mohanbaabu1996** [comment]
Hi @letssamu ,

Will you be available for a short call tomorrow (Friday) at 6:30 PM IST?
If yes, please send me an invite to mohan.baabu@databricks.com
Thanks!

**Comment by letssamu** [comment]
HI @mohanbaabu1996 

Can be 5:00 PM IST?

**Comment by mohanbaabu1996** [comment]
Yes, 30 minutes will be fine. Can you please share the invite.

**Comment by letssamu** [comment]
Hi @mohanbaabu1996 

I run the job again after your recommendations but throw this error:
![image](https://github.com/databrickslabs/overwatch/assets/6296797/59cafceb-36c3-431a-a6ab-5d3aa3754e2c)

**Comment by mohanbaabu1996** [comment]
Hi @letssamu 

I remember we were trying to add the JAR using the wheel option. Can you trying again adding using JAR option.

<img width="666" alt="image" src="https://github.com/databrickslabs/overwatch/assets/87074323/9e5e9ac1-b46e-4990-80b8-768cc76bc10a">

**Comment by letssamu** [comment]
Hi @mohanbaabu1996 

There is an error if I select Python wheel:
![image](https://github.com/databrickslabs/overwatch/assets/6296797/b3f82902-1ce6-4c5d-a36f-2b51454425ed)

![image](https://github.com/databrickslabs/overwatch/assets/6296797/dd10710a-2704-410c-8939-132eb18870e6)

**Comment by mohanbaabu1996** [comment]
Hi @letssamu 

You need to select the JAR type

**Comment by letssamu** [comment]
@mohanbaabu1996 

JAR file is selected and failed again with the same error.

**Comment by letssamu** [comment]
Hi @mohanbaabu1996 , 

Please can be tomorrow Wednesday at same time?

**Comment by mohanbaabu1996** [comment]
yes, Wednesday 5 PM IST will work

**Comment by mohanbaabu1996** [comment]
HI @letssamu 

I've joined the call, and please admit me to the call.
Thanks!
