### ISSUE TITLE
Column 'organization_id' does not exist

### ISSUE THREAD

**Issue by jphala2dxc** [databrickslabs/overwatch#1187]
**Overwatch Version** 
0.7.2.2.1

**Describe the bug** 
Our Databricks workspace is based in Azure.
The MultiWorkspaceRunning encountered the error below in which it failed to create view in gold due to column 'organization_id' does not exist.

For additional context, the was job failing in the past due to invalid PAT token in which we renewed from the Keyvault Secret and after doing so we did an adhoc run which completed much longer but now we encountered the below error.

`GOLD VIEW: CREATE VIEW FAILED: Cannot create view: overwatch_etl.sparkJob_gold --> Column 'organization_id' does not exist. Did you mean one of the following? []; line 5 pos 93;
'CreateViewCommand `hive_metastore`.`overwatch_consumer`.`sparkJob`, select 
organization_id, workspace_name, spark_context_id, job_id, job_group_id, execution_id, stage_ids, cluster_id, notebook_id, notebook_path,
db_job_id, db_id_in_job, db_job_type, unixTimeMS, timestamp, date, job_runtime, job_result, event_log_start,
event_log_end, user_email
 from delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkjob_gold` where organization_id = delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkjob_gold`.organization_id and date = delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkjob_gold`.date, false, true, PersistedView, false
+- 'Project ['organization_id, 'workspace_name, 'spark_context_id, 'job_id, 'job_group_id, 'execution_id, 'stage_ids, 'cluster_id, 'notebook_id, 'notebook_path, 'db_job_id, 'db_id_in_job, 'db_job_type, 'unixTimeMS, 'timestamp, 'date, 'job_runtime, 'job_result, 'event_log_start, 'event_log_end, 'user_email]
   +- 'Filter (('organization_id = 'delta./mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkjob_gold.organization_id) AND ('date = 'delta./mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkjob_gold.date))
      +- SubqueryAlias hive_metastore.delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkjob_gold`
         +- Relation [] parquet

GOLD VIEW: CREATE VIEW FAILED: Cannot create view: overwatch_etl.sparkStage_gold --> Column 'organization_id' does not exist. Did you mean one of the following? []; line 4 pos 95;
'CreateViewCommand `hive_metastore`.`overwatch_consumer`.`sparkStage`, select 
organization_id, workspace_name, spark_context_id, stage_id, stage_attempt_id, cluster_id, unixTimeMS, timestamp, date, stage_runtime,
stage_info, event_log_start, event_log_end
 from delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstage_gold` where organization_id = delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstage_gold`.organization_id and date = delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstage_gold`.date, false, true, PersistedView, false
+- 'Project ['organization_id, 'workspace_name, 'spark_context_id, 'stage_id, 'stage_attempt_id, 'cluster_id, 'unixTimeMS, 'timestamp, 'date, 'stage_runtime, 'stage_info, 'event_log_start, 'event_log_end]
   +- 'Filter (('organization_id = 'delta./mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstage_gold.organization_id) AND ('date = 'delta./mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstage_gold.date))
      +- SubqueryAlias hive_metastore.delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstage_gold`
         +- Relation [] parquet

GOLD VIEW: CREATE VIEW FAILED: Cannot create view: overwatch_etl.sparkTask_gold --> Column 'organization_id' does not exist. Did you mean one of the following? []; line 5 pos 94;
'CreateViewCommand `hive_metastore`.`overwatch_consumer`.`sparkTask`, select 
organization_id, workspace_name, spark_context_id, task_id, task_attempt_id, stage_id, stage_attempt_id, cluster_id, executor_id, host,
unixTimeMS, timestamp, date, task_runtime, task_metrics, task_info, task_type, task_end_reason,
event_log_start, event_log_end
 from delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparktask_gold` where organization_id = delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparktask_gold`.organization_id and date = delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparktask_gold`.date, false, true, PersistedView, false
+- 'Project ['organization_id, 'workspace_name, 'spark_context_id, 'task_id, 'task_attempt_id, 'stage_id, 'stage_attempt_id, 'cluster_id, 'executor_id, 'host, 'unixTimeMS, 'timestamp, 'date, 'task_runtime, 'task_metrics, 'task_info, 'task_type, 'task_end_reason, 'event_log_start, 'event_log_end]
   +- 'Filter (('organization_id = 'delta./mnt/optimum/overwatchglobal/6824821813734644/global_share/sparktask_gold.organization_id) AND ('date = 'delta./mnt/optimum/overwatchglobal/6824821813734644/global_share/sparktask_gold.date))
      +- SubqueryAlias hive_metastore.delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparktask_gold`
         +- Relation [] parquet

GOLD VIEW: CREATE VIEW FAILED: Cannot create view: overwatch_etl.sparkExecution_gold --> Column 'organization_id' does not exist. Did you mean one of the following? []; line 4 pos 99;
'CreateViewCommand `hive_metastore`.`overwatch_consumer`.`sparkExecution`, select 
organization_id, workspace_name, spark_context_id, execution_id, cluster_id, description, details, unixTimeMS, timestamp, date,
sql_execution_runtime, event_log_start, event_log_end
 from delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkexecution_gold` where organization_id = delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkexecution_gold`.organization_id, false, true, PersistedView, false
+- 'Project ['organization_id, 'workspace_name, 'spark_context_id, 'execution_id, 'cluster_id, 'description, 'details, 'unixTimeMS, 'timestamp, 'date, 'sql_execution_runtime, 'event_log_start, 'event_log_end]
   +- 'Filter ('organization_id = 'delta./mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkexecution_gold.organization_id)
      +- SubqueryAlias hive_metastore.delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkexecution_gold`
         +- Relation [] parquet

GOLD VIEW: CREATE VIEW FAILED: Cannot create view: overwatch_etl.sparkStream_gold --> Column 'organization_id' does not exist. Did you mean one of the following? []; line 4 pos 96;
'CreateViewCommand `hive_metastore`.`overwatch_consumer`.`sparkStream`, select 
organization_id, workspace_name, spark_context_id, cluster_id, stream_id, stream_run_id, stream_batch_id,
stream_timestamp, date, streamSegment, stream_name, streaming_metrics, execution_ids
 from delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstream_gold` where organization_id = delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstream_gold`.organization_id and date = delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstream_gold`.date, false, true, PersistedView, false
+- 'Project ['organization_id, 'workspace_name, 'spark_context_id, 'cluster_id, 'stream_id, 'stream_run_id, 'stream_batch_id, 'stream_timestamp, 'date, 'streamSegment, 'stream_name, 'streaming_metrics, 'execution_ids]
   +- 'Filter (('organization_id = 'delta./mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstream_gold.organization_id) AND ('date = 'delta./mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstream_gold.date))
      +- SubqueryAlias hive_metastore.delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkstream_gold`
         +- Relation [] parquet

GOLD VIEW: CREATE VIEW FAILED: Cannot create view: overwatch_etl.sparkExecutor_gold --> Column 'organization_id' does not exist. Did you mean one of the following? []; line 4 pos 98;
'CreateViewCommand `hive_metastore`.`overwatch_consumer`.`sparkExecutor`, select 
organization_id, workspace_name, spark_context_id, executor_id, cluster_id, executor_info, removed_reason, executor_alivetime,
unixTimeMS, timestamp, date, event_log_start, event_log_end
 from delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkexecutor_gold` where organization_id = delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkexecutor_gold`.organization_id, false, true, PersistedView, false
+- 'Project ['organization_id, 'workspace_name, 'spark_context_id, 'executor_id, 'cluster_id, 'executor_info, 'removed_reason, 'executor_alivetime, 'unixTimeMS, 'timestamp, 'date, 'event_log_start, 'event_log_end]
   +- 'Filter ('organization_id = 'delta./mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkexecutor_gold.organization_id)
      +- SubqueryAlias hive_metastore.delta.`/mnt/optimum/overwatchglobal/6824821813734644/global_share/sparkexecutor_gold`
         +- Relation [] parquet`

**Comment by mohanbaabu1996** [comment]
Hi @jphala2dxc 

Can you upgrade to the next latest version, 0800, by running the [script](https://databrickslabs.github.io/overwatch/assets/ChangeLog/0800_Upgrade.html) (Only step 1) and run the job with 0800 version.

**Comment by jphala2dxc** [comment]
Hi @mohanbaabu1996 , 

I followed the instruction you shared, however the error is still the same and same view were still failing as initially shared.

Action performed:

1. Ran the [script](https://databrickslabs.github.io/overwatch/assets/ChangeLog/0800_Upgrade.html) (Only step 1)
2. Upgraded the overwatch library from 0.7.2.2.1 to 0.8.0.1 in the job cluster
3. Manually triggered the job

**Comment by mohanbaabu1996** [comment]
Thanks @jphala2dxc 
Is this a fresh deployment started with 07221 or was it working a few months ago?

**Comment by jphala2dxc** [comment]
It was working a few months ago, according to our users that reported the issue, the last data they could see was last December.

Right now the observation is that users can already see the latest data in views with the exception of the impacted views mentioned in the error logs.

**Comment by mohanbaabu1996** [comment]
Oh, let me know if you're from IST timezone.
If yes, shall we meet at 4 PM today?
Please send an invite to mohan.baabu@databricks.com

**Comment by jphala2dxc** [comment]
Hi @mohanbaabu1996,

Sure we can meet, let me send the invite

**Comment by jphala2dxc** [comment]
Hi @mohanbaabu1996 ,

I just received confirmation that you can proceed to access the affected workspace for further investigation:

**Workspace Name:** adbnasususer01
**Workspace ID:** 6824821813734644

**Comment by mohanbaabu1996** [comment]
Thanks @jphala2dxc If possible, can you create me a small all-purpose cluster named "overwatch_support" that should have the same access as the overwatch job cluster?

**Comment by mohanbaabu1996** [comment]
Hi @jphala2dxc 

The tables are started generating and the issue has been solved. Please check and let me know if you have any issue to my email ID. Thanks!

<img width="621" alt="image" src="https://github.com/databrickslabs/overwatch/assets/87074323/778baca6-1a87-448f-91b4-855180115d29">

**Comment by jphala2dxc** [comment]
Hi @mohanbaabu1996 ,

Thanks for the superb support 😊!
You were very quick and very knowledgeable of your product and was able to to resolve our case in a short amount time!
More power to your and to your team!

Also I was able to confirm that the affected views are now working and have data.
I’ll let you know we see any issues afterwards. Thanks once again!
