### ISSUE TITLE
Have question on Configuration csv file

### ISSUE THREAD

**Issue by learnprofile** [databrickslabs/overwatch#1190]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.8.0.x+

**Describe the bug**
Based on the documentation : https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/configuration/ it says to use this .csv file and make changes with respect to Azure Databricks URL.

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

The documentation is not clear if i need to upload this .csv file to storage account/ mount point and then which command to run?
however based on existing notebook i made changes and while running below step:

![image](https://github.com/databrickslabs/overwatch/assets/32097278/ff6a91df-f216-477a-b2a0-1f4d43b9848f)

It throws this error:

DeltaAnalysisException: [DELTA_MISSING_TRANSACTION_LOG] Incompatible format detected.

You are trying to write to `dbfs:/test/1206-003704-wvqwgqbx/global_share/instancedetails` using Delta, but there is no
transaction log present. Check the upstream job to make sure that it is writing
using format("delta") and that you are trying to write to the table base path.

To learn more about Delta, see https://docs.microsoft.com/azure/databricks/delta/index

So wanted to know what is going wrong?

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by Neha-vs123** [comment]
Hi @learnprofile,

Please let me know your timezone. We need to get on a call to understand your existing configurations and what is missing.
I am from the IST timezone. We can connect at an available time.

Regards,
Neha

**Comment by learnprofile** [comment]
if you are available we can connect now?

**Comment by learnprofile** [comment]
Hi Neha,
I am available now for a call, could you send teams invite we can discuss further.

Thanks,
Prashanth Kumar


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by Neha-vs123** [comment]
Hi @learnprofile,

I have a conflict, can we connect at 3pm IST?

**Comment by learnprofile** [comment]
Yes 3pm IST will work for me, please send me the meeting invite accordingly.

**Comment by Neha-vs123** [comment]
@learnprofile please share your mail id to send the meeting invite. If not, can you send the invite directly?
My mail id is neha.vs@databricks.com

**Comment by learnprofile** [comment]
Sure thank you, let me send

**Comment by Neha-vs123** [comment]
Hi @learnprofile, Thanks for joining the call. Hope your doubts are cleared. Please let me know if you have any other issues.

Regards,
Neha
