### ISSUE TITLE
[INVESTIGATION] Can we do all transactions at table level

### ISSUE THREAD

**Issue by gueniai** [databrickslabs/overwatch#1205]
Review the impact on read, writes, and optimization. 
As a step 2, can we check if we can remove table locks?

**Comment by sriram251-code** [comment]
Tried different approches but still getting the same exception even we perform all the transaction at table level.

**Comment by sriram251-code** [comment]
Let me know if we want to investigate more or can close this issue @gueniai

**Comment by sriram251-code** [comment]
Created a programm which can run 4 threads in parallel to update into an external table with INSERT INTO command got exception.
Tried changing delta properties of the read version and write version but got the same exceptions.
Tried changing different delta properties but got the same exception.
