### ISSUE TITLE
[Epic] Derive cost for sql-endpoint 

### ISSUE THREAD

**Issue by aman-db** [databrickslabs/overwatch#1212]
Derive cost for sql-endpoints.

Issues (and PRs) in this epic include:

- [x] ~#1217~ (won't do) 
- [x] #1218 (#1254)
- [x] #1252 (#1265)
- [x] #1261

**Comment by neilbest-db** [comment]
@aman-db , please check correctness and completeness of the list of Issues and PRs that I added to the description of this epic.

**Comment by aman-db** [comment]
> @aman-db , please check correctness and completeness of the list of Issues and PRs that I added to the description of this epic.

@neilbest-db  This looks good
