### ISSUE TITLE
Ambiguous reference to the field `vendor_UNIQUESUFFIX_-820075192`.

### ISSUE THREAD

**Issue by msadlocha31** [databrickslabs/overwatch#1233]
We recently discovered the problem with our Production Overwatch and tried to fix that ourselves but so far our methods are not pushing it forwards. The problem is within the Bronze_Clusters_Snapshot that fails due to Ambiguous reference to the field `vendor_UNIQUESUFFIX_-820075192`.

We tried on our INT environment to upgrade the version of OVW maven repository that end up with the same error. The other solution we tried was to rollback all the related modules and run it again which also did not help.
[LOGS_PRD.md](https://github.com/user-attachments/files/15612389/LOGS_PRD.md)

**Comment by msadlocha31** [comment]
Hi @mohanbaabu1996,

On Int there is version 0.8.1.1 and the error its actually now bit different:
"Bronze_Clusters_Snapshot: Validating Input Schemas
Wrote 726862 bytes.
FAILED: 1002-Bronze_Clusters_Snapshot Module: Failed

Failed to merge fields 'spec' and 'spec'
com.databricks.sql.transaction.tahoe.DeltaAnalysisException: Failed to merge fields 'spec' and 'spec'
at com.databricks.sql.transaction.tahoe.schema.SchemaMergingUtils$.$anonfun$mergeSchemas$1(SchemaMergingUtils.scala:207)"

On PROD we stay with old 0.7.2.2.1

**Comment by mohanbaabu1996** [comment]
Thanks, Have you started running Overwatch from 0811 or updated to 0811 from the previous version.
If yes, what's the previous version?

**Comment by msadlocha31** [comment]
We had previous 8.10 and hence tried to run the script that you recommended but it failed (see attached)
![image](https://github.com/databrickslabs/overwatch/assets/171593157/8f9cf5cb-1ec1-45f4-a0b9-87f080ceec6a)
 
Many Thanks

**Comment by mohanbaabu1996** [comment]
Which version of Overwatch were you using at the time of running the upgrade script?

**Comment by msadlocha31** [comment]
8.10 at the time of that run

**Comment by mohanbaabu1996** [comment]
can you run the 0811 upgrade [script](https://databrickslabs.github.io/overwatch/changelog/#0811-patch) using the cluster with the library 0811 itself?

**Comment by msadlocha31** [comment]
I tried but the error for 8.11 lib is the same

**Comment by mohanbaabu1996** [comment]
Hi @msadlocha31 

Please let me know if you're available for a 15-minute call. I'm from the IST timezone.

**Comment by msadlocha31** [comment]
Hi @mohanbaabu1996 , sure, let me know when you have time.

I'm in the CET zone. I'm free tomorrow after 9:30 (so 13:00 your time, I think) for 1.5 hours, or Wednesday after 10:00 (13:30 your time).

If none of these times fit you, please propose something else.

**Comment by mohanbaabu1996** [comment]
Hi, @msadlocha31 ,

We closed this ticket and were able to fix the 0811 upgrade script.
Thanks!
