### ISSUE TITLE
Unable to run AWS example notebook

### ISSUE THREAD

**Issue by j0nnyr0berts** [databrickslabs/overwatch#124]
I am trying to set up Overwatch as per the [AWS example notebook](https://databrickslabs.github.io/overwatch/assets/GettingStarted/aws_runner_docs_example.html), however, I am getting the error, object overwatch is not a member of package com.databricks.labs when running import com.databricks.labs.overwatch.pipeline.{Initializer, Bronze, Silver, Gold}. I have tried adding the [overwatch package](https://search.maven.org/artifact/com.databricks.labs/overwatch_2.12/0.4.11/jar) to the cluster but still no joy! Any pointers would be greatly appreciated

**Comment by GeekSheikh** [comment]
@j0nnyr0berts If you attach the library after the cluster is running you'll need to clear -> clear state at the top of the notebook to bring in the references to the Overwatch package. It's best practice to always clear state after attaching libraries. Please also make sure you're attaching version 0.4.11 from Maven `com.databricks.labs:overwatch_2.12:0.4.11`. Please also make sure that your cluster is >= DBR 7.3 (7.6+ is preferred). Please let us know if this doesn't work

**Comment by GeekSheikh** [comment]
Hi there, I'm assuming this will fix your issue, if it does not please re-open the ticket and let me know.

**Comment by j0nnyr0berts** [comment]
Thanks for getting back to me so quickly - worked perfectly! I knew this would expose my ignorance 😆
