### ISSUE TITLE
Grant to views issue

### ISSUE THREAD

**Issue by letssamu** [databrickslabs/overwatch#1242]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.8.0.0 with UC

**Describe the bug**
After granting select to a view to a user, it shows an error that the user doesn't have permissions to read files in external location, use schema and select the table

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/6296797/a5429f3f-b4b3-496a-9c9d-27346b79d17b)

![image](https://github.com/databrickslabs/overwatch/assets/6296797/49f85b14-42d5-453c-aa31-141a560046a8)

![image](https://github.com/databrickslabs/overwatch/assets/6296797/7b577423-4244-4f7d-ae80-0e20ea5061b5)

Aflter those grants, the query worked but I have the doubt if I have to grant access to the table if I want users to use the views.

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by ashlytee** [comment]
Hi @letssamu,

Please go thorough this document and provide with necessary permissions. Thank you

https://databrickslabs.github.io/overwatch/deployoverwatch/ucedeployment/uceprereqs/#sql-command-to-grant-permissions-to-various-uc-objects

**Comment by letssamu** [comment]
Hi @ashlytee ,

I want to grant Select to the Views to a user, the workflow runs ok.
The documentation Is yo grant permissions to the principal to run overwatch, I want the user to query the Views not accessing the tables.

**Comment by letssamu** [comment]
Hi @ashlytee @mohanbaabu1996 ,

Do you have any update about this question please?
It seems I have to grant select to ETL tables to users to consume the information.

PD: I'm using UC.

**Comment by ashlytee** [comment]
Hi @letssamu,

Yes, you have to grand all permissions ( grant select to ETL tables to users) to consume the information in UC.

**Comment by ashlytee** [comment]
Hi @letssamu ,

I'm hoping this is resolved. Kindly respond to this if you need any additional help.
