### ISSUE TITLE
)

### ISSUE THREAD

**Issue by letssamu** [databrickslabs/overwatch#1251]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.8.0.0 with UC

**Describe the bug**
Workflow optimization. I am looking for alternatives to save cost and time of execution.

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
[GenericTicket_Diagnostics (2).zip](https://github.com/user-attachments/files/15958093/GenericTicket_Diagnostics.2.zip)

**Comment by Mahalakshmi1305** [comment]
Hi @letssamu ,

1. How did you configure the Overwatch daily job?
2. Did you follow the recommended cluster configuration for the job?
3. Is the Optimizer job enabled in the workspace? If so, what is the current DBR version?

Thanks,
Mahalakshmi

**Comment by letssamu** [comment]
1. As a JAR.
2. Yes and after the recommendations I changed also the configurations
3. Yes, 13.3

**Comment by Mahalakshmi1305** [comment]
Hi @letssamu,

Please let me know your time zone. We need to get on a call to review the status of the job. I am in the IST time zone.

Thanks,
Mahalakshmi

**Comment by letssamu** [comment]
Hi @Mahalakshmi1305 ,

I am in Peru time (GMT-5).

Samuel

**Comment by Mahalakshmi1305** [comment]
Hi @letssamu,

I will be available tomorrow from 8:30 PM to 9:00 PM IST (10:00 AM to 10:30 AM GMT). If this works for you, please schedule a call and send me an invitation to this email: mahalakshmi.rajendran@databricks.com.

**Comment by Mahalakshmi1305** [comment]
Hi @letssamu,

Thanks for joining the call. Please let me know if you have any other issues.

Thanks,
Mahalakshmi
