### ISSUE TITLE
Invalid configuration value detected for fs.azure.account.key

### ISSUE THREAD

**Issue by tbaert-prest** [databrickslabs/overwatch#1257]
Hello,

I am trying to install overwatch on a Databricks deployed in Azure. But after many attempts, it is not ok.
I am using Unity Catalog. I follow these documentations :

- [https://databrickslabs.github.io/overwatch/deployoverwatch/ucedeployment/cloudstorageaccessrequirements/azure/](https://databrickslabs.github.io/overwatch/deployoverwatch/ucedeployment/cloudstorageaccessrequirements/azure/)
- [https://databrickslabs.github.io/overwatch/deployoverwatch/ucedeployment/uceconfiguration/](https://databrickslabs.github.io/overwatch/deployoverwatch/ucedeployment/uceconfiguration/)

The storage prefix is abfss://overwatch@***.dfs.core.windows.net/ow.

I have this error message :
![Capture d’écran 2024-07-03 085108](https://github.com/databrickslabs/overwatch/assets/158584906/ee6f54fb-fa2f-4f98-8904-344834118b8a)

I tested to add this configuration on the cluster :
[https://hadoop.apache.org/docs/stable/hadoop-azure/abfs.html#Azure_Managed_Identity](https://hadoop.apache.org/docs/stable/hadoop-azure/abfs.html#Azure_Managed_Identity)

But without success.
I am using a deployment as a JAR.

My external location and credentials are ok. I am able to read and write on the storage account with my own notebook with the same cluster. And overwatch is able to write these files :
![image](https://github.com/databrickslabs/overwatch/assets/158584906/b2953837-2d82-4d7d-9f4c-2588acec8df8)

I don't want to use a Service Principal like suggest in this documentation : 
[https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/securityconsiderations/#azure-storage-auth-config](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/securityconsiderations/#azure-storage-auth-config)

Thanks

**Comment by ashlytee** [comment]
Hi @tbaert-prest,

Adding a service principle account is the recommended operation. Without this overwatch cannot work.

Thanks

**Comment by tbaert-prest** [comment]
Hello,

I think it's a mistake.
It makes no sense to configure a managed identity, an external location and a Storage credentials if we need to use a Service Principal ([https://databrickslabs.github.io/overwatch/deployoverwatch/ucedeployment/cloudstorageaccessrequirements/azure/](https://databrickslabs.github.io/overwatch/deployoverwatch/ucedeployment/cloudstorageaccessrequirements/azure/)).

What you propose is a legacy pattern ([https://learn.microsoft.com/en-us/azure/databricks/connect/storage/azure-storage](https://learn.microsoft.com/en-us/azure/databricks/connect/storage/azure-storage)).

The right way is explained here ([https://learn.microsoft.com/en-us/azure/databricks/connect/unity-catalog/](https://learn.microsoft.com/en-us/azure/databricks/connect/unity-catalog/)).

**Comment by ashlytee** [comment]
Hi @tbaert-prest ,

Are you okay to go with it?

**Comment by neilbest-db** [comment]
Hello, @tbaert-prest.  Please pardon the delayed response.  Is this issue still preventing you from running Overwatch successfully?  It looks like you have an invalid or expired value in that configuration field but we can attempt to provide more precise guidance if you are still interested in solving this.  Any additional information or screenshots you can provide would be helpful.  Thanks for your patience.

**Comment by neilbest-db** [comment]
Closing this for now.  Feel free to reopen if you would like to discuss it further, @tbaert-prest.  Thanks for using Overwatch.
