### ISSUE TITLE
External Optimizer is failing.

### ISSUE THREAD

**Issue by mikekimlovelytics** [databrickslabs/overwatch#1264]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.8.1.2

**Describe the bug**
External optimizer job is failing. 

The job just terminates without completing, the following is the email fail notification (picture included below).

The job run output does not have any error message (picture included below). 

The job/cluster setup is as follows (picture included below).

**Screenshots**

<img width="842" alt="email_error" src="https://github.com/user-attachments/assets/976578d2-0dc1-4d0b-8bec-edc400ce14ed">
<img width="1440" alt="jobrun_output" src="https://github.com/user-attachments/assets/50c8a0a3-9601-456e-9a10-ab1b8a727f6a">
<img width="813" alt="job_setup" src="https://github.com/user-attachments/assets/f1713695-f21a-4058-96cf-98e069d5dff4">
<img width="821" alt="cluster_setup" src="https://github.com/user-attachments/assets/9fa41856-08ab-495c-94af-e48a82123bee">

**Issue Reports**
Overwatch runs fine.

**Comment by mohanbaabu1996** [comment]
Can you please try with cluster DBR 11.3 LTS?

**Comment by mikekimlovelytics** [comment]
> Can you please try with cluster DBR 11.3 LTS?

@mohanbaabu1996 This is the error with 11.3 LTS:

<img width="820" alt="11 3LTS_error" src="https://github.com/user-attachments/assets/a7006c05-fa3f-4db3-bda3-aac4221f2361">

**Comment by mikekimlovelytics** [comment]
> Can you please try with cluster DBR 11.3 LTS?

Thank you, it failed again with 11.3, but succeeded with 14.3 LTS. This case can be closed now :)
