### ISSUE TITLE
Spark Dashboards

### ISSUE THREAD

**Issue by joaoaugusto05** [databrickslabs/overwatch#1275]
Is there anyway to provide those queries used in the documentation to create the spark dashboard?
The image can be found at https://databrickslabs.github.io/overwatch/images/_index/spark_dashboard1.png

**Comment by neilbest-db** [comment]
Thanks for your inquiry, @joaoaugusto05.  Those screenshots were provided by a user.  We do not have them but they should not be difficult to implement once you have the necessary [real-time metric collection infrastructure](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics/#using-overwatch-data-to-enrich-realtime-monitoring) in place.  I hope this is helpful.
