### ISSUE TITLE
Spike in Deployment Runtime

### ISSUE THREAD

**Issue by mikekimlovelytics** [databrickslabs/overwatch#1279]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
v0.8.1.2

**Describe the bug**
Upgrading from v0.8.0.0 to the latest v0.8.1.2 (overwatch_2.12-0.8.1.2.jar
) has steadily spiked our weekly Overwatch deployment time (from 10-12 hrs to now 22 hrs). Requesting to know if our pipeline is as optimized as possible.

Please note the following:

-The pipeline runs every Friday midnight EST.
-[External optimizer job](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics/#externalize-optimize--z-order-as-of-060) runs every Thursday midnight EST.
- Upgrade was done between Jul 04 and Jul 11 (screenshot1). Please note the Launched "By Scheduler" times for progressive runtime increases.
- Bronze cluster setting (screenshot2) and Silver/Gold cluster setting (screenshot3) are included.
- All clusters have the following Spark config:
```
overwatch.tableLockTimeout 7200000
spark.driver.maxResultSize 32G
spark.rpc.message.maxSize 1024
```
-Pipeline runs on the following settings:
```
primordial_date: 2024-01-01
max_days: 15
```
Please advise the most cost efficient changes, if any.

**Screenshots**
<img width="1249" alt="screenshot1" src="https://github.com/user-attachments/assets/5e630700-ae67-4184-a849-517ec1299a5a">
<img width="956" alt="screenshot2" src="https://github.com/user-attachments/assets/77601f54-8b28-4371-b840-b1efbd12dcff">
<img width="960" alt="screenshot3" src="https://github.com/user-attachments/assets/fcd93f10-29e7-4ea9-a808-94a8554ad98a">

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by mohanbaabu1996** [comment]
Hi, @mikekimlovelytics ,

We've noticed a performance issue with the silver job run and silver job status modules. It will be fixed in the next release (0820), which we are hoping to release by the end of next weekend.

**Comment by mikekimlovelytics** [comment]
> Hi, @mikekimlovelytics ,
> 
> We've noticed a performance issue with the silver job run and silver job status modules. It will be fixed in the next release (0820), which we are hoping to release by the end of next weekend.

@mohanbaabu1996 Awesome. Do you recommend any changes in our settings?

**Comment by mohanbaabu1996** [comment]
I will let you know if any changes are required for the new release.
Please keep track of the [documentation](https://databrickslabs.github.io/overwatch/changelog/) regarding the new version release.

**Comment by mohanbaabu1996** [comment]
Hi @mikekimlovelytics ,

The new version has been released and that will fix the existing issues. Please swap the JAR to 0820 library.
https://databrickslabs.github.io/overwatch/changelog/
