### ISSUE TITLE
ConnectionStringBuilder.IllegalConnectionStringFormatException: Connection String cannot be parsed.

### ISSUE THREAD

**Issue by ruimaximo** [databrickslabs/overwatch#128]
Hi,

I am facing an issue when overwatch tries to connect to the Azure Event Hub.

Command:
`Bronze(workspace).run()`

Output:
```
CREATING TABLE: overwatch_etl.instanceDetails at /mnt/cluster-logs/overwatch_t/global_share/instancedetails
create table overwatch_etl.instanceDetails USING DELTA location '/mnt/cluster-logs/overwatch_t/global_share/instancedetails'
GOLD VIEW: CREATE: Statement --> create or replace view overwatch.instanceDetails as select * from overwatch_etl.instanceDetails where organization_id = instanceDetails.organization_id 
Overriding spark.databricks.delta.optimize.maxFileSize from 1073741824 --> 134217728
Overriding spark.databricks.delta.optimizeWrite.numShuffleBlocks from 50000000 --> 50000
Overriding spark.databricks.delta.optimizeWrite.binSize from 536870912b --> 512
DEBUG: CLOUD PROVIDER = azure
ConnectionStringBuilder.IllegalConnectionStringFormatException: Connection String cannot be parsed.
```

If I bypass overwatch and try to connect directly using the spark libraries, I can connect to the Even Hub.
 
I am using a cluster with Databricks runtime 7.6 with the libraries:
com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.18
com.databricks.labs:overwatch_2.12:0.4.11

Thank you,
Rui

**Comment by GeekSheikh** [comment]
@ruimaximo -- could you please post your config? Your connection string format appears to be incorrect.

From the [docs](https://databrickslabs.github.io/overwatch/assets/GettingStarted/azure_runner_docs_example.html)
```
private val ehConnString = dbutils.secrets.get(secretsScope, ehKey)
private val azureLogConfig = AzureAuditLogEventhubConfig(connectionString = ehConnString, eventHubName = ehName, auditRawEventsPrefix = ehStatePath)
```
your `ehConnString` should be stored as a secret. The format should begin with `Endpoing=sb://...` 

You can find this `Connection String-primary key` in the portal at the following location
```
eh-namespace --> eventhub --> shared access policies --> Connection String-primary key
```
This is the text that should be stored in your ehConn secret.

**Comment by ruimaximo** [comment]
Yes, my issue was that I was using SAS token instead of the conn_string. 
Working now!
Thank you
