### ISSUE TITLE
Users loses access to views in UC every day after job run

### ISSUE THREAD

**Issue by letssamu** [databrickslabs/overwatch#1303]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.8.0.0 with UC

**Describe the bug**
Users need to access some views that were granted to select:
![image](https://github.com/user-attachments/assets/4994d26e-c567-4509-8f82-9f10e997ce8f)

Every day the job runs and loses the grants

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by mohanbaabu1996** [comment]
Hi @letssamu ,

I've not noticed any issue like this, but please confirm that nobody revoked the access manually or through some other script.

**Comment by letssamu** [comment]
Hi @mohanbaabu1996 ,

I see in the catalog that views are recreated every day in the job execution, so the user loses the access to them:

![image](https://github.com/user-attachments/assets/741e17eb-8b12-4d17-aa78-b7009412c3fd)

**Comment by mohanbaabu1996** [comment]
We checked with the team, and yes, the views will be recreated on every pipeline run as per the architecture. But to overcome, we can create a new notebook with all the grant commands at the consumer database level and add them as a part of the pipeline at the end, so that permission will be assigned.
