### ISSUE TITLE
Overwatch job stuck

### ISSUE THREAD

**Issue by varungorantla** [databrickslabs/overwatch#1306]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.8.1.2

**Describe the bug**
Overwatch job keeps on running without starting. Noticed this happens twice. It works after cancelling and retrying.
**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by mohanbaabu1996** [comment]
Hi @varungorantla,
Hope you doing good and sorry for the delay.
It looks like a cluster issue, please let me know if you're still facing it.
Thanks!
