### ISSUE TITLE
table job only contains "action" == "update" ? 

### ISSUE THREAD

**Issue by ruimaximo** [databrickslabs/overwatch#131]
Hi,

I am not sure if this is a bug or the desired behavior, but the table job is only storing jobs with action == update. 

We have several scheduled jobs that run notebooks.

We would like to map the records in the table "SparkJob" with the table "notebook". According to your data model on the png Overwatch_gold this could be done by joining SparkJob.db_job_id with job_job_id and by joining job_notebook_path with notebook.notebook_path. 

However we are facing the following issues:
a. the table job only contains jobs that had a configuration change since we started overwatch
b. if we manually change the configuration of an existing scheduled job, a new record appears in the table job.  This record has matching  SparkJob.db_job_id with job_job_id. However, it has NULL in the notebook_path field. Then we cannot map it with the notebook table.

**Comment by GeekSheikh** [comment]
A. This is correct. The data prior to your primordial date (i.e the earliest audit data, EH for Azure and audit log data for AWS).  Overwatch attempts to fill in missing data for jobs and jobRuns for existing job configs using api calls to jobs endpoint but this is not always 100% complete. If you're missing metadata in job table, please look in `<etlDB>.jobs_snapshot_bronze` as a snapshot of all configured jobs is taken each time Overwatch runs (thus ensure to select the greatest Overwatch_SnapTS that has your data). I will look at this more on Monday as I am surprised that you are missing existing job configs in the job table.

B. Same as above, the audit data only shows edited data unfortunately, thus in the first days of Overwatch there are often gaps. Again, I thought this would be handled automatically with the snapshot data, I will review Monday, for now, please use the `jobs_snapshot_bronze` table as it holds a full snapshot of all exisitng job configs and should hold the notebook path as well. spark_job --> job WITH lookup of missing data from jobs_snapshot.

**Comment by GeekSheikh** [comment]
@ruimaximo -- after looking at this a bit deeper, I am curious as to what it is you're actually trying to accomplish. Why do you want to join sparkJob to job? If you're looking for costs for jobs by notebook, that's quite simple to do from jobRunCostPotentialFact. If you're looking for spark metrics by job or notebook, that takes a few more joins but hopefully not too bad. [Here's a LINK](https://drive.google.com/file/d/1oA2tqZyycZKTfyelsf9vKrwfMPxTvPyu/view?usp=sharing) to download an HTML of a notebook I through together that should give you what you need to resolve the issue.

Bets of luck, please let me know if you have any more questions.

FULL LINK
https://drive.google.com/file/d/1oA2tqZyycZKTfyelsf9vKrwfMPxTvPyu/view?usp=sharing

**Comment by ruimaximo** [comment]
Thank for your answers.

Your notebook is useful, I appreciate it very much.

Answering to your question. 
I am trying to accomplish a way to help troubleshooting the reason why certain job fails. For that I am for example mapping the field overwatch.sparkjob.job_result.Exception with the name of the notebook associated. I found out that the name of the notebook can be found in the column new_settings of the table job, even when it has a null  in the column name. Since we have several jobs that were created long time a go it is a bit of inconvenience changing the configuration of each jobs so that there is an entry to that job with the relevant metadata in the job table. 

In a hope that it would populate the job table, I changed the Primordial Date of the overwatch configuration to a date prior to the creation of the jobs. It did not help. Maybe it is because the overwatch databases were already created? Do I need to delete the databases before changing the Primordial Date? Should I have increased the Max Day?

**Comment by GeekSheikh** [comment]
@ruimaximo no no, the notebook I gave you should get everything for you. Note how it grabs the current existing jobs and cross-references it with old-updates and results in the latest notebook path.

You cannot put primordial date to a date prior to your audit log and expect to get any new platform data. If you have historical cluster logs, you can do that but it's very likely that you will be missing Databricks platform metadata. To do this, yes you will need to drop your current spark data and reset the primordial date. I suggest a full rebuild.

When you say `why certain jobs fail` do you mean spark jobs or db_jobs. If you're just looking for databricks jobs and their failure reasons, you don't need to join to sparkJobs at all. See the new notebook for DB job failure summaries.

[HTML EXAMPLE](https://drive.google.com/file/d/1JY3aCllZCjYkI-4fOeZjAzhiBOP6_wi1/view?usp=sharing)

[SCALA Source Example](https://drive.google.com/file/d/18foYh3n_uLIZKVzm_X8HneR73PagyVnn/view?usp=sharing)

**Comment by ruimaximo** [comment]
Thank you very much for the notebook.
Using the jobs_snapshot_bronze is very useful.
Problem solved

**Comment by GeekSheikh** [comment]
FYI - [Issue 154](https://github.com/databrickslabs/overwatch/issues/154) was opened to improve the answer to this question.

**Comment by GeekSheikh** [comment]
#154 linked
