### ISSUE TITLE
Init script to config cluster log delivery Global Scope

### ISSUE THREAD

**Issue by ruimaximo** [databrickslabs/overwatch#136]
A nice improvement that overwatch could have would be to include a Global Scope init script in the repo that could automate the cluster log delivery configuration. This is specially useful when you have userspaces with hundreds of cluster jobs.

**Comment by GeekSheikh** [comment]
Could you say more? We do require our customers to enable audit logging. If jobs are submitted programmatically [through an API endpoint](https://docs.databricks.com/dev-tools/api/latest/jobs.html#jobs-api), an existing cluster spec or [new cluster spec](https://docs.databricks.com/dev-tools/api/latest/jobs.html#newcluster) definition must be provided. Through that process, the user/enterprise should alter the definition to include the appropriate logging location. This is different for each customer.

For reference [here is the LogConf section of the clusterSpec](https://docs.databricks.com/dev-tools/api/latest/clusters.html#clusterlogconf) that should be populated for automated cluster creation whether through a job or clusters/create endpoint.

If your enterprise allows for ad-hoc user-created clusters, it's imperative that you enable a [cluster policy](https://docs.databricks.com/administration-guide/clusters/policies.html) that automatically populates the proper logging path. If your admins create clusters for your users upon approved request, these admins must be trained to create the cluster with an appropriate logging path, but remember they too can utilize a cluster policy that can require them to fill it out. Often times, admin groups create clusters through the clusters/create API endpoint, here the default scripts/templates should be updated to include an appropriate logging location.

**Comment by ruimaximo** [comment]
Thank you for your prompt answer.

I agree that a cluster policy is the way to go for the new jobs that the users will create. I will follow your advise and implement it for the new jobs. However, I am not aware that these policies modifies definition of already specified clusters. 

To give you our context:
Our workspace is restricted to a few users and they have plenty of liberty. The clusters that we created manually have audit logging enabled.
But we already have more than 100 submitted databricks jobs that instantiate a new cluster when they are triggered. These were submitted manually by the users and they do not have the audit logging. I could develop a script that would change the config of these jobs using the databricks CLI. 

Is there a simpler way that I am not seeing?

Thank you!

**Comment by GeekSheikh** [comment]
Ahh, good question. For existing clusters, there's a nice little script you can use to edit the logging location for all existing clusters. Be careful and test this as it is a global script, I take no responsibility if it messes something up. :P You've been warned. You can do the same thing with existing job specs just use the jobs API endpoints

You do need to attach the Overwatch JAR as API calls through Overwatch are very simple

All the script does is gets all clusters that don't have the logging location you want, and edits the cluster to set the location. NOTE: this edit will restart any running clusters (if you remove the state filter) so be sure that's ok when you do it. You can filter the cluster list down in Cmd4 to scope down the number of clusters on which you execute.

[HTML Notebook](https://drive.google.com/file/d/1A8fR1m6isXCdHhydnA4X7186JHMiwI0-/view?usp=sharing)
[Source Code](https://drive.google.com/file/d/1iQq5TDdyPle7C0g2gLdlnytBByjNza6w/view?usp=sharing)

**Comment by GeekSheikh** [comment]
Hi @ruimaximo -- I hope this resolved your issue, we'll be closing this ticket soon if we don't get any response. You're always welcome to reopen or open a new one and reference this one.

**Comment by ruimaximo** [comment]
thank you! issue solved.
