### ISSUE TITLE
Metrics about running Databricks streaming jobs

### ISSUE THREAD

**Issue by ruimaximo** [databrickslabs/overwatch#142]
Hi,

 We would like to store these  metrics for Databricks streaming jobs,  while the job is running (not after the job has stopped):
1. the metrics that we can see at the datarbicks GUI:
![image](https://user-images.githubusercontent.com/32925235/123067120-ff234980-d410-11eb-9784-052ab77d7455.png)
2. additional metrics like CPU and memory consumption per DB.

The purpose is to monitor the resources usage at db job level in a streaming scenario. 

I can find metrics of type 1 once the streaming job fails or it is stopped by the user. But I cannot find the metrics of the running db streaming jobs in the tables. Since streaming jobs are not supposed to terminate, the information of the running jobs is more valuable. 

Is Overwatch storing these? 
If not, is there any plans on the roadmap to be included? Any suggestions for alternative solutions?

Thank you,
Rui

**Comment by GeekSheikh** [comment]
That is correct. At this time we haven't had the cycles to build out the intermediate upserts to enable the data model to this granularity. We have discussed this at length internally. Our dev team is growing and we hope to tackle this before long. I've gone ahead and typed up [issue (143)](https://github.com/databrickslabs/overwatch/issues/143) so you, and others, can track our progress on this.

I have built many of these streaming applications and batch reporting/monitoring processes aren't the right way to go.

That said, I usually handle this in a few ways when monitoring streaming data:
- Custom listener that sends update metrics wherever I need them at the end of each batch or after some period passes whichever comes first
- A reporting structure of streaming target tables that accept the streams mini-batch metrics at the end of each minibatch. This ensures I always have up-to-date insights on streaming processes.

**Comment by GeekSheikh** [comment]
@ruimaximo -- did this resolve your issue / question?

**Comment by ruimaximo** [comment]
Yes, thank you.

________________________________
Fra: Daniel Tomes ***@***.***>
Sendt: tirsdag 29. juni 2021 15.58
Til: databrickslabs/overwatch ***@***.***>
Kopi: Rui Esteves ***@***.***>; Mention ***@***.***>
Emne: Re: [databrickslabs/overwatch] Metrics about running Databricks streaming jobs (#142)


@ruimaximo<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fruimaximo&data=04%7C01%7Crui.esteves%40bouvet.no%7Cde591a49ebe2462f768b08d93b06022f%7Cc317fa72b39344eaa87cea272e8d963d%7C1%7C0%7C637605719263511389%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jNZ8vpIhVJACJN0ct%2BsId39YwgZc%2FBkzuS%2BzcgHFWGU%3D&reserved=0> -- did this resolve your issue / question?
