### ISSUE TITLE
Runner notebook uses deprecated workspace arguments

### ISSUE THREAD

**Issue by uucico** [databrickslabs/overwatch#212]
https://databrickslabs.github.io/overwatch/assets/GettingStarted/aws_runner_docs_example_042.html (and the associated dbc) uses the deprecated workspace args:

val workspace = Initializer(Array(args), debugFlag = true)

instead of 

val workspace = Initializer(args) // 0.4.2+

according to the docs.

**Comment by GeekSheikh** [comment]
thanks @uucico -- overlooked this change for AWS. Appreciate the info, I'll get this fixed right away.
