### ISSUE TITLE
Docs Typos

### ISSUE THREAD

**Issue by alanjack-db** [databrickslabs/overwatch#232]
While looking through the docs I found two typos. I'm happy to fix these, but don't seem to have access to pages on this account.

On https://databrickslabs.github.io/overwatch/gettingstarted/configuration/ "Endpoing" should be "Endpoint"
On https://databrickslabs.github.io/overwatch/environmentsetup/azure/ "Tht Event Hub" should be "The Event Hub"

**Comment by GeekSheikh** [comment]
keep em coming, we'll get these resolved. Thank you!
