### ISSUE TITLE
orgId may be not be intuitive for multiple workspace overwatch users

### ISSUE THREAD

**Issue by uucico** [databrickslabs/overwatch#234]
In multiple workspace setups the orgId is used to segregate the data between multiple workspaces. Many users actually know the workspace name / vanity URL for their workspaces but may not use the orgId frequently.

@psg2 mentioned that if perhaps in the gold tables or in the consumption database views we could have an additional column to add the workspace name / vanity URL, in addition to the orgId.

Does that make sense?

`dbutils.notebook.getContext.tags("browserHostName")` would give us the vanity URL. i.e. [demo.cloud.databricks.com](url)

But couldn't find exactly in the APIs or context how to get the actual workspace name.

Potential options would be:

- Creating CASE WHENs in the view definition, could be challenging as each instance will not know about other workspaces in the multi-workspace setup;
- Enriching only the gold tables with the new column to avoid too much redundant data in bronze/gold.

Shall we discuss if this could be an interesting addition?

**Comment by GeekSheikh** [comment]
yes, this makes sense. Adding to backlog. 

Regarding browser host name, what about e2? what about azure? The challenge has always been ensuring a canonical name across all workspaces that works across all circumstances. 

For now, perhaps you can create a lookup table that maps org_id to vanity name for your customer?

**Comment by GeekSheikh** [comment]
@uucico -- This may be helpful in the meantime.

Create a Map table in the etl database that maps org_id to friendly name -- scala would like this
```
val workspaceNameLookup = Seq(
  ("org_id1", "workspace_name1"),
  ("org_id2", "workspace_name2"),
  ("org_id3", "workspace_name3"),
  ("org_id4", "workspace_name4")
).toDF("organization_id", "workspace_name")
  .coalesce(1)
  .write
  .mode("overwrite")
  .format("delta")
  .saveAsTable("overwatch_global_etl.workspaceMap")
```

join it to any queries to add workspace_name where desired, below is an example of joining it to pipeline_report to create the view desired with the workspace_name
```
create or replace view overwatch_global_etl.pipReport as 
select pipReport.organization_id, workspace_name, moduleID, moduleName, primordialDateString, 
  from_unixtime(fromTS / 1000.0) as fromTSt, from_unixtime(untilTS / 1000.0) as untilTSt, 
  status, recordsAppended, fromTS, untilTS, Pipeline_SnapTS, Overwatch_RunID
from overwatch_global_etl.pipeline_report pipReport
left join overwatch_global_etl.workspaceMap workspaceMap
  on pipReport.organization_id = workspaceMap.organization_id
order by Pipeline_SnapTS desc, moduleID desc
```
