### ISSUE TITLE
I cannot consolidate multiple workspaces into one database.

### ISSUE THREAD

**Issue by man40** [databrickslabs/overwatch#237]
I need oraganization_id as a config parameter here:
https://github.com/databrickslabs/overwatch/blob/main/src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala#L430
My goal is to run multiple workspaces into one database, segregated by the column organization_id (workspace_id). I have a notebook that runs on one workspace that collects logs from Azure Event Hubs of multiple workspaces. Since I cannot set the organization_id, they all come as the workspace_id (organization_id) of the workspace I ran the notebook in.

**Comment by GeekSheikh** [comment]
That's correct. As of now we do not support multiple workspaces being logged to the same event hub. Please see #204, for tracking when this will be available.

**Comment by man40** [comment]
I do have multiple event hubs. My problem is, I dont want to have multiple destination databases for Bronze, Silver, Gold, user.
Thanks for replying!

**Comment by GeekSheikh** [comment]
@mohanbaabu1996 -- I'm assigning this to you. Please help @man40 get his targets set up properly so he can have one output target.

**Comment by mohanbaabu1996** [comment]
Hello @man40 , if possible, please scheduled a meeting and i'm from IST time zone
