### ISSUE TITLE
Changes on publicFile log4j appender disturbs Overwatch?

### ISSUE THREAD

**Issue by rodrigoassumpcao** [databrickslabs/overwatch#239]
Following this instructions we can change log4j configs: https://kb.databricks.com/clusters/overwrite-log4j-logs.html

Changes on publicFile appender, such as Layout changes or ConversionPattern changes will disturb Overwatch operation?

**Comment by GeekSheikh** [comment]
great question, no not log4j. Overwatch only uses the spark event logs thus you should be just fine to use whatever pattern you want on log4j. Please re-open this ticket if you have issues.
