### ISSUE TITLE
azure setup documentation points to AWS docs about billing

### ISSUE THREAD

**Issue by alexott** [databrickslabs/overwatch#25]
In the section `With Databricks Billable Usage Delivery Logs` in `EnvironmentSetup/azure.md`, we point to the AWS docs about billing.  On Azure, billing information isn't provided this way. We need to either remove this section, or rework it according to the Azure documentation

**Comment by GeekSheikh** [comment]
I believe this has been resolved. Closing for now, please let me know if you still see something incorrect there.
