### ISSUE TITLE
Bronze_ClusterEventLogs module fails 

### ISSUE THREAD

**Issue by dyon78** [databrickslabs/overwatch#259]
Hi, 
 I have an aws setup with no auditing logs enabled and after running Bronze jobs in pipeline report for 1005 module I see following error message: 
`FAILED --> ERROR: Bronze_ClusterEventLogs FAILED --> Message: cannot resolve '`serviceName`' given input columns: []; 'Project [CASE WHEN (('serviceName = clusters) AND 'actionName LIKE %Result) THEN 'requestParams.clusterId WHEN (('serviceName = clusters) AND 'actionName IN (permanentDelete,delete,resize,edit)) THEN 'requestParams.cluster_id WHEN (('serviceName = clusters) AND ('actionName = create)) THEN get_json_object('response.result, $.cluster_id) ELSE 'requestParams.cluster_id END AS clu...`

Could you help with troubleshooting this please?

**Comment by mohanbaabu1996** [comment]
Hi @dyon78, enabling audit logs is must for overwatch, check the environment [setup](https://databrickslabs.github.io/overwatch/gettingstarted/#environment-setup) and [AWS](https://databrickslabs.github.io/overwatch/environmentsetup/aws/) from the docs.

**Comment by mohanbaabu1996** [comment]
Thanks @dyon78 for letting us know.
