### ISSUE TITLE
Non-standard default_tags should be represented as map, not as struct

### ISSUE THREAD

**Issue by alexott** [databrickslabs/overwatch#260]
In current implementation, the `default_tags` field is treated as struct, but besides the values defined in the [API specification](https://docs.databricks.com/dev-tools/api/latest/clusters.html#get), it could be populated with additional tags, coming from the Azure resource group, or workspace level. And there are situations when these tags could differ in casing, breaking the data processing

Also, should we have a column with all tags combined together, instead of having `custom_tags` & `default_tags` separately?

**Comment by GeekSheikh** [comment]
@alexott this is already handled with the [structToMap](https://github.com/databrickslabs/overwatch/blob/fb7f828981da64eab71dedbc529c39a746c57690/src/main/scala/com/databricks/labs/overwatch/utils/SchemaTools.scala#L120) function implemented in BronzeTransforms in several places, [here's one example](https://github.com/databrickslabs/overwatch/blob/fb7f828981da64eab71dedbc529c39a746c57690/src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala#L191).

**Comment by alexott** [comment]
Yes. But wasn't applied to default tags
