### ISSUE TITLE
Documentation - Azure - add note for maven coordinate vs the jar

### ISSUE THREAD

**Issue by meganfeichtel** [databrickslabs/overwatch#263]
For the Azure jobs, it would be good to point out specifically with a Note that only the "Maven coordinate" works for the azure-eventhubs-spark integration package. A customer implemented this job trying to use the downloaded jar of the same version and ran into issues, so it would be helpful to highlight the requirement.
See here: https://databrickslabs.github.io/overwatch/gettingstarted/#cluster-dependencies

**Comment by GeekSheikh** [comment]
hmm, that's interesting that the downloaded jar would cause issues. My guess is that they downloaded the wrong JAR, I will test and if this is true, we'll get a note added to the docs, thanks.

**Comment by alexott** [comment]
The downloaded jars doesn't include dependencies (see [list here](https://mvnrepository.com/artifact/com.microsoft.azure/azure-eventhubs-spark_2.12/2.3.21)) that needs to be downloaded as well, together with dependencies of dependencies...

**Comment by GeekSheikh** [comment]
Hello, I believe this issue has been resolved. Please re-open with updated details if not.

Thank you.
