### ISSUE TITLE
Table clusterstatefact_gold is not loaded since Jan 11th 2022

### ISSUE THREAD

**Issue by saikumar-gouddubbaka** [databrickslabs/overwatch#300]
Hi Team,

We started using Databricks overwatch since Oct 2021 and the mentioned tables were generated and we are able to query.

But since Jan 11th 2022 , the table **overwathc.clusterstatefact_gold** is not loading with latest data. Can you please help to troubleshoot the issue

**Comment by Neha-vs123** [comment]
Hi Saikumar, 

What is the overwatch version you are using?
Please share with us the pipeline report table from ETL database.

**Comment by saikumar-gouddubbaka** [comment]
HI Neha. Please find the Pipeline Report attached

[PipeLine report .csv](https://github.com/databrickslabs/overwatch/files/7986092/PipeLine.report.csv)
.

**Comment by Neha-vs123** [comment]
Are you using single workspace or multi workspace deployment? 
From the report, I assume that you are using AWS and the overwatch version is 0506. Please confirm.
Please let me know your time zone.

**Comment by saikumar-gouddubbaka** [comment]
It is created for single workspace right now. I could see below error for the Module 1005 in the pipeline report from 01/13

ModuleID - 1005

FAILED --> 
ERROR:
Bronze_ClusterEventLogs FAILED -->
Message: cannot resolve '`organization_id`' given input columns: [__overwatch_ctrl_noise];
'RepartitionByExpression ['organization_id, __overwatch_ctrl_noise#26784], 200
+- Project [cast((rand(-164607708925729314) * cast(32 as double)) as int) AS __overwatch_ctrl_noise#26784]
   +- LocalRelation <empty>

**Comment by saikumar-gouddubbaka** [comment]
In the job parameters we are giving as below. 

"maxDaysToLoad\":120,\"primordialDateString\":\"2021-10-01\

is it causing the issue.. do i need to change the primordialDateString to latest ?

**Comment by Neha-vs123** [comment]
Shall we connect now to check the issue?

**Comment by saikumar-gouddubbaka** [comment]
Sure. You can connect below webex "https://collaborate.webex.com/join/saikumar.gouddubbaka"

**Comment by saikumar-gouddubbaka** [comment]
HI Mohan & Neha,

I am able to run the cmd9 and list the clusters after updating the secrets. Please let me know once new version 0.6.0.2 is released and setup a meeting with me(I am available in IST 1 PM to 10 PM) . Really appreciate your help :)

**Comment by GeekSheikh** [comment]
@saikumar-gouddubbaka -- there's an issue with the spark tables in 0602. Docs should be getting updated today to notify of the issue and 0603 should be out in maven tomorrow (hopefully). I suggest waiting for 0603 before completing your upgrade.

**Comment by saikumar-gouddubbaka** [comment]
Sure Thankyou

**Comment by Neha-vs123** [comment]
Hi Saikumar,

Overwatch 0603 version is released. Can we connect from 3 to 4 pm IST? Please send us the Webex link if it's okay for you.

**Comment by saikumar-gouddubbaka** [comment]
Sure Neha. Please join the below webex at 3:00 PM IST.

"https://collaborate.webex.com/join/saikumar.gouddubbaka"

**Comment by saikumar-gouddubbaka** [comment]
Do you production issue. I
 need to reschedule the meeting to 5 PM IST. is it fine with you.?

**Comment by Neha-vs123** [comment]
Okay. Let's connect at 5 pm IST.

**Comment by Neha-vs123** [comment]
@saikumar-gouddubbaka Was the deployment successful? Please let us know the updates.

**Comment by saikumar-gouddubbaka** [comment]
Hi Neha, The deployment went successfully. I am closing this request . Really Appreciate yours's & Mohan  help.
