### ISSUE TITLE
sparkEvents dependency on log4j needs clarification in docs

### ISSUE THREAD

**Issue by uucico** [databrickslabs/overwatch#301]
A customer asked if they could change log4j appenders without affecting overwatch's sparkEvents ingestion. It turns out we're using eventlog json files which are actually created by our custom DBCEventLoggingListener and not log4j.

There's a section Q4 related to cluster log shipping. While probably a corner case, maybe we could document the question related to this dependency? Something in the lines of:

Q5: If I change logging formats in log4j, will this affect overwatch?

Answer: No, you can change log4j file formats for Spark and this will not affect Overwatch. The SparkEvents module ingests eventlog JSON files which are produced by a custom spark listener (DBCEventLoggingListener), not the driver and executor logs generated by log4j.

**Comment by GeekSheikh** [comment]
Answers are correct, will take this as a todo for docs. thanks

**Comment by GeekSheikh** [comment]
Added to docs, released Feb 2, 2022.
