### ISSUE TITLE
SparkExecution and SparkJob table not being populated

### ISSUE THREAD

**Issue by smhood92** [databrickslabs/overwatch#306]
We are seeing errors when our databricks jobs run where we get the following problem:

```
22/02/08 18:17:34 INFO PipelineTable: FILTERING: Gold_SparkExecution using cron columns: startTimestamp
22/02/08 18:17:34 WARN Module: WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1644344176457 exceeds that of an upstream requisite module. with untilTS of: 1644300279978. Setting current module untilTS == min requisite module: 1644300279978.
22/02/08 18:17:34 INFO PipelineFunctions$: APPLIED FILTERS:
MODULE_ID: 3013
MODULE_NAME: Gold_SparkExecution
FILTERS:
(('startTimestamp >= 1644300279978) AND ('startTimestamp < 1644300279978))('organization_id = 4154560703287719)
```

As you can see the upper and lower bound of this filter that is being applied are the same, resulting in never getting any actual data. We have had the table populate data before but every job seems to be hit or miss on whether or not the code picks up new data. 

We are curious as to how these timestamps are derived and why the code doesn't seem to want to populate new data a majority of the time.

**Comment by smhood92** [comment]
Azure Cloud
```
<dependency>
    <groupId>com.databricks.labs</groupId>
    <artifactId>overwatch_2.12</artifactId>
    <version>0.5.0.6</version>
</dependency>
```

Pipeline_Report:
[export.csv](https://github.com/databrickslabs/overwatch/files/8042391/export.csv)

**Comment by smhood92** [comment]
As you can see from alot of these module runs, the from and until TS are the same for the upper and lower ranges for some reason.

**Comment by shravanshibu90** [comment]
Hi, is this single deployment workspace or multiple?

**Comment by smhood92** [comment]
In this case its single, however, we do have some environments where it's two workspaces using the same cluster log location.

**Comment by smhood92** [comment]
Oh, so the primordial date shouldn't change from initialization? The documentation made it seem that it was supposed to be 5 days from run time.

**Comment by smhood92** [comment]
As far as a time to meet up, I am in CST so the earliest I can meet up would be 8 AM CST (7:30 PM IST).

**Comment by shravanshibu90** [comment]
Kindly join us for a call using this call : GitHub Ticket - 306 - [Meeting link
](meet.google.com/dck-euxe-ipw)
You can write to me to shravan.shibu@databricks.com

**Comment by GeekSheikh** [comment]
@smhood92 -- that is correct. The primordial date is a static date per workspace. It represents the first date that audit logs were present and the first date of the pipeline. It's there to control the start date for the initial run, please set it and leave it per workspace. Please let us know if you have more questions.

Please find the [configuration documents here](https://databrickslabs.github.io/overwatch/gettingstarted/configuration/#overwatchparams).

**Comment by shravanshibu90** [comment]
@smhood92 is the issue resolved, do you need any kind of further assistance?
