### ISSUE TITLE
Bronze_SparkEventLogs Failed to Merge Fields

### ISSUE THREAD

**Issue by nrabidea** [databrickslabs/overwatch#307]
I received this failed error for only the Bronze_SparkEventLogs table after Overwatch ingestion executed for one of my Databricks E2 workspaces. 
This is the first time an error like this has occurred mentioning merge field and merge incompatible data type failures.
We are currently using Overwatch 0.5.0.6 with multiple workspaces, this error only occurred for one table in one workspace.

> FAILED --> ERROR: Bronze_SparkEventLogs 
FAILED --> Message: Failed to merge fields 'TaskEndReason' and 'TaskEndReason'. 
Failed to merge fields 'AccumulatorUpdates' and 'AccumulatorUpdates'. 
Failed to merge incompatible data types StructType(StructField(CountFailedValues,BooleanType,true), StructField(ID,LongType,true), StructField(Internal,BooleanType,true), StructField(Update,StringType,true)) and StringType

**Comment by shravanshibu90** [comment]
This is in one workspace or all?

**Comment by nrabidea** [comment]
[log4j-active_log_2_10_22.txt](https://github.com/databrickslabs/overwatch/files/8051749/log4j-active_log_2_10_22.txt)

This is the log4j-active.log file from that day's ingestion run from the workspace.  The same ingestion run happened today with no failure in the same workspace.

**Comment by GeekSheikh** [comment]
@nrabidea my guess is that the first run included very little data for the cluster logs. We are required to implicitly determine the schema for bronze as it's very different from customer to customer. We then evolve the schema as necessary but in this case this is not a valid evolution.

Please try setting the config below and rerunning. This may resolve your issue but it may not. If it does not, please work with @shravanshibu90 to get this table (and data) dropped, the pipeline rolled back and this re-ingested.

**Cluster Config**
`spark.databricks.delta.schema.autoMerge.enabled, true`

**From Inside the Runner Notebook**
`spark.conf.set(spark.databricks.delta.schema.autoMerge.enabled, true)`

**Comment by shravanshibu90** [comment]
@nrabidea is the issue resolved, do you need any kind of further assistance?

**Comment by nrabidea** [comment]
Thank you for your help. I have added that line into the config for each workspace's ingestion job, I have not had any issues or failures since then.

**Comment by shravanshibu90** [comment]
Thanks for the information, in future if you have any issues please create a ticket.

**Comment by shravanshibu90** [comment]
Thanks for the information, in future if you have any issues please create a ticket.
