### ISSUE TITLE
Spark Job - several nulled fields -- version 0.6.0.3

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#310]
Several fields like execution_id, notebook_id, job_id, etc are null in sparkJob table as of version 0.6.0.3

Cause: The schema cleanser was updated in 0603 to covert special characters to "" (originally) to "_" (0603). These map keys in the source had periods between words and thus the keys got converted to an _ instead of null string.

Solution: update the map keys to have the underscores.

**Comment by GeekSheikh** [comment]
To recover data that was nulled out while running 0603, please import and follow the instructions on the attached dbc. It's a folder with 2 notebooks, please just run, "RUNME".
[git_310_rebuild.zip](https://github.com/databrickslabs/overwatch/files/8210775/git_310_rebuild.zip)

**Comment by lukhnov** [comment]
dropRelevantSparkEvents() is missing in the funcs - this prevents upgrade
