### ISSUE TITLE
Details about Instance Profile

### ISSUE THREAD

**Issue by saikumar-gouddubbaka** [databrickslabs/overwatch#311]
I am looking for details about  Instance Profile . In what table we can find them ?

**Comment by mohanbaabu1996** [comment]
Hi Sai,
Please find the instancedetails table from ETL database

**Comment by GeekSheikh** [comment]
Actually, upon further review, we're trying to locate that for you. We have engaged our internal teams to determine if it's being delivered, if it is not, they will need to create a PR for Datarbricks. Once that's deployed, we can then begin delivering that for you. Thanks for bring this to our attention. We'll check back in with you after we have more info.

**Comment by GeekSheikh** [comment]
This is being addressed by Databricks internal. once it's released it will be added to Databricks Logs it will be added to Overwatch.

For internal Tracking [CJ-33542](https://databricks.atlassian.net/browse/CJ-33542)

**Comment by GeekSheikh** [comment]
Update - Please note that this has entered development at Databricks. Once it's released we will integrate into Overwatch.

**Comment by GeekSheikh** [comment]
@mohanbaabu1996 -- can you confirm that this was resolved by #361  and that instanceProfile is now available in Gold?

**Comment by GeekSheikh** [comment]
I'm going to leave this open as we should explore utilizing the instanceProfile data from new bronze snapshot added as part of #432 especially for first runs

**Comment by mohanbaabu1996** [comment]
@GeekSheikh Yes, I could view the instanceProfile information for some of the clusters with instanceProfile enabled (to which I have access in demo and e2-demo-west workspaces). I evaluated the cluster gold table's **_security_profile.instance_profile_arn_** field.
