### ISSUE TITLE
Issues deploying to multiple workspace sharing a Hive Catalog

### ISSUE THREAD

**Issue by smhood92** [databrickslabs/overwatch#316]
Getting the following error trying to deploy to Overwatch to a second workspace that shares a Hive Catalog:
```
com.databricks.labs.overwatch.utils.BadConfigException: The DB: overwatch_etl exists at location dbfs:/mnt/overwatch/248988692605798/overwatch_etl.db which is different than the location entered in the config. Ensure the DBName is unique and the locations match. The location must be a fully qualified URI such as dbfs:/...
at com.databricks.labs.overwatch.pipeline.Initializer.dataTargetIsValid(Initializer.scala:362)
```

Looks like there was a similar issue here in this issue:
https://github.com/databrickslabs/overwatch/issues/308

We upgraded our overwatch version from 0.6.0.3 -> 0.6.0.4 however still seeing this error.

Nothing in the documentation seems to indicate that we can't use the same db for multiple workspaces.... Any help is appreciated here.

**Comment by GeekSheikh** [comment]
@smhood92 #308 was dealing with an issue in the externalize optimize main class, totally different. This error is there to protect the user from making a mistake.

If you're saying you have a shared metastore, there are some nuance differences to ensuring a safe deploy to a shared metastore. I will have someone reach out to you to help you get deployed.

**Comment by mohanbaabu1996** [comment]
@smhood92 Shall we meet for a call and what's your timezone ?

**Comment by smhood92** [comment]
@GeekSheikh thanks for the clarification! @mohanbaabu1996 Absolutely, I am in the CST timezone.

**Comment by mohanbaabu1996** [comment]
@smhood92 Please send us your id , we can have a call and i'm from IST timezone

**Comment by mohanbaabu1996** [comment]
thanks
