### ISSUE TITLE
Ambiguous reference to fields causes failure on Silver_JobsStatus

### ISSUE THREAD

**Issue by mwoods329** [databrickslabs/overwatch#317]
The error message appears to implicate that it is using AWS resource tags on the cluster/job as column names.   Some of these tags were created in upper case, some mixed case, some lower case.  Overwatch appears to be setting those up as separate columns and then erring out when attempting to locate one of them.

EMPTY: 2011-Silver_JobsRuns Module: SKIPPING Downstream modules that depend on this module will not progress until new data is received by this module. Module Dependencies: 1004, 2010, 2014 Requires 2010 is in a failed state: FAILED --> ERROR: Silver_JobsStatus FAILED --> Ambiguous reference to fields StructField(Client_UNIQUESUFFIX_Gpi2C7,StringType,true), StructField(Client_UNIQUESUFFIX_Gpi2C7,StringType,true) org.apache.spark.sql.AnalysisException: Ambiguous reference to fields StructField.

**Comment by Neha-vs123** [comment]
Hi @mwoods329,

Which version of overwatch are you using? 
Please send us the pipeline_report table from the ETL database.

**Comment by mwoods329** [comment]
Hello @Neha-vs123 
Currently using: com.databricks.labs:overwatch_2.12:0.6.0.4
Timezone is Eastern/US.
Where do I send the pipeline report table to?

**Comment by Neha-vs123** [comment]
Please share the report in GitHub chat so that it will be visible to all.
You can reach out to me at neha.vs@databricks.com.

**Comment by mwoods329** [comment]
@Neha-vs123
[pipeline_report_.xlsx](https://github.com/databrickslabs/overwatch/files/8215102/pipeline_report_.xlsx)

**Comment by Neha-vs123** [comment]
Should we meet today at 10 a.m. EST or Tuesday at 9 a.m. EST?

**Comment by mwoods329** [comment]
Tuesday 9am EST

**Comment by mwoods329** [comment]
Hi @Neha-vs123 following your recommendations I completed the workspace cleanup and then used the runner notebook as we had discussed.  The same failure is still occurring.  See attached report.
[export(5).csv](https://github.com/databrickslabs/overwatch/files/8256139/export.5.csv)
