### ISSUE TITLE
The processing time range of overwatch

### ISSUE THREAD

**Issue by skywalker0618** [databrickslabs/overwatch#325]
Hi Databricks Team!

One question. For the overwatch job, in each run we have a processing time range. For example, in one run, say the processing time range is [2/1/2022, 2/5/2022] both inclusive. Hence it will process jobs that fall within this time range, wondering if it’s according to job start time, or job end time, or the time when the "job end event" arrived? Or some other events?

Thanks,
Shihuan

**Comment by mohanbaabu1996** [comment]
Hi Shihuan,

We can calculate the job processing time using the "job runtime" [field](https://databrickslabs.github.io/overwatch/dataengineer/definitions/#jobrun) in the jobrun table in the overwatch ETL database.
Yes, it calculates the difference in time between start time and end time.

![image](https://user-images.githubusercontent.com/87074323/159210423-6d088d6e-a9b5-498c-a5f3-fb900c963cfb.png)

**Comment by mohanbaabu1996** [comment]
Hi Shihuan,

Please feel free to reopen this ticket if you require more assistance in the future.

**Comment by skywalker0618** [comment]
Hi,

My question was, the Overwatch job uses "job start time", or "job end time", or "the time when the job end event arrived" to judge if a job falls into the processing time range? So which one of them is being used?

Thanks,
Shihuan

**Comment by skywalker0618** [comment]
I don't see an option that I can reopen this issue @mohanbaabu1996

**Comment by mohanbaabu1996** [comment]
Hi,

It's a job start time, the job end time must be equal to Pipeline_SnapTS that will allow us to do calculate the cost even the job is still running. For example, in this snippet job is started at Feb 1 and still running till Feb 5, we will get job snapshot time as job end time in that way we can calculate the cost. If the job again started at Feb 6 and still running, it will update the current snapshot time as end time and go on. 

I'll reopen for you.

**Comment by skywalker0618** [comment]
Wouldn't this cause data loss? For example, suppose we run an Overwatch job at 12:30am on Feb 6, and the processing time window is [Feb 1, Feb 5] (both inclusive). Suppose we have a job (say job A run 1) that started at 11pm on Feb 5, and finished on 1am on Feb 6. For this job, its start time falls within [Feb 1, Feb 5], so theoretically it should be included in the calculation. However, since it was not finished yet when the Overwatch job was running (at 12:30am on Feb 6), the Overwatch won't be able to process its cost.

Say on next day, say 12:30am on Feb 7, we run the Overwatch job again, whose processing time window is [Feb 6, Feb 6], it still won't be processing job A run 1 because its start time was outside of the current processing time window.

Would this cause "job A run 1" was never processed by the Overwatch job?

**Comment by mohanbaabu1996** [comment]
No, It won't lose data. Overwatch checks for closures on runs where end_time == pipelineSnap time. If no closures found in new dataset the end_time is updated to the new run's Pipeline_SnapTS. Thank you for bringing this to our attention; we will try to provide more relevant information in the next release.

**Comment by skywalker0618** [comment]
I see, so in my example, "job A run 1" has no closure on [Feb 1, Feb 5] window, so its run end_time will be set to Pipeline_SnapTS (12:30am on Feb 6)? However when this run really ended (at 1am on Feb 6), will you update its end_time to be the real end time on the [Feb 6, Feb 6] Overwatch run?

**Comment by mohanbaabu1996** [comment]
Yes, it will update the end_time when the overwatch job ran on Feb 6

**Comment by mohanbaabu1996** [comment]
I'm closing this ticket. Please feel free to reopen if you have any queries.
Thanks.
