### ISSUE TITLE
Inaccurate  costing

### ISSUE THREAD

**Issue by saikumar-gouddubbaka** [databrickslabs/overwatch#354]
The cost metric which is generated from overwatch is not accurate/near to that what we have in manage account. Can you please help

**Comment by mohanbaabu1996** [comment]
Hi Saikumar,

As we discussed in the call, kindly update the custom cost in the runner notebook and verify once the job gets complete.
private val interactiveDBUPrice = 
private val automatedDBUPrice = 
private val DatabricksSQLDBUPrice = 
private val automatedJobsLightDBUPrice =
