### ISSUE TITLE
Structured streaming fails for timeout on ClientConnection Pool

### ISSUE THREAD

**Issue by alexz00** [databrickslabs/overwatch#355]
Hi,
while running Overwatch on Azure I'm getting the following error:

> === Streaming Query ===
> Identifier: StreamTo_audit_log_raw_events [id = c1e276fb-753d-4d4e-88b9-fcd507f12c81, runId = a53c3ce4-6196-4c47-8763-8c1721003e03]
> Current Committed Offsets: {}
> Current Available Offsets: {}
> 
> Current State: INITIALIZING
> Thread State: RUNNABLE
> 	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:381)
> 	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:250)
> Caused by: java.util.concurrent.TimeoutException: Futures timed out after [5 minutes]
> 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
> 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
> 	at scala.concurrent.Await$.$anonfun$result$1(package.scala:223)
> 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
> 	at scala.concurrent.Await$.result(package.scala:146)
> 	at org.apache.spark.eventhubs.client.ClientConnectionPool.org$apache$spark$eventhubs$client$ClientConnectionPool$$borrowClient(ClientConnectionPool.scala:92)
> 	at org.apache.spark.eventhubs.client.ClientConnectionPool$.borrowClient(ClientConnectionPool.scala:170)
> 	at org.apache.spark.eventhubs.client.EventHubsClient.client(EventHubsClient.scala:62)
> 	at org.apache.spark.eventhubs.client.EventHubsClient.liftedTree1$1(EventHubsClient.scala:187)
> 	at org.apache.spark.eventhubs.client.EventHubsClient.partitionCountLazyVal$lzycompute(EventHubsClient.scala:184)
> 	at org.apache.spark.eventhubs.client.EventHubsClient.partitionCountLazyVal(EventHubsClient.scala:183)
> 	at org.apache.spark.eventhubs.client.EventHubsClient.partitionCount(EventHubsClient.scala:176)
> 	at org.apache.spark.sql.eventhubs.EventHubsSource.partitionCount(EventHubsSource.scala:81)
> 	at org.apache.spark.sql.eventhubs.EventHubsSource.<init>(EventHubsSource.scala:106)
> 	at org.apache.spark.sql.eventhubs.EventHubsSourceProvider.createSource(EventHubsSourceProvider.scala:84)
> 	at org.apache.spark.sql.execution.datasources.DataSource.createSource(DataSource.scala:322)
>      ...

We also see the following errors in the logs:

> 22/04/11 13:49:48 WARN MessagingFactory: messagingFactory[MF_a50464_1649684868691], hostName[myhub.servicebus.windows.net], message[Processing all pending tasks and closing old reactor.]
> 22/04/11 13:49:48 INFO ReactorHandler: name[MF_a50464_1649684868691] reactor.onReactorFinal
> 22/04/11 13:49:48 WARN ConnectionHandler: onTransportError hostname[myhub.servicebus.windows.net:5671], connectionId[MF_7b1d4b_1649684928711], error[org.apache.qpid.proton.engine.TransportException: connection aborted]
> 22/04/11 13:49:48 WARN MessagingFactory: onConnectionError messagingFactory[MF_7b1d4b_1649684928711], hostname[myhub.servicebus.windows.net], error[org.apache.qpid.proton.engine.TransportException: connection aborted]
> 22/04/11 13:49:48 WARN MessagingFactory: onConnectionError messagingFactory[MF_7b1d4b_1649684928711], hostname[myhub.servicebus.windows.net], open hasn't complete, stopping the reactor
> 22/04/11 13:49:48 INFO ConnectionHandler: onConnectionUnbound hostname[myhub.servicebus.windows.net:5671], connectionId[MF_7b1d4b_1649684928711], state[CLOSED], remoteState[UNINITIALIZED]
> 22/04/11 13:49:48 INFO ConnectionHandler: onConnectionFinal hostname[myhub.servicebus.windows.net:5671], connectionId[MF_7b1d4b_1649684928711], errorCondition[amqp:resource-limit-exceeded], errorDescription[local-idle-timeout expired]
> 22/04/11 13:49:48 INFO RetryUtils: (TID -1) retrying createFromConnectionString after 10 ms
> 22/04/11 13:49:48 WARN MessagingFactory: messagingFactory[MF_7b1d4b_1649684928711], hostName[myhub.servicebus.windows.net], message[stopping the reactor because thread was interrupted or the reactor has no more events to process.]

We are using: overwatch 0.6.0.4, azure-eventhubs-spark_2.12 2.3.21, Spark 3.1.2.

Any idea of what could be the root cause?

Thanks

**Comment by mohanbaabu1996** [comment]
Hi alexz00,

Please run and check with the validation notebook which I'll sent (please share your email-id).
If you have any problems, we'll have a call you and discuss it.
Please let us know what time zone you're in and when you're available.
I'm from India, and my time zone is IST.

Thanks,
Mohan Baabu

**Comment by alexz00** [comment]
Hi Mohan,
thanks a lot you can send the notebook to: alessandro.zucca00@gmail.com
I'm in Europe, CET timezone.

Alessandro

**Comment by mohanbaabu1996** [comment]
Thanks, i've sent you an email with the notebook

**Comment by mohanbaabu1996** [comment]
Hi,

As we discussed, are you able to build a new listener policy under Event Hub and verify with that readiness notebook ?

**Comment by alexz00** [comment]
Hi,
yes I've been able to create a new listener policy but I got the same error.
As soon as we find some time we'll further analyze this and provide an update.

Thanks

**Comment by alexz00** [comment]
Hi,
after discussion with Mohan we opened a ticket to Azure, since it seems a
connectivity issue of the azure-event-hubs-spark connector.

I will provide an update on this as soon as we progress.

Thanks a lot for your support. Regards,
Alessandro

Il giorno mer 11 mag 2022 alle ore 18:50 Daniel Tomes <
***@***.***> ha scritto:

**Comment by mohanbaabu1996** [comment]
Hi Alessandro,

Were you able to resolve the issue ?

**Comment by alexz00** [comment]
Hi, thanks for checking.
Not yet, we have an open ticket with Azure.

Best regards,
Alessandro

Il giorno ven 20 mag 2022 alle ore 08:31 mohanbaabu1996 <
***@***.***> ha scritto:

**Comment by mohanbaabu1996** [comment]
Thanks for the info.
After that have you tried running the notebook ?

Regards,
Mohan Baabu

**Comment by alexz00** [comment]
Hi, yes, same result.

Regards,
Alessandro

Il giorno ven 20 mag 2022 alle ore 13:05 mohanbaabu1996 <
***@***.***> ha scritto:

**Comment by mohanbaabu1996** [comment]
Hi,

Any response from Microsoft ticket or Pritesh(SA) from DB ?

**Comment by alexz00** [comment]
Hi,
we had a few calls with Microsoft, but they are still analyzing the issue.

Thanks for checking.
Best regards,
Alessandro


Il giorno lun 6 giu 2022 alle ore 06:33 mohanbaabu1996 <
***@***.***> ha scritto:

**Comment by mohanbaabu1996** [comment]
Hi @alexz00 ,

Hope you doing good!
Have you tried any further steps with this issue ?
We can follow up in the mail because we've account team in our mail thread.
Feel free to reply in mail, if you still have an issue.
Thanks!
