### ISSUE TITLE
Missing data in jobruncostpotentialfact_gold

### ISSUE THREAD

**Issue by skywalker0618** [databrickslabs/overwatch#356]
Hi Databricks Team!

It looks like we are missing some data in jobruncostpotentialfact_gold table for a specific job (job ID 91213012749241). 

If we look at the silver table (jobrun_silver) we can actually see the runs of this job on 4/12, 4/14 and 4/15. The SQL query we used:
```
USE overwatch;
select * from jobrun_silver where jobid=91213012749241 order by startEpochMS desc;
```
The result includes these 3 runs:
{"startEpochMS": 1650044387459, "startTS": "2022-04-15T17:39:47.000+0000", "endEpochMS": 1650292627501, "endTS": "2022-04-18T14:37:07.000+0000", "runTimeMS": 248240042, "runTimeS": 248240.042, "runTimeM": 4137.3340333333335, "runTimeH": 68.95556722222223}

{"startEpochMS": 1649966975757, "startTS": "2022-04-14T20:09:35.000+0000", "endEpochMS": 1650025199635, "endTS": "2022-04-15T12:19:59.000+0000", "runTimeMS": 58223878, "runTimeS": 58223.878, "runTimeM": 970.3979666666667, "runTimeH": 16.173299444444446}

{"startEpochMS": 1649790382039, "startTS": "2022-04-12T19:06:22.000+0000", "endEpochMS": 1649837641093, "endTS": "2022-04-13T08:14:01.000+0000", "runTimeMS": 47259054, "runTimeS": 47259.054, "runTimeM": 787.6509, "runTimeH": 13.127514999999999}

However, when we query the gold table (jobruncostpotentialfact_gold), we cannot see above runs. The latest run on the gold table was on 4/6. SQL query:
`select * from jobruncostpotentialfact_gold where job_id=91213012749241 order by startEpochMS desc;`

The latest result is:
{"startEpochMS": 1649280776133, "startTS": "2022-04-06T21:32:56.000+0000", "endEpochMS": 1649280825450, "endTS": "2022-04-06T21:33:45.000+0000", "runTimeMS": 49317, "runTimeS": 49.317, "runTimeM": 0.82195, "runTimeH": 0.013699166666666667}

Note that we have the Overwatch job being scheduled daily, and it has been running well. Wondering why do we miss data in the gold table?

Thanks,
Shihuan

**Comment by GeekSheikh** [comment]
Hi,

If you're on 0604, please note that there was a gap found. 0605 should be out next week and I am hopeful the issue is resolved. If not, we will dig in further.

**Comment by skywalker0618** [comment]
Yeah I am on 6.0.4. Will upgrade to 6.0.5. Would it retrospectively fix previous gaps or it's only affecting future calculations?

**Comment by skywalker0618** [comment]
Hi @GeekSheikh I don't see 6.0.5 version in Maven Central? The latest I can see is still 6.0.4. Thanks

**Comment by skywalker0618** [comment]
Ah gotcha you said it will be out next week. I will wait until then. Thanks!

**Comment by GeekSheikh** [comment]
Right, next week. And you'll just need to rebuild jrcp to get the corrected data retroactively.

**Comment by skywalker0618** [comment]
One additional question, would the bug which is fixed in the new version cause data loss from silver to gold job stages? Just trying to understand whether this indeed is the reason of the issue I reported.

**Comment by GeekSheikh** [comment]
Yes, I do believe it's the same issue. If it is not corrected in 0605, we will investigate and get a solution. 0605 code has already been frozen and all hands are on deck in testing that release atm. Please bear with us.

**Comment by skywalker0618** [comment]
No problem, thank you!

**Comment by mohanbaabu1996** [comment]
Hi @skywalker0618 ,

Have you preformed the [upgradation ](https://databrickslabs.github.io/overwatch/changelog/#0610-upgrade-release) into your workspace ? Any help required in the upgradation process ?

**Comment by mohanbaabu1996** [comment]
Hello, please keep us updated on your progress.

**Comment by mohanbaabu1996** [comment]
Hi @skywalker0618 ,

Please reopen this ticket, if you need any guidance on the upgradation part.
Thanks.
