### ISSUE TITLE
Externalize Configs for ApiCallV2 / ApiEnv controls

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#390]
ApiCallV2 should have the following items configurable externally

- parallelism - default 4 - hard max at 6
- batch size - default 50 requests - hard max at 200
- max module API failure count before fail module -- default 200 -- hard max 9999

These should be nested as `ApiConfigs` into `OverwatchParams` as optional overrides.

**Comment by GeekSheikh** [comment]
@Sriram-databricks -- is all of this complete? If so please link the PR and close this. Thanks.

**Comment by Sriram-databricks** [comment]
Its done below is the PR
Ov 38 use new api #381
