### ISSUE TITLE
[TESTS] - PipelineFunctions

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#396]
Build unit tests for all functions in PipelineFunctions.scala

**Comment by GeekSheikh** [comment]
@sundarshankar89 -- wasn't it you that said you were going to try to take a look at Sawan's PR and help close it? If not, sorry we can cover in stand-up just curious. If it is you, please provide update in next standup

**Comment by sundarshankar89** [comment]
yes on it
