### ISSUE TITLE
Unrecognized token 'compactString'

### ISSUE THREAD

**Issue by patrick-incite** [databrickslabs/overwatch#438]
First time running the Upgrade_0610 notebook.
Tried on Databricks Runtime 10.4 LTS and 11.0
Libraries installed: com.databricks.labs:overwatch_2.12:0.6.1.0

Getting error message on command 3:
JsonParseException: Unrecognized token 'compactString': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"compactString"; line: 1, column: 14]

**Comment by mohanbaabu1996** [comment]
Hi Patrick,

In order to [upgrade ](https://databrickslabs.github.io/overwatch/changelog/#0610-upgrade-release)from 0.6.X to 0.6.1.0, we must use 10.4 LTS. What version of Overwatch are you currently using?
If possible, could you please share the HTML copy of the upgrade_notebook to understand the issue.

Thanks,
Mohan Baabu

**Comment by patrick-incite** [comment]
Yes, this was attempted with 10.4
Please see the attached HTML notebook.

**Comment by mohanbaabu1996** [comment]
Thanks for the notebook.
It seems like you didn't give the json compact string in the upgrade_notebook.
Please copy the output of compact string from the [runner_notebook ](https://databrickslabs.github.io/overwatch/gettingstarted/#jump-start-notebooks)as mentioned by below command and paste it inside triple quotes,
"JsonUtils.objToJson(params).compactString"

![image](https://user-images.githubusercontent.com/87074323/177312456-d90a073f-ada8-46ab-b842-7ef92dca1913.png)

**Comment by mohanbaabu1996** [comment]
Hi Patrick,
Is it working fine after adding compact string ?

**Comment by mohanbaabu1996** [comment]
The upgrade has been finished, and the job has begun.

**Comment by patrick-incite** [comment]
The job ran but threw multiple exceptions; all looking like this:

java.util.concurrent.ExecutionException: io.delta.exceptions.ConcurrentDeleteDeleteException: This transaction attempted to delete one or more files that were deleted (for example organization_id=8998077817868329/part-00692-edf41bbd-b08b-4066-a423-52d72c441cd4.c000.snappy.parquet) by a concurrent update. Please try the operation again.
Conflicting commit: {"timestamp":1657106587050,"operation":"OPTIMIZE","operationParameters":{"predicate":[],"zOrderBy":[],"batchId":0,"auto":false},"readVersion":57,"isolationLevel":"SnapshotIsolation","isBlindAppend":false,"operationMetrics":{"numRemovedFiles":"986","numRemovedBytes":"4468136","p25FileSize":"1027332","minFileSize":"1027332","numAddedFiles":"1","maxFileSize":"1027332","p75FileSize":"1027332","p50FileSize":"1027332","numAddedBytes":"1027332"},"engineInfo":"Databricks-Runtime/10.4.x-photon-scala2.12","txnId":"85277a05-280b-4767-9647-091212392caa"}
Refer to https://docs.databricks.com/delta/concurrency-control.html for more details.

**Comment by mohanbaabu1996** [comment]
Did the job succeed?

**Comment by patrick-incite** [comment]
Yes, job succeeded.  Is the data still accurate despite all of the update conflict errors?

**Comment by mohanbaabu1996** [comment]
Let's check the results in pipeline_report table.
Can you please send it in mail.

**Comment by patrick-incite** [comment]
Ah, I missed that line.  That specific issue has come up before.  I did a working session with Daniel Tomes and he had come up with a fix in a prior version.

**Comment by mohanbaabu1996** [comment]
Thanks for sharing that

**Comment by mohanbaabu1996** [comment]
Hello, the new version will be release shortly that fixes this problem.
Please check the [docs ](https://databrickslabs.github.io/overwatch/changelog/)for version release.
If you need any assistance, send a mail to me.
Thanks!

**Comment by patrick-incite** [comment]
Thanks, I did that and get:

(No Token Secret Defined,java.lang.NullPointerException)
No secret parameters provided: attempting to continue with job owner's token.
The DB: overwatch exists at location dbfs:/mnt/mke-log/8998077817868329/overwatch.db which is different than the location entered in the config. Ensure the DBName is unique and the locations match. The location must be a fully qualified URI such as dbfs:/...
BadConfigException: The DB: overwatch exists at location dbfs:/mnt/mke-log/8998077817868329/overwatch.db which is different than the location entered in the config. Ensure the DBName is unique and the locations match. The location must be a fully qualified URI such as dbfs:/...
