### ISSUE TITLE
job tags - struct to map

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#445]
Databricks recently released a new "job tags" feature. This is currently making its way into job_gold as a struct instead of a map k:v. Convert this field from struct to map string:string just as all other user-defined structs.

Must be part of a minor release as it will require a schema change to all tables with this field in it -- they must be upgraded from tags struct to tags map string:string

**Comment by alinealvarez0107** [comment]
I'm facing this problem too. Any solution predictions or what action should we take?
![overwatch table job](https://user-images.githubusercontent.com/110247311/184130291-40a66de4-ecf1-4b70-8408-ae7684c8af80.png)

**Comment by GeekSheikh** [comment]
this will be rolled into the changes for MTJ support epic in #471 as a sub-item for #342
