### ISSUE TITLE
AWS Bucket need historical logs to run overwatch

### ISSUE THREAD

**Issue by mohanbaabu1996** [databrickslabs/overwatch#446]
"Exception: Audit Logs Module Failure: Audit logs are required to use Overwatch and no data was found in the following locations:"

Following error occurred due to no historical log in the bucket.  Overwatch required atleast one day historical load to run.
Above [information ](https://databricks.slack.com/archives/C012VT7C136/p1657517901446229?thread_ts=1657517043.124179&cid=C012VT7C136)need to be added in the documentation.

**Comment by GeekSheikh** [comment]
@mohanbaabu1996 -- Did you have an idea of where you wanted this included in the docs?

**Comment by mohanbaabu1996** [comment]
This is appropriate for both AWS and Azure, however we can add it under AWS Environment setup because we have addressed event hubs in Azure.

**Comment by GeekSheikh** [comment]
@mohanbaabu1996 can you verify that this is done?

**Comment by mohanbaabu1996** [comment]
@GeekSheikh We indicated on the AWS Setup page that audit and cluster logs should be checked before deploying overwatch. However, we did not specify that some historical data should be available in the audit bucket.

**Comment by kennes913** [comment]
I'm running into this issue as well and I'm wondering if 1 day means one s3 subpath partition or is it 1 day of audit logs (i.e. I start audit logs mid day yesterday and have to wait a full 24 hours?).

**Comment by mohanbaabu1996** [comment]
@kennes913 You need to have atleast one day audit logs to run overwatch. 
For example, S3 audit path looks like
s3a://*/*/workspaceId=************/date=2022-**-**/

**Comment by kennes913** [comment]
@mohanbaabu1996, I have several days worth of audit logs and this is still not working.

**Comment by mohanbaabu1996** [comment]
@kennes913 Anusha is helping you in  #564 , she will connect with you to resolve this.
Thanks!
