### ISSUE TITLE
Unable to get costs for AWS c6gd instances

### ISSUE THREAD

**Issue by sharathsamala** [databrickslabs/overwatch#455]
I started using the c6gd instances for our databricks workloads and overwatch is not capturing the cost information for the jobs launched using these instances. 

After debugging, i found that `overwatch.instancedetails` table is not having the AWS pricing information for these instances.

**Comment by Anusha-Sure** [comment]
Hi Sharath,

Based on your request, we have created another GitHub ticket to update the cost tables for static instance details and the changes will reflect in the new overwatch version release (0612).

As I am aware your overwatch version is 0611. To reflect the changes in the current version, you need to add the records with cost details manually.

Regards,
Anusha

**Comment by mohanbaabu1996** [comment]
Hi @sharathsamala ,

Thanks for your patience.
Please upgrade the overwatch to the latest [version](https://databrickslabs.github.io/overwatch/changelog/) (0710) and you can view the new instances types in the table.
Reference Ticket: [641](https://github.com/databrickslabs/overwatch/issues/641)
If you need doubt, please re-open this ticket.

Thanks,
Mohan Baabu
