### ISSUE TITLE
[REFACTOR] - Initializer.scala (P0)

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#460]
Initializer is getting more and more confusing. Reordering the functions and simplifying the overall structure is paramount to improve tests coverage and simplify future development.

**Comment by GeekSheikh** [comment]
Created branch
[460_refactor_initializer](https://github.com/databrickslabs/overwatch/tree/460_refactor_initializer)

**Comment by souravbaner-da** [comment]
Linked PR is Merged
