### ISSUE TITLE
[FEAT] - Add Warehouses To Data Model

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#462]
Let's get endpoints into the data model.

**Comment by aman-db** [comment]
@GeekSheikh - Can I get access to the existing data model? Are we using any tool like lucid chart to create/maintain the diagram ?

**Comment by GeekSheikh** [comment]
@aman-db -- I provided you access and sent you the details in slack. Let's hold off on adding this until it's actually added to gold but feel free to go ahead and add gold table for sqlQueryHistory

**Comment by ktopcuoglu** [comment]
hey @GeekSheikh,
We're using SQL Warehouse (classic) in our environment (aws), unique custom tags assigned to SQL Warehouses and I believe we're able to get our SQL Warehouse dbu costs from the current [clusterstatefact_gold](https://databrickslabs.github.io/overwatch/dataengineer/definitions/#gold) model. Would it be acceptable to rely on the results of the following query? thanks in advance!


```
select date_trunc('month',state_start_date) as date_month
      ,get_json_object(custom_tags,'$.DataBricksClusterName') as sql_warehouse_name
      ,round(sum(total_dbu_cost)) as total_dbu_cost
from clusterstatefact_gold
where state_start_date > '2023-01-01'

--sql endpoints only
and cluster_name ='SQLAnalytics' 

--all of our SQL endpoints have "DataBricksClusterName" custom tag.
and get_json_object(custom_tags,'$.DataBricksClusterName') in ('tagged_sql_endpoint_1','tagged_sql_endpoint_2') 

--costs dbu
and databricks_billable 
group by 1,2
order by 1 desc,2
```
