### ISSUE TITLE
Calculate costs for DBSQL

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#463]
Properly calculate costs for DBSQL SKUs in clusterStateFact

**Comment by souravbaner-da** [comment]
@GeekSheikh 
PR raised for this issue
https://github.com/databrickslabs/overwatch/pull/524

Please review

**Comment by GeekSheikh** [comment]
Cannot implement this until DB starts publishing warehouse events. Moving this back to backlog.

**Comment by neilbest-db** [comment]
@aman-db , is this meaningful/feasible?

Maybe it is this already implemented in any/all of these?:

- [x] #1261
- [ ] ~#1278~ 
- [ ] #1286
- [ ] #1217 
- [ ] #1218 
- [ ] #1254 
- [ ] #1252 
- [ ] #1265 

(please `[x]` check or `[ ]` ~strikethrough~ and add notes to indicate status)

IOW, is there anything to do here?

**Comment by aman-db** [comment]
This issue can be closed
