### ISSUE TITLE
Description of fields in gold Layer

### ISSUE THREAD

**Issue by SomanathSankaran** [databrickslabs/overwatch#466]
Hi Team,

We tried implementing overwatch in our project 
But I couldnt find any place where we could get description of fields in the gold layer.
Can someone point to the documentation

**Comment by mohanbaabu1996** [comment]
Hi @SomanathSankaran ,

These are the gold [tables](https://databrickslabs.github.io/overwatch/dataengineer/definitions/#gold) that will be created as part of the ETL database. You may utilize consumer database to develop dashboards and see field [descriptions](https://databrickslabs.github.io/overwatch/dataengineer/definitions/#column-descriptions) for all tables. The table fields under consumer database are similar to gold tables. Thanks!

**Comment by SomanathSankaran** [comment]
Hi @mohanbaabu1996 thanks it was helpful it will highly great if  you could point out the  table from which we can get  actual resource utilization similar to the one which we see in Ganglia UI

**Comment by mohanbaabu1996** [comment]
For cluster utilization - Cluster, clusterstatefact, sparktask tables
For Job's cluster utilization - Jobrun, Jobruncostpotential, sparktask
For Spark metrics - Sparktask, sparkjob, sparkstage
We team working on the advanced dashboard as you seen in ganglia which will release soon.
Meanwhile please share your mail id, i'll share the dashboard which is readily available

**Comment by SomanathSankaran** [comment]
somanathsankaran@gmail.com is my mail id . Also I would like to contribute for overwatch please let me know what could be the starting point for me to contribute

**Comment by mohanbaabu1996** [comment]
I've shared the dashboard to your mail. Start from [data_model](https://databrickslabs.github.io/overwatch/dataengineer/#overwatch-erd) flow and understand the each tables and joining between the tables

**Comment by SomanathSankaran** [comment]
Thanks a lot !! 
I am closing the ticket

**Comment by andrii-nimble-ai** [comment]
@mohanbaabu1996  can you please also send the dashboard which is readily available with me as well? my email is andrii@nimble.ai

**Comment by mohanbaabu1996** [comment]
@andrii-nimble-ai Sent!

**Comment by andrii-nimble-ai** [comment]
> 

thank you!
