### ISSUE TITLE
[UPGRADE] - Hugo Build Version

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#475]
Docs are currently built with an older version of HUGO. We need to investigate the LOE for compiling docs with later version of Hugo. If LOE is sufficiently low, we will migrate to compiling on latest version.

**Comment by GeekSheikh** [comment]
Hey @mohanbaabu1996 and @shravanshibu90 -- can you guys look at if there are any compatibility issues by using a newer version of hugo. We're on v76 and they're on 104. I'd like to 1st make sure that there aren't any major breaking changes if we were to upgrade to a later (latest) version. If not, what would be the major changes / benefits of upgrading? If there are breaking changes what is level of effort (LOE) to correcting them?

**Comment by mohanbaabu1996** [comment]
sure @GeekSheikh will check and update you in weekly meeting
