### ISSUE TITLE
[WORKFLOWS] - Investigate jobs-observability metrics endpoint

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#482]
API endpoint is available below in ungated private preview. Goal is to analyze the output and determine if the endpoint offers information that we either cannot otherwise get and/or if it simplifies some of the work being done.

```
$ curl -XGET \
-H 'Authorization: Bearer xxxxxxx’ \
-H  'Accept: application/openmetrics-text' \
'https://<databricks-host>/api/2.0/jobs-observability/metrics'
```

Use 2.1 API if available -- if not check with jobs team to see when / if it will be available in 2.1 API

May feed micro pipelines -- #425

**Comment by GeekSheikh** [comment]
What is available and what is LOE / Value to implement

**Comment by souravbaner-da** [comment]
IAM is an important topic on the GCP Associate Cloud Engineer Exam. You should know what role to assign for what tasks. Most of the problems are caused solely by wrong permissions. So, this lesson is crucial for you to learn how to control IAM easily.

As you read in the last lesson, IAM controls **who can do what on which resource.** So, let’s break this sentence down into IAM components.

- Who: Members
- Can do what: Permissions and Roles
- On which resource: Services

Let’s look at each component in detail.
