### ISSUE TITLE
Can overwatch track overwatch's costing details

### ISSUE THREAD

**Issue by PallerlaAkshay** [databrickslabs/overwatch#486]

**Comment by mohanbaabu1996** [comment]
Hi @PallerlaAkshay ,

Are you talking about sku cost like interactive DBU & Automated DBU's ?
Overwatch is nothing more than a daily job run, and it will keep track of his own job run costs.

**Comment by PallerlaAkshay** [comment]
Thanks. That was my original impression as well. However when I query the
job run table with the job run Id, I can't see any of the overwatch job run
details.

Just the way we have readiness review notebooks, do we have any deployment
review notebooks or something similar that validates if everything is
deployed correctly?

**Comment by mohanbaabu1996** [comment]
In the deployment notebook itself, we've to add the sku cost for interactive and automated cost
private val interactiveDBUPrice = 
private val automatedDBUPrice = 

So after your jobrun, you will find the cost details for particular job from [jobruncostpotentialfact](https://databrickslabs.github.io/overwatch/dataengineer/definitions/#jobruncostpotentialfact) table.

To validate our deployment, please check the pipeline_report table from ETL database for the "status" column

**Comment by PallerlaAkshay** [comment]
Thanks. I don't see any "row" or " record" itself for any runs
corresponding to overwatch job run. If the SKU price units are not
indicated, at the most the columns should be NULL right. In this case, I
don't see records at all

**Comment by mohanbaabu1996** [comment]
not able to see any of the job run details in job run table ?

**Comment by mohanbaabu1996** [comment]
Hi @PallerlaAkshay ,
I hope you having a discussion with Neha, regarding this issue and sharing the corresponding reports.
Please feel free to open the ticket, if you've any issues.
Thank you!
