### ISSUE TITLE
Consumption Layer Sample Queries and Notebooks

### ISSUE THREAD

**Issue by PallerlaAkshay** [databrickslabs/overwatch#487]
Can you share sample consumption layer notebooks and queries for consumption dashboards in SQL endpoint

**Comment by mohanbaabu1996** [comment]
Hi @PallerlaAkshay ,

@Neha-vs123 will send those notebooks to you via email because you two are already in contact.
Please feel free to submit your questions here or send them to her through email.
Thanks!

**Comment by anir** [comment]
@mohanbaabu1996 @PallerlaAkshay @Neha-vs123 Can one you send me these notebooks too? Much appreciated

**Comment by mohanbaabu1996** [comment]
Hi @anir,

Hope you doing good!
The SQL dashboard was not built on the latest version 07x, whereas we do have a python dashboard that gives more valuable information. Those dashboard will be on live from monday in this github repo.

Thanks,
Mohan Baabu
