### ISSUE TITLE
Organization_ID field wrongly Mapped

### ISSUE THREAD

**Issue by SomanathSankaran** [databrickslabs/overwatch#497]
Hi Team,

We have a scheduling workspace and we run the overwatch for a different worspace.
So I have configured the workspaceid hardcoded

val workspaceID = "124555555722765551" (changed )

I could see the data being fetched correctly but I could see the organization id populated as the workspace from where we run instead of workspace for which it is ran.
Please advise.

Does this have any issue on internal metrics calculation.

display(
  pipReport(etlDB)
)
returned 0 records because the workspace id is not matching with org id

**Comment by Anusha-Sure** [comment]
Hi Somanath,

Can we get into a call to resolve this issue ?

Regards,
Anusha

**Comment by Anusha-Sure** [comment]
Hi Somanath,

If possible please share the html file of the runner notebook so that we may fix the issue over here.

Here is my mail_id - anusha.sure@databricks.com

Regards,
Anusha

**Comment by SomanathSankaran** [comment]
hi @Anusha-Sure 

I have used this script

https://databrickslabs.github.io/overwatch/assets/GettingStarted/azure_runner_docs_example_060.html
 
changes made 

val workspaceID = if (dbutils.notebook.getContext.tags("orgId") == "0") {
  dbutils.notebook.getContext.tags("browserHostName").split("\\.")(0)
} else dbutils.notebook.getContext.tags("orgId")
 
def pipReport(etlDB: String): DataFrame = {
  spark.table(s"${etlDB}.pipReport")
    .filter('organization_id === workspaceID)
    .orderBy('Pipeline_SnapTS.desc)
}

val workspaceID = "hardcoded id"

def pipReport(etlDB: String): DataFrame = {
  println(s"${etlDB}.pipReport")
  spark.table(s"${etlDB}.pipReport")
    .filter('organization_id === workspaceID)
    .orderBy('Pipeline_SnapTS.desc)
}

I cant share the notebook unfortunately we can connect tomorrow afternoon.
Mail ID : somanathsankaran@gmail.com

**Comment by Anusha-Sure** [comment]
Hi Somanath,

Please share an invite based on your availability.

Regards,
Anusha

**Comment by SomanathSankaran** [comment]
Sure will schedule a call at monday morning is it fine 10 am  monday

**Comment by Anusha-Sure** [comment]
Can we meet at 11 am Monday ?

**Comment by SomanathSankaran** [comment]
hi @AnushaSure sure

**Comment by Anusha-Sure** [comment]
Hi Somanath,

Can we meet now ?

Regards,
Anusha

**Comment by SomanathSankaran** [comment]
Hi Anusha,

Sorry for the delayed response .
I have mailed you .
Please mail me any time today I am avaialble upto 6pm IST

**Comment by Anusha-Sure** [comment]
Can we have a call now ?

**Comment by Anusha-Sure** [comment]
As discussed over call, you have deployed one workspace (workspace_1) with all the resources under another workspace (workspace_2). So, the overwatch data has picked the org_id of that particular workspace (workspace_2).

Please update org_id column with the ID of deployed workspace (workspace_1).
