### ISSUE TITLE
[Unity Catalog] Overwatch is failing with unity catalog

### ISSUE THREAD

**Issue by thetkoseek** [databrickslabs/overwatch#500]
When using unity catalog, the schema cannot be defined a location. Because of this - it fails in the following area:
src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala

`
if (spark.catalog.databaseExists(dbName)) {
      val dbMeta = spark.sessionState.catalog.getDatabaseMetadata(dbName)
      val dbProperties = dbMeta.properties
      val existingDBLocation = dbMeta.locationUri.toString
      if (existingDBLocation != dbLocation) {
        switch = false
        throw new BadConfigException(s"The DB: $dbName exists " +
          s"at location $existingDBLocation which is different than the location entered in the config. Ensure " +
          s"the DBName is unique and the locations match. The location must be a fully qualified URI such as " +
          s"dbfs:/...")
      }
`

Would it be possible to bypass this check through a configuration parameter?

Note:
The whole pipeline from bronze,silver to gold works if the schema or database does not exist, as it does not do the check above. However when I run it again, it will do the location check and fail there as it expects the database to have a location defined.

**Comment by GeekSheikh** [comment]
Hi @thetkoseek I believe you need follow the [external metastore](https://databrickslabs.github.io/overwatch/gettingstarted/advancedtopics/#using-external-metastores) rules when using UC. I have pinged two other colleagues that have gotten this to work on UC as well. They may be able to add additional context.

Note UC isn't fully supported yet but it does work with a few rules. We're working on getting these rules explicitly published in the docs.

You can follow #476 to see when full support is enabled.

**Comment by GeekSheikh** [comment]
@thetkoseek -- The following appear to be the full list of requirements for Overwatch on UC. We will be getting docs out in the coming weeks and adding full support by end of year (sooner if possible) -- but in the meantime I wanted you and others with this issue to have an easy reference.

**UC REQUIREMENTS**
* DBR 11.1+
* Use full path (not mount point) as storage prefix
* Ensure the OW cluster has direct read/write access to the storage prefix
  * This should be set via `sc.hadoopConfiguration.set` and `spark.conf.set` in cluster config
* Ensure the UC has the appropriate permissions granted to all consumers

**Comment by thetkoseek** [comment]
Hi @GeekSheikh thanks for getting back to me. I actually got it working with UC. It was mainly the initialisation stage after the database has been created that fails when it does the check for existing dblocation. For UC the db location is always blank. I believe you are not able to set a db location for UC databases. 

The first time I run it, it will create the database and skip the check and will actually run through all the stages correctly.

**Comment by GeekSheikh** [comment]
This is why you need to follow the [External Metastore](https://databrickslabs.github.io/overwatch/gettingstarted/advancedtopics/#using-external-metastores) rules.

Glad you got it figured out. Please reopen this ticket if you have any further questions.

**Comment by thetkoseek** [comment]
Hi @GeekSheikh - unfortunately I am still not able to get it to work following the [External Metastore](https://databrickslabs.github.io/overwatch/gettingstarted/advancedtopics/#using-external-metastores) rules. It somehow still does the database location validation check which fails with UC as the we cannot specify a location for a UC database.

I have done a PR which should skip this check if the database is tagged accordingly as a UC database. This also means that we can create the database before hand and don't need to rely on Overwatch to create this database for us.
[Pull request](https://github.com/databrickslabs/overwatch/pull/511)

**Comment by GeekSheikh** [comment]
@thetkoseek -- make sure you're following this bullet.
```
Ensure the OW cluster has direct read/write access to the storage prefix
This should be set via sc.hadoopConfiguration.set and spark.conf.set in cluster config
```
