### ISSUE TITLE
JobRun table not getting populated with all the required job details

### ISSUE THREAD

**Issue by narenderreddy548** [databrickslabs/overwatch#518]
Hi Team,

We have configured Overwatch and scheduled the job from over 2 weeks. As a part of data validation, we observed that Jobrun and Jobruncostpotentialfact tables not getting populated with all the required job details. 

Attaching the screenshot.
[Overwatch_JobRun_Data_Issue.docx](https://github.com/databrickslabs/overwatch/files/9618537/Overwatch_JobRun_Data_Issue.docx)

We have followed https://databrickslabs.github.io/overwatch/ to implement the Overwatch configuration.

Thanks,
Narender.

**Comment by mohanbaabu1996** [comment]
Hello Narender,

Have you seen that all of the job data is presented in the job table?
Please execute the following command to see the entire job list,

%sql
select * from overwatch.job;

**Comment by narenderreddy548** [comment]
Hi Mohan,

Yes, Job table is populated with the job data. Attaching the results for reference.

Thanks,
Narender.
[Overwatch_Job_Table_Data.docx](https://github.com/databrickslabs/overwatch/files/9627043/Overwatch_Job_Table_Data.docx)

**Comment by mohanbaabu1996** [comment]
Hi Narender,

Thank you for your confirmation.
There is no need to be worried because all of the job data has been successfully captured in the bronze layer.
This is a known issue that will be addressed in the next [version](https://github.com/databrickslabs/overwatch/milestone/12), which is set to be released by the end of this month.

**Comment by narenderreddy548** [comment]
Hi Mohan,

Thank you for the update on the issue.

We will wait for the next version and test the issue once the new version is released. Can we keep this ticket open until the issue is resolved?

Thanks,
Narender.

**Comment by mohanbaabu1996** [comment]
Sure Narender,
Thanks for understanding and your patience

**Comment by Evogelpohl** [comment]
Same issue. Tried both 0.6.10 and .11. I'm collecting all events successfully in audit_log_bronze as I can query where requestParams like 'job_id' - however, many are not showing up in the jobrun table, or the fact$ table. @mohanbaabu1996  - is there a work around? Is everyone experiencing this? Seems like a total 'outage' to me... ??

**Comment by mohanbaabu1996** [comment]
@Evogelpohl We are also facing the same issue internally; work is underway, and it will be resolved in the upcoming release.

**Comment by narenderreddy548** [comment]
@mohanbaabu1996 Can you please confirm if the version 0.7.0.0 is released and if yes, can you please provide the documentation to upgrade to latest version.

**Comment by mohanbaabu1996** [comment]
@narenderreddy548 Thanks for your patience! Please follow up this [docs ](https://databrickslabs.github.io/overwatch/changelog/#0700-major-release)for upgradation. Kindly let me know your upgradation status and we can close the ticket. Thanks!

**Comment by narenderreddy548** [comment]
@mohanbaabu1996 Thank you for the support. We have upgraded the version to 0.7.0 and now the data is populated in JobRun table.

Please close the ticket.

**Comment by mohanbaabu1996** [comment]
Thanks @narenderreddy548 for your update.
