### ISSUE TITLE
operation is not permitted on a non-empty directory

### ISSUE THREAD

**Issue by julioliv88** [databrickslabs/overwatch#536]
Hey team,

I hope you are doing well!

I'm facing the following problem: I need a clean or new temp directory every time because the bronze layer is failing, flagging a message that a delete action is forbidden, but that's the last step of the bronze pipeline.

Here is the error message that I get:
AzureException: hadoop_azure_shaded.com.microsoft.azure.storage.StorageException: This operation is not permitted on a non-empty directory. Caused by: StorageException: This operation is not permitted on a non-empty directory.

It seems to me that this is a bug in the logic of the overwatch code. Is it so?

Kind regards,
Julio Oliveira

**Comment by AnushaSure** [comment]
Hi @julioliv88,

How many workspaces do you have ?
Can you please confirm have you run any workspace cleanup script ?

Regards,
Anusha

**Comment by AnushaSure** [comment]
Hi @julioliv88,

Are you still facing the issue ? If yes, please share the details for the previous comments.

Regards,
Anusha

**Comment by AnushaSure** [comment]
Hi @julioliv88,

I will be closing this ticket for now. Please open the ticket if the issue still exists.
We will glad to assist you.

Regards,
Anusha
