### ISSUE TITLE
Get users function

### ISSUE THREAD

**Issue by karoljaron** [databrickslabs/overwatch#540]
Hi, I work for a Partner company and I have a usecase regarding Overwatch which I struggle with. I need to explore usage of a certain schema in Databricks. The metric here is how many unique queries are being run against that database within a day/week/month. But not in total, but only by users (no admins, no scheduled jobs). Is there a way to get which user is admin and which user is a service principal from Overwatch? Or all jobs ids within a workspace? By job I mean Databricks Job. 

At this point I'm joining SparkJob table with SparExecution table and it seems to have almost all information I need but I don't know how to filter only users. I can go to admin console and get all admins as well as go to Workflows tab and get all Job IDs and filter them out but I hope that there is some easier, more generic way when using Overwatch.

Thanks!

**Comment by AnushaSure** [comment]
Hi @karoljaron,

Sorry for the delayed response.
Please find attached **verbose_audit_logging** notebook to get the unique query metrics by user level and admin details can be tracked in account tables in overwatch databases.

Please make sure your using the latest version of overwatch and verbose audit logging is already enable in your workspace.

Regards,
Anusha
[verbose_audit_logging (1).zip](https://github.com/databrickslabs/overwatch/files/10307300/verbose_audit_logging.1.zip)

**Comment by AnushaSure** [comment]
Hi @karoljaron ,

Closing this ticket for now. Please re-open the ticket if you have any questions.

Regards,
Anusha
