### ISSUE TITLE
[FEAT] - Readiness Script - Update for APIV2

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#549]
Single Workspace Readiness Script -- let's expand that to validate OW readiness even for non-multi-workspace deployments.

* [ ] check if pools

**Comment by gueniai** [comment]
@aman-db I reviewed the notebook, and it looks good. I made some minor cosmetic changes to the params. Other than that, let's clear out the outputs, remove any commented out code, and it should be good to go!
