### ISSUE TITLE
Audit Logs Module Failure: Audit logs are required to use Overwatch and no data was found in the following locations 

### ISSUE THREAD

**Issue by kennes913** [databrickslabs/overwatch#564]
I am trying to get the **aws_runner_docs_example_070** notebook working correctly. I have configured audit logging correctly and see logs flowing to my audit logs bucket and I have also configured cluster-logs correctly which I see flowing as well. After running several notebook cells, below are my overwatch pretty printed JSON parameters:

```json
{
  "auditLogConfig" : {
    "rawAuditPath" : "s3://{redacted}-logdelivery/audit-logs/workspaceId={redacted}/", 
    "auditLogFormat" : "json"
  },
  "tokenSecret" : {
    "scope" : "{redacted}",
    "key" : "{redacted}"
  },
  "dataTarget" : {
    "databaseName" : "overwatch_etl",
    "databaseLocation" : "/overwatch_monitoring/{redacted}/overwatch_etl.db",
    "etlDataPathPrefix" : "/overwatch_monitoring/global_share",
    "consumerDatabaseName" : "overwatch",
    "consumerDatabaseLocation" : "/overwatch_monitoring/{redacted}/overwatch.db"
  },
  "badRecordsPath" : "overwatch_monitoring/{redacted}/sparkEventsBadrecords",
  "overwatchScope" : [ "audit", "sparkEvents", "jobs", "clusters", "clusterEvents", "notebooks", "pools", "accounts", "dbsql" ],
  "maxDaysToLoad" : 10,
  "databricksContractPrices" : {
    "interactiveDBUCostUSD" : 0.56,
    "automatedDBUCostUSD" : 0.26,
    "sqlComputeDBUCostUSD" : 0.22,
    "jobsLightDBUCostUSD" : 0.1
  },
  "primordialDateString" : "2021-10-12",
  "intelligentScaling" : {
    "enabled" : false,
    "minimumCores" : 4,
    "maximumCores" : 512,
    "coeff" : 1.0
  },
  "workspace_name" : "{redacted}",
  "externalizeOptimize" : false
}
```
For good measure, I've also tried mounting the s3 bucket to the DBFS so I've changed `rawAuditPath` to `"dbfs:/mnt/{redacted}-logdelivery/audit-logs/workspaceId={redacted}/"`.

Neither have worked.  

I have also verified that my shared-ec2-instance-profile can access all the things required and the mounted s3 bucket is `ls`-able via `%` commands.

**Comment by AnushaSure** [comment]
Hi @kennes913, 

Please refer to #446.

Regards,
Anusha

**Comment by kennes913** [comment]
I've resolved my issue and it was something embarrassingly silly that I missed. I set the incorrect primordial date year portion (2021 vs. 2022) with a window of 30 days such that it was looking for audit logs during a period of time where there were none. Thanks for taking time to respond to this, @AnushaSure.
