### ISSUE TITLE
[FEAT] Make the parallel API calls more generalize. 

### ISSUE THREAD

**Issue by aman-db** [databrickslabs/overwatch#567]
Currently in order to make the parallel API calls for any module, we have to write the redundant code with very less changes. These parallel API calls can be generalized into a function/utils and can be used across the framework. 

* [ ] clusterEvents
* [ ] sqlQueryHistory
* [ ] runs failure out `jobs/runs/get-output` (coming soon)

**Comment by GeekSheikh** [comment]
Adding jobs/runs/get-output api endpoint which is parallelized with key (similar to clusterEvents) -- this must be done before we can integrate this.
