### ISSUE TITLE
Ref #534 - Description column in sparkexecution table is truncated

### ISSUE THREAD

**Issue by alinealvarez0107** [databrickslabs/overwatch#571]
Hi, good evening!

I'm facing a problem with description column in sparkexecution table because it is truncated and I need to see the entire value.

Is there any way to get this information?

We already have this feature enable and upgrade it to 7.0 version and the issue persists.

#534

**Comment by GeekSheikh** [comment]
Hello,

This description field is truncated intentionally by the spark engine to ensure the JVM doesn't OOM. There's really no way around this (certainly not safely) as this field can get extremely long. What are you trying to do? Perhaps there's another way to do it.

**Comment by alinealvarez0107** [comment]
Hi @GeekSheikh,

We need to have visibility of all the commands executed in the clusters to establish a control and audit of these executions.

**Comment by GeekSheikh** [comment]
Right, Overwatch doesn't offer full auditability and in fact, what you're looking for may not completely exist. We (Databricks) have many ways to deliver what you're looking for but there is often a longer story and more discussion needed. 

If you're looking to audit notebooks and their commands, please look at [verbose audit logging](https://docs.databricks.com/administration-guide/account-settings/audit-logs.html#enable-or-disable-verbose-audit-logs) and enable that. Overwatch will provide all the queries / commands / code executed in notebooks this way. Overwatch also exposes all queries executed via DBSQL in the sqlQueryHistory table. If you're needing 100% coverage of all commands executed across all parts of the platform, please reach out to your sales team and they will have those discussion on requirements with you.

Thanks hope this helps.

**Comment by alinealvarez0107** [comment]
OK. Thank you.
