### ISSUE TITLE
Collecting Utilization percent for sql endpoint

### ISSUE THREAD

**Issue by SomanathSankaran** [databrickslabs/overwatch#573]
Hi all,
Is it possible to add cluster logs for sql endpoints as we see cluster logs is used for calculating the potential resource usage

**Comment by GeekSheikh** [comment]
hi, with the latest version 07001 -- you can get usage via the new sqlQueryHistory table. Databricks doesn't yet publish warehouse state change events (i.e. on/off/scale) so we cannot get potential which means we cannot derive utilization. That said, you can sum up the metrics provided in the aforementioned table to get usage by hour of day, day of week, warehouse, etc...but if the warehouse is dynamically scaling or auto-terminating it's not possible to get utilization at this time. It will not be until Databricks starts making this data available.

**Comment by SomanathSankaran** [comment]
hi @GeekSheikh 
Below log is observed do we need to enable anything on sql endpoint or it is auto-populated

EMPTY: 3017-Gold_Sql_QueryHistory Module: No new data found. This does not appear to be an error but simply a lack of data present for the module. Progressing module state. Module Dependencies: 2020 ALERT: No New Data Retrieved for Module 3017-Gold_Sql_QueryHistory! Skipping com.databricks.labs.overwatch.utils.NoNewDataException: ALERT: No New Data Retrieved for Module 3017-Gold_Sql_QueryHistory! Skipping at com.databricks.labs.overwatch.pipeline.Module.validateSourceDF(Module.scala:302) at c...

**Comment by SomanathSankaran** [comment]
sqlQueryHistory - this tbl is not created in my metastore

**Comment by Neha-vs123** [comment]
Hi @SomanathSankaran ,

Do you have enough workloads or actions in DBSQL?

**Comment by SomanathSankaran** [comment]
yes we have a lot of sql endpoints @Neha-vs123 will check once again now

**Comment by SomanathSankaran** [comment]
@Neha-vs123  it is still the same we dont see the table eventhough we have power bi usecases running through the sql endpoint

**Comment by SomanathSankaran** [comment]
@Neha-vs123  @GeekSheikh  sorry for the confusion it seems like the Sql endpoint workloads have been migrated all together to a brand new workspace will add it over there and will let you know will raise a new issue or re-open this as I couldnt test the scenario
