### ISSUE TITLE
Issue in sinking multiple Workspace to same Overwatch DB

### ISSUE THREAD

**Issue by SomanathSankaran** [databrickslabs/overwatch#576]
Below code is used to select the targed DB
So when we try to run it in 2 diff workspace the workspace id is varying which results in spark complaining  the DB name and underlying Path not match as the workpspace name is varying

/*code 
private val dataTarget = DataTarget(

  Some(etlDB), Some(s"${storagePrefix}/${workspaceID}/${etlDB}.db"), Some(s"${storagePrefix}/global_share"),
  Some(consumerDB), Some(s"${storagePrefix}/${workspaceID}/${consumerDB}.db")
)
 
*/
So do we need to create multiple DBs  for multiple workspaces or I am planning to hardcode the workspace id in datatarget alone

**Comment by mohanbaabu1996** [comment]
Hi @SomanathSankaran ,

Overwatch code itself fetch the current workspace ID and created folder under dataTarget section.
Also it will automatically create overwatch databases.

/*code
private val dataTarget = DataTarget(

Some(etlDB), Some(s"${storagePrefix}/${workspaceID}/${etlDB}.db"), Some(s"${storagePrefix}/global_share"),
Some(consumerDB), Some(s"${storagePrefix}/${workspaceID}/${consumerDB}.db")
)

*/

what error are you getting now ?

**Comment by SomanathSankaran** [comment]
@mohanbaabu1996 error stack

BadConfigException: The DB: overwatch_etl_temp exists at location dbfs:/mnt/overwatch-meta-data/6743691722764551/overwatch_etl_temp.db which is different than the location entered in the config. Ensure the DBName is unique and the locations match. The location must be a fully qualified URI such as

**Comment by mohanbaabu1996** [comment]
@SomanathSankaran No need to create separate databases, if you're using same storage path.
Are you available now for 15-20 mins discussion ?

**Comment by SomanathSankaran** [comment]
hi @mohanbaabu1996 we can connect 3:30 IST  if available

**Comment by mohanbaabu1996** [comment]
Sure, i sent you invite

**Comment by SomanathSankaran** [comment]
hi @mohanbaabu1996 thanks for the call

for the benefit of others it is present in advanced section

https://databrickslabs.github.io/overwatch/gettingstarted/advancedtopics/

// DEFAULT
private val dataTarget = DataTarget(
  Some(etlDB), Some(s"${storagePrefix}/${workspaceID}/${etlDB}.db"), Some(s"${storagePrefix}/global_share"),
  Some(consumerDB), Some(s"${storagePrefix}/${workspaceID}/${consumerDB}.db")
)

// EXTERNAL METASTORE
private val dataTarget = DataTarget(
  Some(etlDB), Some(s"${storagePrefix}/${etlDB}.db"), Some(s"${storagePrefix}/global_share"),
  Some(consumerDB), Some(s"${storagePrefix}/${consumerDB}.db")
)
