### ISSUE TITLE
Missing Jobrun tables with new version of Overwatch 0.7.0.0

### ISSUE THREAD

**Issue by narenderreddy548** [databrickslabs/overwatch#583]
Hi,

Recently, we have deployed Overwatch 0.7.0.0 in PROD and observed that the below tables are not getting created:

**Missing Tables:**
**ETL:**
Account_mods_gold
Account_mods_silver
Accountmod
Jobrun_gold
Jobrun_silver
Jobruncostpotentialfact_gold

**CONSUMER:**
Jobrun
Jobruncostpotentialfact
Sparkstream_preview

Can you please check and fix the same. Please let us know if any details required.

Thanks,
Narender.

**Comment by GeekSheikh** [comment]
if this is a brand new deployment, you're likely not to have account mods until some account is actually modified. Remember we don't get historical data -- only new data from when you turn on OW.

Regarding jobs tables, please make sure the configured API token has access to the jobs -- if it's not an admin account the owner of the API Token will need to be provisioned read access to all the jobs.

Regarding sparkstream -- are you running streams on clusters that have logging enabled?

**Comment by narenderreddy548** [comment]
Hi @AnushaSure 

We are using Azure cloud. Please let me know if you need any additional details.

Thanks,
Narender.

**Comment by AnushaSure** [comment]
Hi @narenderreddy548 

Please share pipReport. If possible we can have a call to analyze the issue.

Regards,
Anusha

**Comment by narenderreddy548** [comment]
Hi @AnushaSure 

Please find the attached pipReport. 

Thanks,
Narender.
[PipReport.csv](https://github.com/databrickslabs/overwatch/files/9881592/PipReport.csv)

**Comment by narenderreddy548** [comment]
Hi @AnushaSure,

Can you please let us know a good time to connect for analyzing the issue.

Thanks,
Narender.

**Comment by AnushaSure** [comment]
Hi @narenderreddy548 ,

Any time 10am to 8pm IST works for me. Please share an invite.

Regards,
Anusha

**Comment by AnushaSure** [comment]
Hi @narenderreddy548 ,

Analyzed the pipreport, module Silver_JobsRuns is failing over here. This issue is resolved in the latest version.

Please swap the jar with 07002 and re-run the pipelines. Hope this resolves.

Regards,
Anusha

**Comment by GeekSheikh** [comment]
My guess is that you are hitting #598 -- please follow the instructions in that ticket and let us know if you have any questions / issues.

**Comment by AnushaSure** [comment]
Thanks @narenderreddy548 for the update.

Regards,
Anusha
