### ISSUE TITLE
Auditabiliy And Observability in Overwatch

### ISSUE THREAD

**Issue by SomanathSankaran** [databrickslabs/overwatch#594]
@GeekSheikh @mohanbaabu1996 
Curious and silly question
We have the entire history of Databricks activity in  hive_metastore.overwatch_etl_temp.audit_log_bronze
Why Observability was not highlighted in Overwatch session
Is there any specific reason for the same :)

**Comment by mohanbaabu1996** [comment]
Hi @SomanathSankaran , 
I'll check and update you

**Comment by GeekSheikh** [comment]
Apologies, I don't quite understand the question or the need @SomanathSankaran -- please elaborate if you haven't already done so with @mohanbaabu1996

**Comment by SomanathSankaran** [comment]
@GeekSheikh we have a lot of potential usecases like 
Workspace/Cluster/Repos/DBFS Editing
Login Auditing
Data Lineage (consumers querying a table)
Secrets access etc.

in the bronze audit table.
But in Spark Summit 22 Seminar most of the usecases are around Cost and cluster optimization
But It will be great if we can have some dashboard around this as well

As log Analytics workspace despite providing the data doesnt make it easy for querying as overwatch provides
