### ISSUE TITLE
[EPIC] - Enable support for GCP

### ISSUE THREAD

**Issue by alexott** [databrickslabs/overwatch#61]
As we get closer to the GCP release, we'll need to consider adding the support for GCP (first step would be just to throw an error during initialization, saying that GCP is not supported)

**Comment by alexott** [comment]
Audit log delivery for GCP is [available now](https://docs.gcp.databricks.com/administration-guide/account-settings-gcp/log-delivery.html)

**Comment by a0x8o** [comment]
We are seeing demand for Overwatch on GCP. @alexott @GeekSheikh can we scope out the effort required?
