### ISSUE TITLE
Silver_SQLQueryHistory module loads 10000 queries or no query at all

### ISSUE THREAD

**Issue by Gumula** [databrickslabs/overwatch#625]
Hi,
I'm setting up Overwatch with dbsql and all modules are working correctly, except Silver_SQLQueryHistory (or maybe I'm doing something wrong). I'm using version 0.7.0.0.3. 
Scenario:

- date of running overwatch is 2022-11-17
- we have SQL queries running more or less all the time on databricks sql
- I'm using a token with admin rights and sql access enabled
- running overwatch with primordial date **2022-11-07** (or earlier) and max 18 days gives me 10000 rows (with the most recent query being from today)
- running overwatch with primordial date **2022-11-08** (or later) and max 18 days gives me no data

I tried using the same token that Overwatch uses and run a query against databricks api, with roughly the same values of params (max_results, include_metrics, filter_by.query_start_time_range.start_time_ms, filter_by.query_start_time_range.end_time_ms) and I'm always getting some data. 
Maybe I'm misunderstanding how this module should work? I don't have verbose audit logging set up, but my understanding is that Silver_SQLQueryHistory module loads the data using api.

**Comment by Sriram-databricks** [comment]
Hi Gumula, Can we have an Salesforce Ticket to investigate further?

**Comment by Gumula** [comment]
Hi, what is a salesforce ticket? Do you mean a ticket on help.databricks.com?

**Comment by GeekSheikh** [comment]
Hi @Gumula -- yes, that's what @Sriram-databricks meant but please note that we have identified this issue and the fix is coming out this week as part of 07004 release. @aman-db has resolved the issue as part of #537. @aman-db, please link this ticket to your PR as well for tracking. Thanks.
