### ISSUE TITLE
Overwatch ETL pipeline error

### ISSUE THREAD

**Issue by agnitc** [databrickslabs/overwatch#627]
Getting issue while running Bronze function used version com.databricks.labs:overwatch_2.12:0.7.0.0.3. 

AnalysisException: Column 'operationVersion' does not exist. Did you mean one of the following? [operationName, ReleaseVersion, durationMs, properties, RoleLocation, correlationId, organization_id, category, identity, resourceId, tenantId, time, callerIpAddress, level, resultSignature, resultType, jobId, jobType];
'Project [ReleaseVersion#4147, RoleLocation#4148, callerIpAddress#4149, category#4150, correlationId#4151, durationMs#4152, identity#4153, jobId#4154, jobType#4155, level#4156, operationName#4157, properties#4158, resourceId#4159, resultSignature#4160, resultType#4161, tenantId#4162, time#4163, organization_id#3950, 'operationVersion AS version#4182]
+- Project [streamRecord#4144.ReleaseVersion AS ReleaseVersion#4147, streamRecord#4144.RoleLocation AS RoleLocation#4148, streamRecord#4144.callerIpAddress AS callerIpAddress#4149, streamRecord#4144.category AS category#4150, streamRecord#4144.correlationId AS correlationId#4151, streamRecord#4144.durationMs AS durationMs#4152, streamRecord#4144.identity AS identity#4153, streamRecord#4144.jobId AS jobId#4154, streamRecord#4144.jobType AS jobType#4155, streamRecord#4144.level AS level#4156, streamRecord#4144.operationName AS operationName#4157, streamRecord#4144.properties AS properties#4158, streamRecord#4144.resourceId AS resourceId#4159, streamRecord#4144.resultSignature AS resultSignature#4160, streamRecord#4144.resultType AS resultType#4161, streamRecord#4144.tenantId AS tenantId#4162, streamRecord#4144.time AS time#4163, organization_id#3950]
   +- Project [streamRecord#4144, organization_id#3950]
      +- Generate explode(parsedBody#4126.records), false, [streamRecord#4144]
         +- Project [body#3940, partition#3941, offset#3942, sequenceNumber#3943L, enqueuedTime#3944, publisher#3945, partitionKey#3946, properties#3947, systemProperties#3948, deserializedBody#3949, organization_id#3950, Overwatch_RunID#3951, Pipeline_SnapTS#3952, workspace_name#3953, from_json(StructField(records,ArrayType(StructType(StructField(ReleaseVersion,StringType,true),StructField(RoleLocation,StringType,true),StructField(callerIpAddress,StringType,true),StructField(category,StringType,true),StructField(correlationId,StringType,true),StructField(durationMs,StringType,true),StructField(identity,StructType(StructField(authorization,StructType(StructField(action,StringType,true),StructField(evidence,StructType(StructField(principalId,StringType,true),StructField(principalType,StringType,true),StructField(role,StringType,true),StructField(roleAssignmentId,StringType,true),StructField(roleAssignmentScope,StringType,true),StructField(roleDefinitionId,StringType,true)),true),StructField(scope,StringType,true)),true),StructField(claims,StructType(StructField(aio,StringType,true),StructField(appid,StringType,true),StructField(appidacr,StringType,true),StructField(aud,StringType,true),StructField(exp,StringType,true),StructField(groups,StringType,true),StructField(http://schemas.microsoft.com/2012/01/devicecontext/claims/identifier,StringType,true),StructField(http://schemas.microsoft.com/claims/authnclassreference,StringType,true),StructField(http://schemas.microsoft.com/claims/authnmethodsreferences,StringType,true),StructField(http://schemas.microsoft.com/identity/claims/identityprovider,StringType,true),StructField(http://schemas.microsoft.com/identity/claims/objectidentifier,StringType,true),StructField(http://schemas.microsoft.com/identity/claims/scope,StringType,true),StructField(http://schemas.microsoft.com/identity/claims/tenantid,StringType,true),StructField(http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname,StringType,true),StructField(http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name,StringType,true),StructField(http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier,StringType,true),StructField(http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname,StringType,true),StructField(http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn,StringType,true),StructField(iat,StringType,true),StructField(idtyp,StringType,true),StructField(ipaddr,StringType,true),StructField(iss,StringType,true),StructField(name,StringType,true),StructField(nbf,StringType,true),StructField(onprem_sid,StringType,true),StructField(puid,StringType,true),StructField(rh,StringType,true),StructField(uti,StringType,true),StructField(ver,StringType,true),StructField(wids,StringType,true),StructField(xms_tcdt,StringType,true)),true)),true),StructField(jobId,StringType,true),StructField(jobType,StringType,true),StructField(level,StringType,true),StructField(operationName,StringType,true),StructField(properties,StructType(StructField(entity,StringType,true),StructField(eventCategory,StringType,true),StructField(eventProperties,StructType(StructField(cause,StringType,true),StructField(currentHealthStatus,StringType,true),StructField(details,StringType,true),StructField(previousHealthStatus,StringType,true),StructField(title,StringType,true),StructField(type,StringType,true)),true),StructField(hierarchy,StringType,true),StructField(legacyChannels,StringType,true),StructField(legacyEventDataId,StringType,true),StructField(legacyEventProperties,StringType,true),StructField(legacyResourceGroup,StringType,true),StructField(legacyResourceId,StringType,true),StructField(legacyResourceProviderName,StringType,true),StructField(legacyResourceType,StringType,true),StructField(legacySubStatus,StringType,true),StructField(legacySubscriptionId,StringType,true),StructField(message,StringType,true),StructField(requestbody,StringType,true),StructField(responseBody,StringType,true),StructField(serviceRequestId,StringType,true),StructField(statusCode,StringType,true),StructField(statusMessage,StringType,true)),true),StructField(resourceId,StringType,true),StructField(resultSignature,StringType,true),StructField(resultType,StringType,true),StructField(tenantId,StringType,true),StructField(time,StringType,true)),true),true), deserializedBody#3949, Some(Etc/UTC)) AS parsedBody#4126]
            +- Filter ((Overwatch_RunID#3951 = 3bec8c61e3834d21b2d2c1fc7be26a6e) AND (organization_id#3950 = 7734382224886880))
               +- Filter (organization_id#3950 = 7734382224886880)
                  +- Relation [body#3940,partition#3941,offset#3942,sequenceNumber#3943L,enqueuedTime#3944,publisher#3945,partitionKey#3946,properties#3947,systemProperties#3948,deserializedBody#3949,organization_id#3950,Overwatch_RunID#3951,Pipeline_SnapTS#3952,workspace_name#3953] parquet

**Comment by AnushaSure** [comment]
Hi @agnitc ,

Which cloud are you using ( AWS/Azure ) ?
Please share the html file of the runner notebook and pipreport for analysis.

Regards,
Anusha

**Comment by AnushaSure** [comment]
Hi @agnitc, 

Is this your first run and first deployment ?

Regards,
Anusha

**Comment by agnitc** [comment]
Hi @AnushaSure ,
Thanks for the response. I think the issue was due to the fact I was not using the premium workspace and thus all the diagnostic settings were not being captured.
