### ISSUE TITLE
DBU values calculation missing by ~ 30%

### ISSUE THREAD

**Issue by souravbaner-da** [databrickslabs/overwatch#636]
Currently different customer are facing some dbu value mismatch between databricks provided metrics and overwatch metric. 

- This is due to the fact that for for different cluster type the dbu/hr has been recently updated for some cluster types and in overwatch resource that dbu/hr are yet to be updated.
- The temporary solution for this issue is customer need to update instanceDetail table with the latest dbu/hr value.
- You can get latest value of dbu/hr from compute page as shown below.

**Comment by souravbaner-da** [comment]
<img width="1643" alt="Screenshot 2022-11-29 at 12 12 59 PM" src="https://user-images.githubusercontent.com/109206082/204458378-b25e74c5-8986-4d62-9959-1660e3cfbd49.png">

**Comment by souravbaner-da** [comment]
This issue is related to the issue as below:
[597](https://github.com/databrickslabs/overwatch/issues/597)

**Comment by GeekSheikh** [comment]
Complete with #615 and #657
