### ISSUE TITLE
Missing Cluster Event Logs

### ISSUE THREAD

**Issue by cmcharg-dufrain** [databrickslabs/overwatch#637]
Hi, I am facing an issue whereby cluster event logs which I can see via the UI are not appearing in the clusterstatefact table. Only certain cluster events seem to be pulled in by overwatch.

See below for examples:

These are the events in the UI:
![image](https://user-images.githubusercontent.com/116885848/204612591-74e4817e-597a-47d1-888d-66ff7e142e32.png)

And the corresponding clusterstatefact table in overwatch having just run a job:
![image](https://user-images.githubusercontent.com/116885848/204613015-cdf812b6-0e16-494e-9534-73132199f3ae.png)

I have also attached the cluster_state_detail_silver and cluster_events_bronze tables as csv's.

Could you assist in debugging this issue?

Thanks,
Conor
[cluster_events_bronze.csv](https://github.com/databrickslabs/overwatch/files/10115957/cluster_events_bronze.csv)
[cluster_state_detail_silver.csv](https://github.com/databrickslabs/overwatch/files/10115958/cluster_state_detail_silver.csv)

**Comment by Neha-vs123** [comment]
Hi @cmcharg-dufrain ,

What version of Overwatch are you using?

**Comment by cmcharg-dufrain** [comment]
Hi,

I was using 0.7.0.0.1 however have now moved to 0.7.0.0.3 and seems to have partially resolved the issue. However I am now getting the following in my cluster_state_fact table:
![image](https://user-images.githubusercontent.com/116885848/205045205-93b92f57-5cd3-444d-b3f5-c94441d4557d.png)

As you can see all the entries for running clusters have very short time in state

**Comment by Neha-vs123** [comment]
Hi @cmcharg-dufrain ,

This is an existing issue in 7003. This is being fixed and will be resolved in the next version release, which is likely to release early next week. Refer to this [link](https://databrickslabs.github.io/overwatch/changelog/) for the release update. 

Regards,
Neha

**Comment by cmcharg-dufrain** [comment]
Ok thanks,  in the meantime does the issue also exist in 7002?

**Comment by Neha-vs123** [comment]
Yes, it was found for the first time in 7002.

**Comment by cmcharg-dufrain** [comment]
Is there a suggested workaround while we wait for new release?

**Comment by GeekSheikh** [comment]
Apologies for the issue there @cmcharg-dufrain -- please note that 07004 was just pushed to Maven, should show up there in the next 24 hours. The data repair script was published to [07004 changelog](https://databrickslabs.github.io/overwatch/changelog/#07004-patch). @Neha-vs123 can help you execute it if you need any assistance.

**Comment by Neha-vs123** [comment]
Hi @cmcharg-dufrain , Were you able to do the data repair and upgrade to 7004? Please let me know if you need any help.

**Comment by cmcharg-dufrain** [comment]
Hi @Neha-vs123, yes managed to repair and upgrade. Looks to be working ok now. Thanks

**Comment by Neha-vs123** [comment]
@cmcharg-dufrain , Thanks for the update. Closing the ticket for now. Feel free to reopen in case you face any issues. 

Regards,
Neha
