### ISSUE TITLE
Organization ID mismatch in  overwatch_etl_temp.clusterStateFact_gold for Multi Workspace Jobs

### ISSUE THREAD

**Issue by SomanathSankaran** [databrickslabs/overwatch#639]
Hi Team ,

We re-utilize the same overwatch database for multiple workspace but  we do see mismatch in organization id and workspace id in 
overwatch_etl_temp.clusterStateFact_gold

**Comment by SomanathSankaran** [comment]
@Neha-vs123 we see both org id and workspace name getting populated from a diff workspace

**Comment by SomanathSankaran** [comment]
can we run multiple independent jobs at the same time

**Comment by Neha-vs123** [comment]
@SomanathSankaran , 

Yes it gets populated when you share the same etl prefix path for all those workspaces. 
You can run multiple jobs at the same time. 

Regards,
Neha

**Comment by SomanathSankaran** [comment]
@Neha-vs123  but we are not sure why there is a mix between the org ID as one of our clusters only run in 1 workspace.
But we see 2 rows one with dev and 1 with prod(supposed to have all rows with dev org id)

**Comment by Neha-vs123** [comment]
@SomanathSankaran , Are you saying that a cluster existing in one workspace also appears to be in another workspace according to overwatch reports ? 

Please send the query and a snippet of the output where you got this result. Let us have a call tomorrow morning/afternoon IST time to analyze further.  Mail id - neha.vs@databricks.com
Please schedule a meeting for any time after 10:30 am IST.

Regards,
Neha

**Comment by SomanathSankaran** [comment]
yes exactly @Neha-vs123 cant share code it is in client Workpace 
Please schedule a call to  somanathsankaran@gmail.com

**Comment by Neha-vs123** [comment]
@SomanathSankaran, I scheduled a meeting for 3 pm IST tomorrow.

**Comment by GeekSheikh** [comment]
Please confirm that you are not sending diagnostic logs from two different workspaces to the same event hub. They can share a namespace but should be on separate event hubs.

**Comment by SomanathSankaran** [comment]
@GeekSheikh 
I had a call with neha and we use same name space but different event hubs

@Neha-vs123 
Query Used and sample Opt:
%sql
select cluster_id,cluster_name,collect_set(case when organization_id like '123%' then "dev" else "prod" end),collect_set(to_date(`timestamp_state_start`)) from overwatch_temp.clusterstatefact where cluster_id='0402-09441-5p25a1yv' group by cluster_id,cluster_name having size(collect_set(organization_id))>1

|cluster_id         |cluster_name     |Org_id        |collect_set(to_date(timestamp_state_start))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|-------------------|-----------------|--------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|0402-09441-5p25a1yv|CL_SALESFORCE_NRT|["dev","prod"]|["2022-11-29","2022-10-31","2022-10-10","2022-11-30","2022-11-22","2022-11-01","2022-10-11","2022-11-23","2022-11-02","2022-10-25","2022-11-24","2022-11-03","2022-10-26","2022-11-25","2022-10-27","2022-11-26","2022-11-18","2022-10-28","2022-11-19","2022-10-29","2022-10-21","2022-11-20","2022-10-22","2022-11-21","2022-11-13","2022-10-23","2022-11-14","2022-10-24","2022-10-16","2022-11-15","2022-10-17","2022-11-16","2022-11-08","2022-10-18","2022-11-17","2022-11-09","2022-10-19","2022-12-01","2022-11-10","2022-10-20","2022-10-12","2022-11-11","2022-10-13","2022-11-12","2022-11-04","2022-10-14","2022-11-05","2022-10-15","2022-11-27","2022-11-06","2022-11-28","2022-11-07","2022-10-30"]|

**Comment by SomanathSankaran** [comment]
@Neha-vs123 we see multiple rows 1 row with dev org and one with prod org
So we are currently fixing it by filter for org id

**Comment by Neha-vs123** [comment]
@SomanathSankaran, Could you please raise a support ticket in Salesforce using this [link](https://help.databricks.com/s/) ?
This is required so that we can access your workspace and further investigate the problem. 

Regards,
Neha

**Comment by SomanathSankaran** [comment]
@Neha-vs123 I need to check with client reg sharing of the details will update based on discussion with client

**Comment by SomanathSankaran** [comment]
@Neha-vs123 I am facing some issues in updating the same

**Comment by Neha-vs123** [comment]
@SomanathSankaran , Please ignore the link I shared above. It won't work for azure workspace.
Please create a support ticket in the Azure portal and share the ticket number with us.

**Comment by SomanathSankaran** [comment]
@Neha-vs123  I have informed the client

**Comment by mohanbaabu1996** [comment]
@SomanathSankaran Please let us know the update on status of ticket creation. Thanks!
