### ISSUE TITLE
Not all schemas generating on new workspace

### ISSUE THREAD

**Issue by patrick-incite** [databrickslabs/overwatch#643]
I had been using Overwatch a few months and recently I noticed that after v0.6, it stopped updating the Jobs tables.
So, I wiped out the workspace with the "single workspace cleanup" notebook and started over.
Running v0.7.0.0.3 for a new workspace, tossed several errors such as:
 Cannot create view: overwatch_etl.sparkJob_gold --> Table or view not found: overwatch_etl.sparkJob_gold
Cannot create view: overwatch_etl.job_gold --> Table or view not found: overwatch_etl.job_gold
and several more like it.
Only a small number of tables were created in the fresh database.
I ran the runner again, and it threw fewer errors and created a couple more tables and that seems to be the trend.
It throws less errors and creates a couple more tables each run, but I'm not nearly close enough to a complete database and need that data. 
Happy to wipe clean and start over, but it seems like there should be an easier way than just crossing my fingers and hoping a new workspace doesn't throw errors.

**Comment by GeekSheikh** [comment]
Hi @patrick-incite -- please create a new notebook and export it as HTML after running the following

```scala
display(table("overwatch_etl.pipReport"))
```
Thank you

**Comment by patrick-incite** [comment]
[pip_report.zip](https://github.com/databrickslabs/overwatch/files/10142101/pip_report.zip)

**Comment by AnushaSure** [comment]
Hi @patrick-incite ,

Please confirm the below details.

1.Which cloud are you using ( Azure / AWS ) ?
2.In the pipreport, the primordial date is '2021-08-21'. Are you trying to retrieve the data for the past 1 year ?
3.Are you using single node cluster ?

Regards,
Anusha

**Comment by patrick-incite** [comment]
@AnushaSure 
3. Same issues exist when running on a single node

**Comment by AnushaSure** [comment]
Hi @patrick-incite ,

You can retrieve data >1 year but clusterEventsBronze will only go back 30 days. And if the maxDays is set to 60 and trying to run bronze, silver and gold - some modules depended on clusterEvents may not present.

It's important to load bronze repeatedly until it retrieve the data till present before running silver and gold.

If possible we can schedule a call and discuss further.

Regards,
Anusha

**Comment by patrick-incite** [comment]
@AnushaSure That information doesn't address the issue.  Let's schedule a call.

**Comment by AnushaSure** [comment]
Sure. I am from IST time zone. Please share an invite for tomorrow or any day based on your availability.
Mail_id - anusha.sure@databricks.com

Regards,
Anusha

**Comment by AnushaSure** [comment]
PFA

**Comment by AnushaSure** [comment]
Hi @patrick-incite ,

Please update me the status on bronze run.

Regards,
Anusha

**Comment by patrick-incite** [comment]
@AnushaSure 
Success!  Thank you very much for all of your help

**Comment by AnushaSure** [comment]
Hi @patrick-incite ,

Cleanup the existing data and re-deploy with masDays as >300 resolved the issue.
Closing this ticket. Please raise a ticket if you have any other questions / issues.

Regards,
Anusha
