### ISSUE TITLE
Data Dictionary for all overwatch tables

### ISSUE THREAD

**Issue by YatharthKaushik** [databrickslabs/overwatch#652]
Is it possible to get any data dictionary or data linkage documents to understand all the columns in the tables being generated?

**Comment by mohanbaabu1996** [comment]
Hi @YatharthKaushik Yes, please look into our overwatch [docs](https://databrickslabs.github.io/overwatch/dataengineer/definitions/#column-descriptions) for 07x version
For other versions, here is the [link](https://databrickslabs.github.io/overwatch/dataengineer/)

![image](https://user-images.githubusercontent.com/87074323/206416410-bb571161-f67f-44b6-90a5-3d668ad52293.png)

**Comment by YatharthKaushik** [comment]
It definitely helps. Thanks a lot!
