### ISSUE TITLE
Incorrect or Changing Cluster Names for Job Clusters

### ISSUE THREAD

**Issue by priyankabiswas-db** [databrickslabs/overwatch#663]
For some of the events we're getting the actual cluster name AFTER creation and other times we are getting the job_cluster name configured in the task. Sometimes it's getting the job-##-run-## prefix and other times it is not

**Comment by mohanbaabu1996** [comment]
Hi @priyankabiswas-db ,

Are you getting those issues from overwatch jobrun table ?
Please let me know which overwatch version are you using ?

**Comment by priyankabiswas-db** [comment]
Yes issue is present in overwatch_gold_db.jobRun table. Sometimes it's getting the job-##-run-## prefix and other times it is not. 
Overwatch version 7.004

**Comment by mohanbaabu1996** [comment]
Thanks, can you send me the jobrun report and specific job_id and run_id's

**Comment by mohanbaabu1996** [comment]
@priyankabiswas-db Please let me know the updates ?

**Comment by mohanbaabu1996** [comment]
Hi @priyankabiswas-db ,

Please upgrade it to latest version (0710) by running the repair [script](https://databrickslabs.github.io/overwatch/changelog/#07005-patch) with the help of 0710 library installed.
Re-run the overwatch pipeline with 0710 and validate the tables.

**Comment by mohanbaabu1996** [comment]
Hi @priyankabiswas-db ,

I hope this helps you to resolve this issue and also i've pinged you internally.
Please ping me if you need any help.
Thanks!
