### ISSUE TITLE
Missing data in jobruncostpotentialfact when the data is in the jobrun and clusterstatefact

### ISSUE THREAD

**Issue by anogues-danone** [databrickslabs/overwatch#670]
**Overwatch Version**
0.6.1.0

**Describe the bug**
Missing data in jobruncostpotentialfact when the data is in the jobrun and clusterstatefact. Also, some cluster executions are wrongly calculated

Upon checking overwatch (we are running 0.6.1.0) I see some strange behaviour.
Yesterday we had some job executions in a workspace and these appear in the jobrun table, but not in the jobruncostpotentialfact, so we don’t have costs attached to them:

The status of the job is ok, finished successfully and took about 20 min. The job appears here:
![image](https://user-images.githubusercontent.com/64522653/209139090-a5913dfe-6294-4717-84a2-020702cdce1b.png)

We have 11 in total in that table

But in the jobcostrunpotentialfacttable there are only two rows, from old days and only two entries instead of 11:

![image](https://user-images.githubusercontent.com/64522653/209139161-75ca477e-3261-47ad-806a-f3a2376f9fc5.png)

Upon checking the log it seems it processes 5 rows for the last day in the jobrun table but doesn’t produce any result in the jonruncostpotentialfact:

Also, I checked the github repo and somebody complains of exactly the same but there is no workable answer:

[Gold_jobRunCostPotentialFact not loading records · Issue #628 · databrickslabs/overwatch (github.com)](https://github.com/databrickslabs/overwatch/issues/628)
[jobruncostpotentialfact not getting updated correctly · Issue #617 · databrickslabs/overwatch (github.com)](https://github.com/databrickslabs/overwatch/issues/617)
[Missing data in jobruncostpotentialfact_gold · Issue #356 · databrickslabs/overwatch (github.com)](https://github.com/databrickslabs/overwatch/issues/356)

So it seems we all have the same problem. Can you forward this to some of your people? I checked the release log and it says in version 0.7.0.0 job clusters were added, but I am not sure its regarding to costs,a s as you can see these two entries are also job clusters and we have them, the problem is that we have missing ones. And seeing in github it seems its not only me seeing this problem.

Current Pipeline State: BEFORE this run.
+--------+----------------------------+--------------------+-------------+-------------+-------------------+
|moduleID|moduleName                  |primordialDateString|fromTS       |untilTS      |snapTS             |
+--------+----------------------------+--------------------+-------------+-------------+-------------------+
|1001    |Bronze_Jobs_Snapshot        |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|1002    |Bronze_Clusters_Snapshot    |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|1004    |Bronze_AuditLogs            |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|1005    |Bronze_ClusterEventLogs     |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|1006    |Bronze_SparkEventLogs       |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2003    |Silver_SPARK_Executors      |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2005    |Silver_SPARK_Executions     |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2006    |Silver_SPARK_Jobs           |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2007    |Silver_SPARK_Stages         |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2008    |Silver_SPARK_Tasks          |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2010    |Silver_JobsStatus           |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2011    |Silver_JobsRuns             |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2014    |Silver_ClusterSpec          |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2016    |Silver_AccountLogins        |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2017    |Silver_ModifiedAccounts     |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2018    |Silver_Notebooks            |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|2019    |Silver_ClusterStateDetail   |2022-01-01          |1671633199129|1671692708834|2022-12-22 07:11:43|
|3001    |Gold_Cluster                |2022-01-01          |1671550368193|1671633199129|2022-12-22 07:11:43|
|3002    |Gold_Job                    |2022-01-01          |1671550368193|1671633199129|2022-12-22 07:11:43|
|3003    |Gold_JobRun                 |2022-01-01          |1671550368193|1671633199129|2022-12-22 07:11:43|
|3004    |Gold_Notebook               |2022-01-01          |1671550368193|1671633199129|2022-12-22 07:11:43|
|3005    |Gold_ClusterStateFact       |2022-01-01          |1671550368193|1671633199129|2022-12-22 07:11:43|
|3007    |Gold_AccountMod             |2022-01-01          |1671550368193|1671633199129|2022-12-22 07:11:43|
|3008    |Gold_AccountLogin           |2022-01-01          |1671550368193|1671633199129|2022-12-22 07:11:43|
|3010    |Gold_SparkJob               |2022-01-01          |1670943925862|1671633199129|2022-12-22 07:11:43|
|3011    |Gold_SparkStage             |2022-01-01          |1670943925862|1671633199129|2022-12-22 07:11:43|
|3012    |Gold_SparkTask              |2022-01-01          |1670943925862|1671633199129|2022-12-22 07:11:43|
|3013    |Gold_SparkExecution         |2022-01-01          |1670943925862|1671633199129|2022-12-22 07:11:43|
|3014    |Gold_SparkExecutor          |2022-01-01          |1670943925862|1671633199129|2022-12-22 07:11:43|
|3015    |Gold_jobRunCostPotentialFact|2022-01-01          |1671550368193|1671633199129|2022-12-22 07:11:43|
|3016    |Gold_SparkStream            |2022-01-01          |1670943925862|1671633199129|2022-12-22 07:11:43|
+--------+----------------------------+--------------------+-------------+-------------+-------------------+

Overriding spark.databricks.delta.optimize.maxFileSize from 33554432 --> 134217728
FILTERING: Gold_Notebook using cron columns: timestamp
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
APPLIED FILTERS:
MODULE_ID: 3004
MODULE_NAME: Gold_Notebook
FILTERS:
(('timestamp >= 1671633199129) AND ('timestamp < 1671692708834))('organization_id = 7447636167761103)
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.

APPLIED FILTERS:
MODULE_ID: 3003
MODULE_NAME: Gold_JobRun
FILTERS:
(('startEpochMS >= cast(1669041199129 as bigint)) AND ('startEpochMS < 1671692708834))('organization_id = 7447636167761103)
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.

Beginning: 3003-Gold_JobRun
TIME RANGE: 2022-12-21 14:33:19 -> 2022-12-22 07:05:08

Beginning: 3003-Gold_JobRun
TIME RANGE: 2022-12-21 14:33:19 -> 2022-12-22 07:05:08
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
Gold_JobRun: Validating Input Schemas
DEBUG: Source DF Partitions: 5
DEBUG: Target Shuffle Partitions: 100
DEBUG: Max PartitionBytes (MB): 64.0
SUCCESS! Gold_JobRun
OUTPUT ROWS: 11
RUNTIME MINS: 0.21
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
GOLD VIEW: CREATE: Statement --> create or replace view overwatch.job as select 
organization_id, workspace_name, job_id, action, unixTimeMS, timestamp, date, job_name, job_type, timeout_seconds, schedule,
notebook_path, new_settings, cluster, aclPermissionSet, grants, targetUserId, session_id, request_id, user_agent,
response, source_ip_address, created_by, created_ts, deleted_by, deleted_ts, last_edited_by, last_edited_ts
from overwatch_etl.job_gold where organization_id = job_gold.organization_id and __overwatch_ctrl_noise = job_gold.__overwatch_ctrl_noise 

GOLD VIEW: CREATE: Statement --> create or replace view overwatch.jobRun as select 
organization_id, workspace_name, run_id, run_name, job_runtime, job_id, id_in_job, job_cluster_type, job_task_type,
job_terminal_state, job_trigger_type, cluster_id, notebook_params, libraries, children, workflow_context,
task_detail, request_detail, time_detail
from overwatch_etl.jobRun_gold where organization_id = jobRun_gold.organization_id and __overwatch_ctrl_noise = jobRun_gold.__overwatch_ctrl_noise 

FILTERING: Gold_ClusterStateFact using cron columns: unixTimeMS_state_start, state_start_date
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
APPLIED FILTERS:
MODULE_ID: 3005
MODULE_NAME: Gold_ClusterStateFact
FILTERS:
(('unixTimeMS_state_start >= 1671633199129) AND ('unixTimeMS_state_start < 1671692708834))(('state_start_date >= date_sub(cast(cast(from_unixtime((cast(1671633199129 as double) / 1000), yyyy-MM-dd HH:mm:ss, None) as timestamp) as date), 0)) AND ('state_start_date < cast(date_add(cast(from_unixtime((cast(1671692708834 as double) / 1000), yyyy-MM-dd HH:mm:ss, None) as timestamp), 1) as date)))('organization_id = 7447636167761103)
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.

Beginning: 3005-Gold_ClusterStateFact
TIME RANGE: 2022-12-21 14:33:19 -> 2022-12-22 07:05:08

Beginning: 3005-Gold_ClusterStateFact
TIME RANGE: 2022-12-21 14:33:19 -> 2022-12-22 07:05:08
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
Gold_ClusterStateFact: Validating Input Schemas
StructField(organization_id,StringType,true)
StructField(sku,StringType,false)
StructField(organization_id,StringType,true)
StructField(sku,StringType,true)
StructField(organization_id,StringType,true)
StructField(sku,StringType,false)
StructField(organization_id,StringType,true)
StructField(sku,StringType,true)
DEBUG: Source DF Partitions: 1
DEBUG: Target Shuffle Partitions: 100
DEBUG: Max PartitionBytes (MB): 64.0
SUCCESS! Gold_ClusterStateFact
OUTPUT ROWS: 5
RUNTIME MINS: 0.28
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
GOLD VIEW: CREATE: Statement --> create or replace view overwatch.clusterStateFact as select 
organization_id, workspace_name, cluster_id, cluster_name, custom_tags, state_start_date, unixTimeMS_state_start, unixTimeMS_state_end,
timestamp_state_start, timestamp_state_end, state, driver_node_type_id, node_type_id, current_num_workers,
target_num_workers, uptime_since_restart_S, uptime_in_state_S, uptime_in_state_H, cloud_billable,
databricks_billable, isAutomated, dbu_rate, state_dates, days_in_state, worker_potential_core_H, core_hours,
driver_compute_cost, worker_compute_cost, driver_dbu_cost, worker_dbu_cost, total_compute_cost, total_DBU_cost,
total_driver_cost, total_worker_cost, total_cost, driverSpecs, workerSpecs
from overwatch_etl.clusterStateFact_gold where organization_id = clusterStateFact_gold.organization_id and state_start_date = clusterStateFact_gold.state_start_date and __overwatch_ctrl_noise = clusterStateFact_gold.__overwatch_ctrl_noise 

FILTERING: Gold_jobRunCostPotentialFact using cron columns: startEpochMS
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
APPLIED FILTERS:
MODULE_ID: 3015
MODULE_NAME: Gold_jobRunCostPotentialFact
FILTERS:
(('startEpochMS >= cast(1669041199129 as bigint)) AND ('startEpochMS < 1671692708834))('organization_id = 7447636167761103)
FILTERING: Gold_jobRunCostPotentialFact using cron columns: startEpochMS
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
APPLIED FILTERS:
MODULE_ID: 3015
MODULE_NAME: Gold_jobRunCostPotentialFact
FILTERS:
(('startEpochMS >= cast(1669041199129 as bigint)) AND ('startEpochMS < 1671692708834))('organization_id = 7447636167761103)
FILTERING: Gold_jobRunCostPotentialFact using cron columns: unixTimeMS_state_start, state_start_date
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
APPLIED FILTERS:
MODULE_ID: 3015
MODULE_NAME: Gold_jobRunCostPotentialFact
FILTERS:
(('unixTimeMS_state_start >= cast(1663857199129 as bigint)) AND ('unixTimeMS_state_start < 1671692708834))(('state_start_date >= date_sub(cast(cast(from_unixtime((cast(1671633199129 as double) / 1000), yyyy-MM-dd HH:mm:ss, None) as timestamp) as date), 90)) AND ('state_start_date < cast(date_add(cast(from_unixtime((cast(1671692708834 as double) / 1000), yyyy-MM-dd HH:mm:ss, None) as timestamp), 1) as date)))('organization_id = 7447636167761103)
FILTERING: Gold_jobRunCostPotentialFact using cron columns: unixTimeMS, date
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
APPLIED FILTERS:
MODULE_ID: 3015
MODULE_NAME: Gold_jobRunCostPotentialFact
FILTERS:
(('unixTimeMS >= cast(1671460399129 as bigint)) AND ('unixTimeMS < 1671692708834))(('date >= date_sub(cast(cast(from_unixtime((cast(1671633199129 as double) / 1000), yyyy-MM-dd HH:mm:ss, None) as timestamp) as date), 2)) AND ('date < cast(date_add(cast(from_unixtime((cast(1671692708834 as double) / 1000), yyyy-MM-dd HH:mm:ss, None) as timestamp), 1) as date)))('organization_id = 7447636167761103)
FILTERING: Gold_jobRunCostPotentialFact using cron columns: unixTimeMS, date
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
APPLIED FILTERS:
MODULE_ID: 3015
MODULE_NAME: Gold_jobRunCostPotentialFact
FILTERS:
(('unixTimeMS >= cast(1671460399129 as bigint)) AND ('unixTimeMS < 1671692708834))(('date >= date_sub(cast(cast(from_unixtime((cast(1671633199129 as double) / 1000), yyyy-MM-dd HH:mm:ss, None) as timestamp) as date), 2)) AND ('date < cast(date_add(cast(from_unixtime((cast(1671692708834 as double) / 1000), yyyy-MM-dd HH:mm:ss, None) as timestamp), 1) as date)))('organization_id = 7447636167761103)
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
Overriding spark.sql.autoBroadcastJoinThreshold from 10485760b --> -1
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.

Beginning: 3015-Gold_jobRunCostPotentialFact
TIME RANGE: 2022-12-21 14:33:19 -> 2022-12-22 07:05:08

Beginning: 3015-Gold_jobRunCostPotentialFact
TIME RANGE: 2022-12-21 14:33:19 -> 2022-12-22 07:05:08
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
Gold_jobRunCostPotentialFact: Validating Input Schemas
DEBUG: Source DF Partitions: 0
DEBUG: Target Shuffle Partitions: 100
DEBUG: Max PartitionBytes (MB): 64.0
SUCCESS! Gold_jobRunCostPotentialFact
OUTPUT ROWS: 0
RUNTIME MINS: 1.44
WARNING: ENDING TIMESTAMP CHANGED:
Initial UntilTS of 1671693103790 exceeds that of an upstream requisite module. with untilTS of: 1671692708834. Setting current module untilTS == min requisite module: 1671692708834.
GOLD VIEW: CREATE: Statement --> create or replace view overwatch.jobRunCostPotentialFact as select 
organization_id, workspace_name, run_id, job_id, id_in_job, job_runtime, run_terminal_state, run_trigger_type, run_task_type, cluster_id,
cluster_name, cluster_type, custom_tags, driver_node_type_id, node_type_id, dbu_rate, running_days,
run_cluster_states, avg_cluster_share, avg_overlapping_runs, max_overlapping_runs, worker_potential_core_H,
driver_compute_cost, driver_dbu_cost, worker_compute_cost, worker_dbu_cost, total_driver_cost, total_worker_cost,
total_compute_cost, total_dbu_cost, total_cost, spark_task_runtimeMS, spark_task_runtime_H, job_run_cluster_util
from overwatch_etl.jobRunCostPotentialFact_gold where organization_id = jobRunCostPotentialFact_gold.organization_id and __overwatch_ctrl_noise = jobRunCostPotentialFact_gold.__overwatch_ctrl_noise 

OPTIMIZE: Missing Targets: 

OPTIMIZE: Targets To Optimize: 

GOLD VIEW: CREATE: Statement --> create or replace view overwatch_etl.pipReport as select 
organization_id, workspace_name, moduleID as module_id, moduleName as module_name,
cast(primordialDateString as date) as primordialDate,
to_timestamp(fromTS / 1000.0) as fromTS,
to_timestamp(untilTS / 1000.0) as untilTS,
status, writeOpsMetrics as write_metrics,
Pipeline_SnapTS, Overwatch_RunID
from overwatch_etl.pipeline_report where organization_id = pipeline_report.organization_id order by Pipeline_SnapTS desc 

res7: com.databricks.labs.overwatch.pipeline.Pipeline = [com.databricks.labs.overwatch.pipeline.Gold@78dcbca6](mailto:com.databricks.labs.overwatch.pipeline.Gold@78dcbca6)

Also, 

From our yesterdays job. If I look at the cluster statuses:

Cluster was running for 19 minutes, so if I check all statuses in the clusterstatefact table to see how much money we spend I should see this

![image](https://user-images.githubusercontent.com/64522653/209139331-f978b146-4232-45df-adfd-87a7284de934.png)

But its wrongly calculated:

The terminating start starts at 14.50 UTC, this is ok, but the running should span between 14.31 (This is OK) till terminating starts (14.50) but overwatch says 14.31 till 14.36 which is wrong

![image](https://user-images.githubusercontent.com/64522653/209139384-12a23e63-dcb9-4e30-b32f-7f52ac478fa6.png)

Also the terminating status is much longer than it should but i am not much worried by this one as it's not billable.

BR,
Albert

**Comment by AnushaSure** [comment]
Hi @anogues-danone ,

Please upgrade to the latest 07x version and  check the data. Here is the overwatch doc for [version updates](https://databrickslabs.github.io/overwatch/changelog/)

Regards,
Anusha

**Comment by anogues-danone** [comment]
I wil try in the affected workspace only, in a new set of db's as otherwise i will broke the others with the update.

I will let you know once finished.

BR,
Albert

**Comment by AnushaSure** [comment]
Hi @anogues-danone ,

If all the workspaces are sharing the common storage location of overwatch output then upgrade in 1 workspace will affect the other workspaces as well. So, if you are testing with 1 workspace please pause the job for all the other workspaces.

Regards,
Anusha

**Comment by anogues-danone** [comment]
Hi @AnushaSure 

Yes, i Know. Instead of an upgrade i created a new db in another path and with another name, so this way it only affected one workspace.

I am seeing what is the best way to move foward now. Maybe we will not upgrade as we dump this info in another database, and will start from scratch to multiple workspace deployment. I need to address what is the best option.

Another option is to upgrade and keey the job running in each workspace, but we have a lot and i would like to take advantage of the multi workspace deployment...

I need to think properly...

**Comment by AnushaSure** [comment]
Ok @anogues-danone . Please let me know if you have any questions on either of the approach.

Regards,
Anusha

**Comment by anogues-danone** [comment]
> Ok @anogues-danone . Please let me know if you have any questions on either of the approach.
> 
> Regards, Anusha

Seems the new calculations are ok now, but i want to test further, having jobs running at the time overwatch is fetching the data, which is the case of the wrong calculation we had.
I will keep you posted, thanks!

Albert

**Comment by anogues-danone** [comment]
By the way @AnushaSure  I found put that the first time i ran a job for a new workspace, it gets stuck nearly for two hours in the following step:
Silver_JobsRuns: Validating Input Schemas

Previously was not the case. Do you know what could be? Is there a way to speed this up? I'm talking about workspaces with only two jobs executed. May be possible because my ordinal date es 1st of Jan 2022 and i am loading 300 days altough there is no data until a month ago?

Because subsequent executions seem to be incremental and don't get stuck there.

BR,
Albert

**Comment by AnushaSure** [comment]
@anogues-danone Please check the count of output rows under **Bronze_AuditLogs, Silver_JobsStatus and Silver_ClusterSpec** modules. If the count is high then **Silver_JobsRuns** takes time to complete it's run.

Regards,
Anusha

**Comment by anogues-danone** [comment]
@AnushaSure 
Not really:

Beginning: 1004-Bronze_AuditLogs
TIME RANGE: 2022-01-01 00:00:00 -> 2022-10-28 00:00:00 --> Workspace ID: 8223003122966231
Bronze_AuditLogs: Validating Input Schemas
Bronze_AuditLogs: Validating Input Schemas
SUCCESS! Bronze_AuditLogs
OUTPUT ROWS: 2579
RUNTIME MINS: 0.15 --> Workspace ID: 8223003122966231


Beginning: 2010-Silver_JobsStatus
TIME RANGE: 2022-01-01 00:00:00 -> 2022-10-28 00:00:00 --> Workspace ID: 8223003122966231
Silver_JobsStatus: Validating Input Schemas

Beginning: 2014-Silver_ClusterSpec
TIME RANGE: 2022-01-01 00:00:00 -> 2022-10-28 00:00:00 --> Workspace ID: 8223003122966231
Silver_ClusterSpec: Validating Input Schemas
Silver_ClusterSpec -- First run detected, will impute cluster state from bronze to derive current initial state for all existing clusters.

**Comment by AnushaSure** [comment]
Hi @anogues-danone 

How long does it took to complete its run ?
What is the module status in pipreport ?

Please share the pipreport for analysis.

Regards,
Anusha

**Comment by anogues-danone** [comment]
> Hi @anogues-danone
> 
> How long does it took to complete its run ? What is the module status in pipreport ?
> 
> Please share the pipreport for analysis.
> 
> Regards, Anusha

Even if i just run after the previous run it takes more than an hour. So it's very strange. Usually with version 0.6.1 it used to take 20 mins:
I sent you two pip reports, one for the single workspace and another for multiple workspaces. Its always in the silver step in the Silver_JobsRuns: Validating Input Schemas step. I checked the sparkUI and it's doing some broadcasting and other stuf with dozens of thousands of stages or even hundreds of thousands, when there is no data in fact.

I didn't try with the photon btw. Its a small cluster but with no data should go pretty fast. My surprise is that old versions were much faster:

![image](https://user-images.githubusercontent.com/64522653/209826114-b21a8c37-bd8d-4f85-bec7-4218fcf0bb70.png)
In a workspace with 0 activity almost... So quite strange.
 
[PipReports.zip](https://github.com/databrickslabs/overwatch/files/10314636/PipReports.zip)

Regards,
Albert

**Comment by anogues-danone** [comment]
Also, I've found another issue.

When a job is cancelled manually, the RUNNING status is calculated wrongly by overwatch. At least for the overwatch job itself:

![image](https://user-images.githubusercontent.com/64522653/209826409-65e4a126-0b37-4af5-b804-ea8c699e8e6c.png)

Everytime i run overwatch is increasing the running time when the job was cancelled and terminated earlier:

![image](https://user-images.githubusercontent.com/64522653/209826536-ea6995d8-c619-4420-b93e-e741b7f4a099.png)

**Comment by anogues-danone** [comment]
@AnushaSure If you have time today till 6PM CET or tomorrow I am also available and I can show you live, if you prefer.

Thanks!
Albert

**Comment by AnushaSure** [comment]
@anogues-danone Can we meet around 2PM to 5 PM CET next week ?

Mail_id - anusha.sure@databricks.com

Regards,
Anusha

**Comment by anogues-danone** [comment]
> @anogues-danone Can we meet around 2PM to 5 PM CET next week ?
> 
> Mail_id - [anusha.sure@databricks.com](mailto:anusha.sure@databricks.com)
> 
> Regards, Anusha

Hi @AnushaSure 

Sure, I sent you invite for Monday 4pm.

Feel free to reschedule as you wish.

BR,
Albert

**Comment by anogues-danone** [comment]
Hello @AnushaSure 
Made some tests:

With a single node cluster of 28 GB of ram in an almost empty workspace, the daily load takes:
Old Job Duration (0..6.1.0) --> 20 min
New Job Duration (0.7.1.0) -_> 1h20min

However, i did several tests with the new version, these are the times:
With a cluster of two nodes of 28 GB of ram each--> 20 min
With a single node cluster og 54 GB of ram --> between 40 and 50 mins
With a cluster of only one node (+driver) --> 25 mins.

So it seems new version simply just don't play well with a signle node cluster.

BR,
Albert

**Comment by AnushaSure** [comment]
Hi @anogues-danone ,

Yes, we do recommend multi node cluster for overwatch. Moving forward, kindly use a multi-node cluster.

Regards,
Anusha

**Comment by anogues-danone** [comment]
Hi.

@AnushaSure 
Ok, regarding the other point I've emailed you again because there is still a problem.

**Comment by AnushaSure** [comment]
Hi @anogues-danone ,

Please let me know if you have any questions on overwatch data.

Regards,
Anusha

**Comment by Aaditya-Mishra** [comment]
Hi @anogues-danone ,

I just needed an update on this, so could you please give some input on the issue?

Regards,
Aaditya

**Comment by mohanbaabu1996** [comment]
Hi @anogues-danone ,

Please let us know if you've any issues.
Thank you!
