### ISSUE TITLE
Unable to access IP restricted Databricks workspace

### ISSUE THREAD

**Issue by YatharthKaushik** [databrickslabs/overwatch#671]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
Latest version

**Describe the bug**
Getting 403 unauthorized access error while running helper notebook in databricks.

**Screenshots**
![image](https://user-images.githubusercontent.com/49161779/209429421-27332c2d-0f85-4853-b1f6-c13646a2f215.png)

**Issue Reports**
<img width="605" alt="image" src="https://user-images.githubusercontent.com/49161779/209429373-f4ed0333-a850-4123-908a-94427679e746.png">

**Comment by AnushaSure** [comment]
Hi @YatharthKaushik ,

This is probably your routing table is not configured correctly through the ipWhitelist.
Please run the attached document and validate how it works with dkea token and dapi token.

Which overwatch version you are using ? Is this your first run ?

Regards,
Anusha
[Readiness_python_api.zip](https://github.com/databrickslabs/overwatch/files/10301729/Readiness_python_api.zip)

**Comment by YatharthKaushik** [comment]
Hi @AnushaSure,

I ran the script shared by you and got an empty 'clusters_' list while rest all the commands ran successfully:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/49161779/209550133-47875959-4b94-45d1-805e-465732f3a69b.png">

Our current Overwatch version is 0.7.0 also, this is our first run in this Databricks workspace.

We are working on migrating to the latest version, but I am getting the following error when I run the 071x_Runner notebook:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/49161779/209550496-cbced3a3-ee50-45ec-a223-6ab731769206.png">

**Comment by AnushaSure** [comment]
Hi @YatharthKaushik 

The error in the shared script is because your routing table is not configured correctly. Please raise support ticket with the above error details and get the IP Whitelisting set up correctly to allow the workers to talk to the control plane and vice-.versa.

Please confirm which overwatch library is installed in cluster config while migrating to the latest version ?. The above error in 071s runner notebook indicates that 0710 library is not installed under cluster config.

You have updated primordial date as '2022-09-30'. Since you are on Azure, for the first run you can retrieve the data from past 7 days based on your Event hub retention period. You may not have the data from 30th Sep.

Regards,
Anusha

**Comment by alexott** [comment]
@YatharthKaushik is your workspace is the private link enabled?

**Comment by YatharthKaushik** [comment]
Hi @AnushaSure 

Should I raise a request with Microsoft Azure support team?

Also, I have installed the latest version of overwatch library in cluster config and it is working now.

Thanks

**Comment by YatharthKaushik** [comment]
> @YatharthKaushik is your workspace is the private link enabled?

Hi, where can I check that?

**Comment by alexott** [comment]
in the workspace configuration

**Comment by YatharthKaushik** [comment]
> in the workspace configuration

thanks

**Comment by YatharthKaushik** [comment]
Hi @alexott,

Just had one more question about do I need to enable cluster logs for all the clusters in my workspace or just the one being used to run the 071x_Runner Notebook?

**Comment by AnushaSure** [comment]
Hi @YatharthKaushik ,

It is not mandatory to enable cluster logs to run overwatch. Enable of cluster logs will create spark tables.
Please go through this [image](https://databrickslabs.github.io/overwatch/images/_index/Overwatch_Gold_070.png) for spark tables.

Regards,
Anusha

**Comment by YatharthKaushik** [comment]
Hi @AnushaSure.

I do want to generate spark tables which should have information about all the clusters in my workspaces.

So, for that do I need to enable cluster logging in all of the clusters or just the one being used to run the 071x_runner notebook?

Thanks,
Yatharth

**Comment by AnushaSure** [comment]
Hi @YatharthKaushik ,

Yes, if you want the spark tables for all clusters then you must enable cluster logs for every cluster. Spark tables provide information about clusters with enabled cluster logs.

Regards,
Anusha

**Comment by AnushaSure** [comment]
Hi @YatharthKaushik 

Closing this ticket for now. Please re-open the ticket if you have any questions.

Regards,
Anusha
