### ISSUE TITLE
Missing jobs and accounts related tables in Overwatch

### ISSUE THREAD

**Issue by arbaaz750** [databrickslabs/overwatch#672]
**Overwatch Version**
0.7.0

**Describe the bug**
Recently we have deployed Overwatch on Azure Databricks and even after few successful runs, tables related to Jobs and Accounts are missing.
List of missing tables:
- jobRun 
- jobRunCostPotentialFact 
- accountLogin 
- accountMods 

And also need some clarification on setting up "Global Account Storage" dedicated to Overwatch in Azure.

**Comment by AnushaSure** [comment]
Hi @arbaaz750 ,

Please share the pipreport for analysis.
Are you using 0701 version ?

Here is the [Overwatch doc](https://databrickslabs.github.io/overwatch/deployoverwatch/cloudinfra/azure/#setting-up-storage-accounts) for setting up the storage account.

Regards,
Anusha

**Comment by AnushaSure** [comment]
Hi @arbaaz750 ,

 Please let me know status of the above issue. Are you still able to see the missing tables?

Regards,
Anusha

**Comment by arbaaz750** [comment]
Hi @AnushaSure ,

Overwatch version is: 0.7.0.0.5

Current status:
After few runs **jobRun** and **jobRunCostPotentialFact** was created successfully.
but still **accountLogin** and **accountMods** is still not getting generated.

Thanks,
Arbaaz

**Comment by AnushaSure** [comment]
Hi @arbaaz750 ,

Please share the pipreport for analysis.

Regards,
Anusha

**Comment by AnushaSure** [comment]
Hi @arbaaz750 ,

Since you deployed overwatch with 0710 which resolved the issue. Hence closing the ticket.
Please raise a ticket if you have any issues further.

Regards,
Anusha
