### ISSUE TITLE
handling of trailing slashes in api_urls

### ISSUE THREAD

**Issue by jelmerk** [databrickslabs/overwatch#689]
**Overwatch Version**
0.7.1.0

**Describe the bug**
If you use the MultiWorkspaceRunner and the api_url contains trailing slash like `https://oregon.cloud.databricks.com/` instead of `https://oregon.cloud.databricks.com` then many targets will silently fail but the job will pass. 

It's easy to reproduce the error that causes the targets to fail in isolation in a notebook with

```
import com.databricks.labs.overwatch.ApiCallV2
import com.databricks.labs.overwatch.utils.ApiEnv

val jobsEndpoint = "jobs/list"

val query = Map(
  "limit" -> "25",
  "expand_tasks" -> "true",
  "offset" -> "0"
)


val apiEnv = ApiEnv(
  isLocal = false, 
  workspaceURL = "https://foo.cloud.databricks.com/",
  rawToken = "dapi_blah_blah",
  packageVersion = "0.7.1.0",
)

ApiCallV2(apiEnv, jobsEndpoint, query, 2.1)
  .execute()
  .asDF()
  .show()


```

Changing [this line](https://github.com/databrickslabs/overwatch/blob/2b5e65334b802b960e69fe3e0bf16ad5d2a6d024/src/main/scala/com/databricks/labs/overwatch/ApiMeta.scala#L103) to 

```
var request = Http(s"""${apiEnv.workspaceURL.stripSuffix("/")}/${apiV}/${apiName}""")
```

Would remedy it. Also would very much appreciate it if failures like this would fail the job, and not skip over the failures

**Comment by mohanbaabu1996** [comment]
Hi @jelmerk ,

Thanks for letting us know. We will do the necessary changes.
