### ISSUE TITLE
[BUG] scope dbsql missing in Multiworkspace deployment

### ISSUE THREAD

**Issue by sriram251-code** [databrickslabs/overwatch#700]
In Multiworkspace deployment scope dbsql is missing.

**Comment by sjrusso8** [comment]
Is there a workaround to enable DBSQL scope for multi-workspace deployment? I am running into the same issue where the dbsql scope is not listed as an included scope for `com.databricks.labs:overwatch_2.12:0.7.1.0` and my config file is not set to exclude any available scopes.
