### ISSUE TITLE
Runner can not handle 'auto' partition setting

### ISSUE THREAD

**Issue by frosforever** [databrickslabs/overwatch#711]
Overwatch currently assumes that `spark.sql.shuffle.partitions` is set to an `Int` and will fail to run otherwise.

https://github.com/databrickslabs/overwatch/blob/2b5e65334b802b960e69fe3e0bf16ad5d2a6d024/src/main/scala/com/databricks/labs/overwatch/pipeline/Initializer.scala#L581

Databricks runtime currently supports setting partitions to `auto` which then fails overwatch jobs.

Code should likely either be updated to handle `auto` or documentation updated to explicitly call out this issue and recommend against setting `auto` partitions.

**Comment by frosforever** [comment]
AFAICT, seems like overwatch explicitly handles the number of partitions e.g. https://github.com/databrickslabs/overwatch/blob/2b5e65334b802b960e69fe3e0bf16ad5d2a6d024/src/main/scala/com/databricks/labs/overwatch/pipeline/Module.scala#L59 etc and `auto` is indeed inappropriate. 

### Perhaps something like the following can be added to a troubleshooting doc:

**Issue**: Job fails with the following exception in logs:

```
ERROR MultiWorkspaceDeployment: Got Exception while Deploying,
For input string: "auto"
java.lang.NumberFormatException: For input string: "auto"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
...
```

**Resolution**: Confirm `spark.sql.shuffle.partitions` is not set to `auto`. Overwatch explicitly handles this setting and expects no value present on the cluster. If one is provided, it must be a valid integer and not `auto`.

**Comment by GeekSheikh** [comment]
This was resolved in 0711
