### ISSUE TITLE
JobRunCostPotentialFact not getting new data

### ISSUE THREAD

**Issue by CH-JeremiahDeram** [databrickslabs/overwatch#712]
**Overwatch Version**
0.7.1.0 (running as jar)

**Describe the bug**
`overwatch.JobRunCostPotentialFact` table is only showing a limited date range of information, and the maximum date is not increasing with daily overwatch job runs.
In the screenshots below, you can see how among these 4 sample jobs, new job run data is flowing into `jobrun_silver`, but `jobruncostpotentialfact` remains stagnant.

**Screenshots**
Min/Max job run dates on 1/24
First cell shows `overwatch_etl.jobrun_silver`
Second cell shows `overwatch.jobruncostpotentialfact`
![image-20230124-210916](https://user-images.githubusercontent.com/91224803/214595020-61fe14d2-13d8-4e43-925f-9c9175af3ffd.png)

Min/Max job run dates on 1/25
First cell shows `overwatch_etl.jobrun_silver` (We see newer max dates)
Second cell shows `overwatch.jobruncostpotentialfact` (Max dates haven't changed)
![image-20230125-141057](https://user-images.githubusercontent.com/91224803/214595065-41cacd64-e522-40e3-b8a5-d7f13f5b7190.png)

**Issue Reports**
(can provide diagnostics report via email or slack)

**Comment by Arfa-1999** [comment]
Please share the pipeline report to validate, select * from overwatch_etl.pipeline_report order by pipeline_snapts desc;

**Comment by CH-JeremiahDeram** [comment]
Diagnostic report below. I had to add a .txt extension to the html file to allow for attachment.

[GenericTicket_Diagnostics.html.txt](https://github.com/databrickslabs/overwatch/files/10506143/GenericTicket_Diagnostics.html.txt)

**Comment by Arfa-1999** [comment]
The above shared is a HMTL file, which is hard to interpret. Can you run this SQL query **select * from overwatch_etl.pipeline_report** , download that Dataframe and share that. It helps us to understand the running status of Modules.

**Comment by CH-JeremiahDeram** [comment]
> The above shared is a HMTL file, which is hard to interpret. Can you run this SQL query **select * from overwatch_etl.pipeline_report** , download that Dataframe and share that. It helps us to understand the running status of Modules.

All you have to do is download the file, remove the .txt extension, and open it with a browser. It behaves just like a read-only databricks notebook.

**Comment by Arfa-1999** [comment]
While opening this is what I can see 

<img width="522" alt="image" src="https://user-images.githubusercontent.com/121929173/215012445-c172d907-bdf6-47a1-82ee-8ab15559a284.png">


You can share the file to syeda.arfa@databricks.com

**Comment by Arfa-1999** [comment]
Hi @CH-JeremiahDeram ,

Have you got a chance to look into it?

**Comment by CH-JeremiahDeram** [comment]
Hi @Arfa-1999 , I sent the diagnostic report via email on 26 Jan. Please let me know if I need to send again, thanks.

**Comment by Arfa-1999** [comment]
Hi @CH-JeremiahDeram, I am able to open your report and validated for JobRunCostPotentialFact Module, the data was present from primordial date till Jan 25th (at the time of Jan 25th run).
1. Whether the secret key configured in the overwatch should have an admin access or not?
2. Are you using AWS cloud?
3. What's your timezone so that we can discuss and resolve it, and I'm from IST timezone
<img width="932" alt="image" src="https://user-images.githubusercontent.com/121929173/217255390-05ffcec9-6f46-4c03-8f11-fdcd6195cc5a.png">

**Comment by CH-JeremiahDeram** [comment]
This has been resolved by ensuring the token we are using for overwatch has admin rights.
Thanks for your help with this!

Do you guys mind if I create another issue for checking that the token being used has admin access?
Could be included in `com.databricks.labs.overwatch.MultiWorkspaceDeployment.validate()`
