### ISSUE TITLE
[BUG] - Case condition in Excluded Scope config

### ISSUE THREAD

**Issue by mohanbaabu1996** [databrickslabs/overwatch#715]
Hi Team,

If any workspace doesn't have jobs then we need to exclude the scope in the multi workspace input config.
For example, I've mentioned "Jobs:pools" in the excluded scopes column and ran the pipeline.
But it ran for jobs modules and ended up with errors, because workspace don't have jobs.
Then changed it to lower case letters and it worked.

![image](https://user-images.githubusercontent.com/87074323/215514651-1a043744-e2b2-474b-a2c8-0f25b39841cc.png)

It should be like below

![image](https://user-images.githubusercontent.com/87074323/215519781-2ab2494a-a23b-461b-95d2-14d4a8007a03.png)

**Comment by GeekSheikh** [comment]
excludedScopes must be case insensitive but still map to the camel case standardScopes appropriately. @sriram251-code -- I'm not sure if you already took care of this with the dbsql scope issue but if not, please address this as well for 0711.
