### ISSUE TITLE
Cluster & Clusterstatefact - Null Values for Runtime Engine

### ISSUE THREAD

**Issue by AnushaSure** [databrickslabs/overwatch#718]
When a spark version is available, the runtime_engine column in the cluster and clusterstatefact tables is frequently populated with null values. As per [github code](https://github.com/databrickslabs/overwatch/blob/main/src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala), it should be either 'PHOTON' or 'STANDARD'.

![image](https://user-images.githubusercontent.com/93247478/215765040-73d727e0-7efb-4817-b24f-718811933e08.png)

**Comment by GeekSheikh** [comment]
Improvements can be made to populate the runtime_engine from raw source. Only certain actions provide this info and this info should be looked up and/or filled appropriately similar to how we do many other fields.

**Comment by GeekSheikh** [comment]
closed by #510
