### ISSUE TITLE
Clarification in docs relating to `cluster_type` column in JobRunCostPotentialFact definitions

### ISSUE THREAD

**Issue by frosforever** [databrickslabs/overwatch#720]
**Overwatch Version**
`0.7.1.0`

**Describe the bug**
More a clarifying question than a bug per se.
https://github.com/databrickslabs/overwatch/blob/9fefb2443be700d74959bfd8ea497a32f16cd7d1/docs-compose/overwatch_docs/content/DataEngineer/Definitions/_index.md?plain=1#L414 states the expected values for `cluster_type` in `JobRunCostPotentialFact`. However, tables that are generated in my runs all have the following value: `automated` which is not in the documented values. 
Is the documentation missing this value or is this indicative of a broader issue?

**Screenshots**
![image](https://user-images.githubusercontent.com/1630422/216185754-c5f66d6c-7571-48c9-b36c-b083d97d07c1.png)

**Comment by mohanbaabu1996** [comment]
Hi @frosforever ,

I think docs needs to be updated. In your case, all the jobs are running with job's cluster, that's why the cluster_type is mentioned as automated. If any interactive cluster, then it will be "existing"
