### ISSUE TITLE
"Got Exception while Deploying, Secret does not exist with scope" error on running MultiWorkspaceDeployment

### ISSUE THREAD

**Issue by anoj-9771** [databrickslabs/overwatch#721]
Hi all,

I'm trying out overwatch for our organization.
I'm using notebook (linked on this [page](https://databrickslabs.github.io/overwatch/deployoverwatch/runningoverwatch/notebook/)) to deploy overwatch. On running the notebook, I'm getting errorMsg in the deploymentReport:

`Got Exception while Deploying, Secret does not exist with scope: ADS_KV_ACCOUNT_SCOPE and key: null java.lang.IllegalArgumentException: Secret does not exist with scope:`

I can see that the error is showing secret key as null but I have provided key in the config (screenshots attached). Also the validation `NOTNULL_SecretKey_DBPAT` was successful as well. As a Scala newbie, I was unable to troubleshoot much further. Could anyone please point me to what the issue might be here? Thanks in advance!

![2023-02-03 11_55_51-071x_Runner - Databricks and 1 more page -  InPrivate  - Microsoft​ Edge](https://user-images.githubusercontent.com/27731256/216487111-935e1171-cdc4-4ff1-a05c-5244342a4bd6.png)
![2023-02-03 12_11_11-071x_Runner - Databricks and 1 more page -  InPrivate  - Microsoft​ Edge](https://user-images.githubusercontent.com/27731256/216487151-2b1ad526-9ec5-4373-ad9d-cb231600430b.png)
![2023-02-03 11_54_36-071x_Runner - Databricks and 1 more page -  InPrivate  - Microsoft​ Edge](https://user-images.githubusercontent.com/27731256/216488160-31ef57fd-f27b-4bc3-889e-de1243b481cb.png)

**Comment by AnushaSure** [comment]
Hi @anoj-9771 ,

Please share the html file of the notebook for analysis.

Regards,
Anusha

**Comment by anoj-9771** [comment]
Thanks for your response @AnushaSure ! I've attached the HTML here.
[071x_Runner (1).zip](https://github.com/databrickslabs/overwatch/files/10637309/071x_Runner.1.zip)

**Comment by AnushaSure** [comment]
Hi @anoj-9771 ,

Thanks for sharing the file.
The error is pointing to secret key  (connection string) of event hub. Please fill the event hub details and re-run.

Regards,
Anusha

**Comment by anoj-9771** [comment]
You're right @AnushaSure ! I was testing out overwatch while eventhub was being configured. The error threw me off a bit. The error would probably be better if it explicitly called out `eh-scope-key` or `secret-key-dbpat`.
