### ISSUE TITLE
Bronze layer is not processed in a particular workspace

### ISSUE THREAD

**Issue by pcocko** [databrickslabs/overwatch#724]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.7.1.0

**Describe the bug**
Bronze tables are not processed when multiworkspace deploy is executed. But it only happen with this workspace and it is properly configured in the config file. The report is skipping bronze tables so I assume that the problem is before that. But I don't have any error about the configuration

**Screenshots**
<img width="978" alt="image" src="https://user-images.githubusercontent.com/2462035/217388098-21ff699b-5459-4e69-a033-66158be0cc9a.png">

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by Neha-vs123** [comment]
Hi @pcocko ,
Please send the pipeline report for analyzing the issue. Use the command below:
`select * from overwatch_etl.pipeline_report order by pipeline_snapts desc`

**Comment by pcocko** [comment]
thanks @Neha-vs123 , here is the first 30 rows of the pipeline report

[export_overwatch.csv](https://github.com/databrickslabs/overwatch/files/10684762/export_overwatch.csv)

**Comment by pcocko** [comment]
@Neha-vs123 we have deployed only one overwatch but it's retrieving data from other two workspaces. One of them works well but the other one is skipping the bronze tables

**Comment by Neha-vs123** [comment]
@pcocko please share your availability for next week. We need to get on a call to analyze the issue.
I am from the IST timezone, available from 8 am to 11 am EST on Tue/Wed/Thurs.
Here is my mail id, neha.vs@databricks.com

Please schedule a 1-hour meeting for troubleshooting.

**Comment by pcocko** [comment]
Hi @Neha-vs123,

This issue was solved. Starting from scratch it solved the issue. But I am facing a problem in other workspace.
Basically I am getting a this error in the validation step:

`com.databricks.labs.overwatch.utils.ApiCallFailure: {"error_code":"403","message":"Unauthorized access to Org: 6973829937583411"}`

It's because we have the IP access list feature enabled

How we can solve the problem? 

Thanks in advance

**Comment by Neha-vs123** [comment]
Hi @pcocko ,

Have you created the secret scope in the driver workspace (the workspace in which the overwatch job is running) and PAT token in the remote workspace in which you are getting this error? 

There should be only one secret scope and it should be created in the driver workspace itself. The PAT token must be created from all the workspaces and stored in the secret scope of the driver workspace. Please confirm this. 

Have you properly configured the API URL of the remote workspace?

**Comment by Neha-vs123** [comment]
Hi @pcocko, I am closing this issue for now. Please re-open it if the issue exists.
