### ISSUE TITLE
Bronze_ClusterEventLogs FAILED --> Unable to receive all the clusters/events api responses

### ISSUE THREAD

**Issue by hebo-yang** [databrickslabs/overwatch#728]
I constantly get this error for our ST workspace. Could we not fail the entire Bronze_ClusterEventLogs for this?

Bronze_ClusterEventLogs FAILED --> Unable to receive all the clusters/events api responses; Api response received 56600;Api response not received 160 java.lang.Exception: Unable to receive all the clusters/events api responses; 

https://github.com/databrickslabs/overwatch/blob/2b5e65334b802b960e69fe3e0bf16ad5d2a6d024/src/main/scala/com/databricks/labs/overwatch/pipeline/BronzeTransforms.scala#L534

**Comment by hebo-yang** [comment]
Also, how to resolve this?

**Comment by AnushaSure** [comment]
Hi @hebo-yang 

Which overwatch version are you using ?

Regards,
Anusha
