### ISSUE TITLE
How are `date` columns created for SparkJob and SparkTask tables?

### ISSUE THREAD

**Issue by frosforever** [databrickslabs/overwatch#734]
Hello!

I'm attempting to join sparkTask and sparkJob tables. Ideally I'd use `date` in the join key as it is a partition column for both tables. However, I see that some stages show a different date in task vs job. Where does `date` come from for each table?

example query:
```scala
    sparkTask
      .as("st")
      .join(
        sparkJob
          .withColumn("stage_id", explode($"stage_ids"))
          .as("sj"),
        Seq("cluster_id", "workspace_name", "organization_id", "spark_context_id", "stage_id"),
        "inner"
      ).filter($"stage_id" === 1511)
      .filter($"cluster_id" === "0114-160400-m6adq274")
      .select($"cluster_id", $"st.date".as("task_date"), $"sj.date".as("job_date"), $"stage_id", $"st.timestamp".as("task_ts"), $"sj.timestamp".as("job_ts"))
.distinct
.show()
```
returns

|cluster_id          |task_date      |job_date      |stage_id|task_ts         |job_ts          |
|--------------------|----------|----------|--------|-------------------|-------------------|
|0114-160400-m6adq274|2023-01-14|2023-01-14|1511    |2023-01-14 18:46:17|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-14|2023-01-14|1511    |2023-01-14 18:46:14|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-15 01:21:25|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 23:05:13|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 22:15:29|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 19:55:57|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-15 01:37:28|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 22:21:52|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 23:07:19|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 22:14:46|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 22:56:58|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 23:15:51|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 23:04:59|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-15 00:13:38|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 23:08:08|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 23:07:29|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 23:09:13|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 22:22:40|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 23:05:27|2023-01-14 18:45:49|
|0114-160400-m6adq274|2023-01-15|2023-01-14|1511    |2023-01-14 22:59:37|2023-01-14 18:45:49|

Thanks for the help and please feel free to direct me elsewhere if this is not the appropriate venue for such questions!

**Overwatch Version**
`0.7.1.0`

**Comment by frosforever** [comment]
Super helpful! So `date` is from `timestamp` and I think adding to my confusion is that it was calculated using date at UTC while I was then querying the data using `America/New_York` so the dates didn't line up with the date displayed in the timestamp. 

Thanks for the help @shravanshibu90!

**Comment by GeekSheikh** [comment]
Glad you got what you needed @frosforever. 

Think of the lifecycle of a spark job ([more details here](https://databrickslabs.github.io/overwatch/dataengineer/modules/#sparkevents)). A job can start on day 1, a job is full of tasks and it's often that some of the tasks will start on day 1 while others start on day 2. You could do a range join here manually but that's essentially what the `joinWithLag` function is doing for you. Good question
