### ISSUE TITLE
"Got Exception while Deploying, hadoop_azure_shaded.com.microsoft.azure.storage.StorageException" on deploying bronze layer

### ISSUE THREAD

**Issue by anoj-9771** [databrickslabs/overwatch#735]
Hi team,
I've got a question similar to the one mentioned in this closed issue:
https://github.com/databrickslabs/overwatch/issues/536

When deploying the bronze layer I'm getting this error:
```Got Exception while Deploying, hadoop_azure_shaded.com.microsoft.azure.storage.StorageException: This operation is not permitted on a non-empty directory. shaded.databricks.org.apache.hadoop.fs.azure.AzureException: hadoop_azure_shaded.com.microsoft.azure.storage.StorageException: This operation is not permitted on a non-empty directory. at shaded.databricks.org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.delete(AzureNativeFileSystemStore.java:2828) at shaded.databricks.org.apache.hadoop...```

I was getting similar error referring to delete action in the validation part but I was able to resolve by clearing out the TEMPDIR folder and redoing the validation (the validation part has no failures). I've attached an HTML file showing the output of my run.
[eventhub_deployment_failure.zip](https://github.com/databrickslabs/overwatch/files/10729289/eventhub_deployment_failure.zip)

Could you please point me in the right direction here? Thanks in advance!

**Comment by mohanbaabu1996** [comment]
Hi @anoj-9771 ,

I've seen you notebook which you've attached. You've created the functions to delete all the folders inside "/mnt/datalake-raw/overwatch/stuff", but some folders inside the mount path belongs to overwatch are not deleted properly.

If possible could you send the snippet of below cmd,

%fs ls '/mnt/datalake-raw/overwatch/stuff'

**Comment by anoj-9771** [comment]
Thanks @mohanbaabu1996 ! I can confirm that the folder `/mnt/datalake-raw/overwatch/stuff/` was properly deleted . I've attached another html file showing the output of the aforementioned command post the folder deletion.

**Comment by mohanbaabu1996** [comment]
Hi @anoj-9771 ,

After cleaning, have you made a fresh run ?

**Comment by anoj-9771** [comment]
Yup. Same issue.

**Comment by mohanbaabu1996** [comment]
Do you have read write permission to the ETL_STORAGE_PREFIX?

**Comment by anoj-9771** [comment]
That's correct! After deleting the entire folder at the top of the notebook, I can see that the folder gets populated by the notebook and I can read the contents of files in it..
![Uploading 2023-02-16 18_09_06-.png…]()

**Comment by mohanbaabu1996** [comment]
Hi @anoj-9771 ,

I got an email that your issue is fixed, please confirm it once
![image](https://user-images.githubusercontent.com/87074323/219302104-8c38f8c2-de37-4e32-9f97-e8d04e98efbb.png)

**Comment by anoj-9771** [comment]
@mohanbaabu1996 , I was just answering your question above. I do have access to read and write to the `ETL_STORAGE_PREFIX`. After deleting the entire folder, I was able to see new content generated in the `ETL_STORAGE_PREFIX`  and I can also read the contents. So the issue is NOT related to the access to `ETL_STORAGE_PREFIX`..
![2023-02-16 18_09_06-](https://user-images.githubusercontent.com/27731256/219509227-5c9569c5-d94d-4e30-bf5e-b9f0470e5cf1.png)

**Comment by mohanbaabu1996** [comment]
Thanks @anoj-9771 for the confirmation.
After cleaned and able to see the folders, have you run the overwatch ?

**Comment by anoj-9771** [comment]
Yes. The original html file and the new html file both show the folders being cleaned up at the beginning.

**Comment by mohanbaabu1996** [comment]
Thanks @anoj-9771 for the update. If the issues are clear please close the ticket

**Comment by anoj-9771** [comment]
Hi @mohanbaabu1996 !
The issue is ongoing. The html files attached show the issue on hand. Please let me know what I can do/provide to assist the issue along. What we've established so far:
* all the storage locations are cleaned up prior running to the overwatch notebook
* the notebook has access to read and write into the locations
The same issue mentioned in the first post is still ongoing.

**Comment by mohanbaabu1996** [comment]
Hi @anoj-9771 ,

Are you from which time zone ?
I'm from IST and please schedule a call tomorrow (Thursday) anytime betweeen 11 - 8 PM IST.
My email ID: mohan.baabu@databricks.com

**Comment by anoj-9771** [comment]
Great! I'm in AEST and have sent you an invite. Thanks in advance!

**Comment by mohanbaabu1996** [comment]
Hi @anoj-9771 , As we discussed in our last call, 0711 is released this week.
Please run the [script](https://databrickslabs.github.io/overwatch/changelog/#0711) using 0711 library to get upgrade, also change the job clusters.
If you've any doubt, ping me through email.
Thanks!
