### ISSUE TITLE
Where to find spark context local properties

### ISSUE THREAD

**Issue by frosforever** [databrickslabs/overwatch#744]
Where can I find spark context local properties in overwatch tables? This would be for known keys like `spark.job.description` etc but also for custom keys that may be set using `org.apache.spark.SparkContext.setLocalProperty`? 

Thanks very much for the help and please direct me to a more appropriate forum for this question if this is not the right place. 

**Overwatch Version**
`0.7.1.0`

**Comment by GeekSheikh** [comment]
@frosforever 

You may find the cluster spark conf overrides like this
```scala
display(
  table("overwatch_global.cluster")
    .select('action, 'cluster_id, 'timestamp, 'spark_env_vars, 'spark_conf)
)
```

If you want to find the overrides at the time of a spark execution, you may find that like this. It's still only accessible from bronze but I have added a ticket to get it promoted to gold: #745 
```scala
display(
  table("overwatch_global_etl.spark_events_bronze")
    .filter('organization_id === orgId) // partition filter
    .filter('fileCreateDate >= date) // partition filter
    .filter('Event === "org.apache.spark.sql.execution.ui.SparkListenerSQLExecutionStart") // partition filter
    .select('organization_id, 'clusterId, 'sparkContextId, 'executionId, 'modifiedConfigs)
)
```

**Comment by frosforever** [comment]
This is definitely a start. Thanks!

Ultimately what I'd like to is track specific functions in databricks jobs over time. I have an extension function on `SparkSession` similar to 
```scala
    def usingJobGroup[R]( name: String, description: String = null)(f: => R): R = {
      spark.sparkContext.setJobGroup(name, description)
      try {
        f
      } finally {
        spark.sparkContext.clearJobGroup()
      }
    }
```

that I use like 
```scala
spark.usingJobGroup(name = "name", description = "some desc") {
  ...
  df.write(...)
}
```
which allows me to assign a job group to track over time. I'd like to know if adding more information via 
`spark.sparkContext.setLocalProperty(k, v)` can help in narrowing down the specific function over time if I'm able to join tasks / jobs back to a local property.

**Comment by GeekSheikh** [comment]
If this is part of a framework and you have control over the workloads -- you should be able to inject a custom spark listener and pull it out of the spark_events_bronze table. You would be able to store whatever data you wanted in the custom listener...does this help?

**Comment by mohanbaabu1996** [comment]
Hi @frosforever ,

Please open a ticket, if you've any further issues.
Thanks!
