### ISSUE TITLE
SparkEvents is not processed - Path Globs Empty, exiting

### ISSUE THREAD

**Issue by pcocko** [databrickslabs/overwatch#767]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
v0.7.1.0

**Describe the bug**
The sparkevents are not being processed because it says that is empty but the configuration file has the path to the folder where cluster logs are located.
Here the output:
```
Beginning: 1006-Bronze_SparkEventLogs
TIME RANGE: 2023-02-19 08:37:58 -> 2023-02-20 08:35:23 --> Workspace ID: XXXXXXXXXXXXX
Bronze_SparkEventLogs: Validating Input Schemas
Path Globs Empty, exiting
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by Neha-vs123** [comment]
Hi @pcocko, Has this issue occured in the same overwatch that is mentioned in [Issue 724](https://github.com/databrickslabs/overwatch/issues/724)?

If this is a different deployment, please provide the following details;
1. Azure or AWS ?
2. How many workspaces are involved in this deployment?
3. Send the pipeline report using the command - 
select * from <etl database name>.pipeline_report order by pipeline_snapts desc
5. Have you configured the csv columns correctly as given in the [docs](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/configuration/#column-description)?
6.Does the user who created the PAT token has admin access or Is the PAT token created by a Service principle (In case of Azure) ?

**Comment by pcocko** [comment]
Hi @Neha-vs123 ,

Is other deployment but I found that is happening in same deployment as well.

Here the details:

1. Azure or AWS ? **Azure**
2. How many workspaces are involved in this deployment? **One workspace**
3. Send the pipeline report using the command ?
select * from overwatch_etl.pipeline_report order by pipeline_snapts desc
[pipeline_report.csv](https://github.com/databrickslabs/overwatch/files/10785145/pipeline_report.csv)
4. Have you configured the csv columns correctly as given in the [docs] (https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/configuration/#column-description)?
 **Yes, I set "/mnt/overwatch" in the "etl_storage_prefix" column because logs are in /mnt/overwatch/cluster-logs/ folder**
5. Does the user who created the PAT token has admin access or Is the PAT token created by a Service principle (In case of Azure)? **Yes, the user who created the token has admin permissions**

**Comment by pcocko** [comment]
Hi @Neha-vs123,

I solved the problem

Basically, i didn't have the storage settings in cluster configuration

**Comment by mtyszkiewicz** [comment]
Hi @pcocko,
I'm having the same problem rn :)
Could you elaborate on what cluster settings solved the problem?

**Comment by AnushaSure** [comment]
Hi @mtyszkiewicz ,

Please go through [Azure Storate Auth Config](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/securityconsiderations/#azure-storage-auth-config) for cluster configuration.

Regards,
Anusha

**Comment by Mpicca** [comment]
Hello @mtyszkiewicz @pcocko @AnushaSure I am also running into this same issue. I have everything set up in an Azure environment using a user profile with admins permissions rather than a Service Principal. B/c of this, there is no application ID to reference in the config code. What did you all do to resolve this?

**Comment by Mpicca** [comment]
just an update for anyone else who may see this. I noticed the our Event Hub properties were set to a 1 hour retention. This contributed to the spark tables not loading data. When I increased the retention to max 7 days it loaded hope millions of rows.
