### ISSUE TITLE
[BUG] - MW - AWS - nonJSON audit log formats

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#781]
When building the configs for aws AuditLogConfig the json format was not added. This config should be optional and should be exposed in the config.csv file. Default should be JSON.

Added quick fix in 711 release. The format can be changed by adding the following spark conf to cluster. Set it to `json`, `parquet`, etc. Only necessary when audit log delivery is not default (json).

`overwatch.aws.auditlogformat`

https://github.com/databrickslabs/overwatch/blob/afb1f9ebcaeae3351dd963d3a140b56234643719/src/main/scala/com/databricks/labs/overwatch/MultiWorkspaceDeployment.scala#L114-L117

**Comment by sriram251-code** [comment]
tried adding overwatch.aws.auditlogformat parquet as spark config in AWS and got the exception as expected
<img width="1606" alt="Screenshot 2023-03-10 at 11 45 54 AM" src="https://user-images.githubusercontent.com/69749553/224238424-d5770bbc-b65d-4880-a116-cd0bf492fa7d.png">

**Comment by sriram251-code** [comment]
We have to implement this for GCP also as it also supports parquet file format for audit logging.

**Comment by sriram251-code** [comment]
we can have overwatch.auditlogformat as the parameter instead of overwatch.aws.auditlogformat

**Comment by GeekSheikh** [comment]
Testing still outstanding. Awaiting validation results.
