### ISSUE TITLE
Silver task fails with error; Undefined function: count.

### ISSUE THREAD

**Issue by TheRealJimShady** [databrickslabs/overwatch#783]
**Overwatch Version**
0.7.1.0

**Describe the bug**

- Cloud : Azure
- Cluster Spec : See attachment
- Configuration : Multiworkspace, configured as multitask job (bronze, silver, gold)
- Stack trace : See attachment
- Run as : Jar 

I've noticed that this error occurs most frequently immediately after I schedule the job following a period of manual triggering for test purposes. Leads me to think that there's something in the cluster state which is getting overwritten once the cluster restarts. I also sometime experience this issue when I use the validation notebook. A couple of other factors which I'm uncertain of are the isolation level on the cluster and whether or not I enable Table ACLs on the overwatch workspace. Have tested with older runtimes with and without photon and still get the same exception. Have also tried clearing out the databases and still get the same exception.

This seems to stem from a call to `com.databricks.labs.validation.Validator` which is part of the [dataframe-rules-engine repo](https://github.com/databrickslabs/dataframe-rules-engine), which has a dependency on Spark 3.0.1... is it possible that there's a regression since OW uses later versions of Spark? Fundamentally it looks like it's expecting `count` to be a function stored on the catalogue but it can't find it. Not sure if this is due to permissions on the catalogue or because of a regression... or much more likely, user error 😃 

**Screenshots**
![Screenshot 2023-02-23 205637](https://user-images.githubusercontent.com/12716005/221028465-1d46474f-ad3d-47b3-8e17-96e408ea4fea.png)
![Screenshot 2023-02-23 205810](https://user-images.githubusercontent.com/12716005/221028794-1d4f8e2c-cf90-48d9-bd52-6b27d14352e9.png)

[job-spec.txt](https://github.com/databrickslabs/overwatch/files/10818588/job-spec.txt)
[cluster-spec.txt](https://github.com/databrickslabs/overwatch/files/10818173/cluster-spec.txt)
[stack-trace.txt](https://github.com/databrickslabs/overwatch/files/10818174/stack-trace.txt)
[GenericTicket_Diagnostics_html.txt](https://github.com/databrickslabs/overwatch/files/10818337/GenericTicket_Diagnostics_html.txt)

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by GeekSheikh** [comment]
There's a bit of a leak in the spark context at times. We're working with engineering to find the best fix but for now, the answer is to restart the cluster and let the entire pipeline run. I see you're using an interactive cluster, a jobs cluster should be less likely to hit this. If you were to restart the cluster and run again, it will likely run just fine. Sorry for the inconvenience, we hope to have a permanent fix for this -- as noted this shouldn't happen very frequently.

If you run validation on an interactive cluster and then try to run the job on the same cluster this will happen.

**Comment by TheRealJimShady** [comment]
Thanks very much for your help so quickly, I can confirm that compressing the multi-task job into a single task and switching to a jobs cluster has fixed the issue. One other problem that I'm having is the the `Gold_jobRunCostPotentialFact` module is not producing any data, it runs to completion but always output zero rows - do you know why that might be?
