### ISSUE TITLE
[BUG] -Wrong dbu calculation for worker node for long running cluster.

### ISSUE THREAD

**Issue by sriram251-code** [databrickslabs/overwatch#803]
Issue:

For long running cluster in CLSF the worker node is coming as 0 hence the worker_dbus are coming as 0.

![Screenshot 2023-03-07 at 1 36 13 PM](https://user-images.githubusercontent.com/69749553/223361620-afbc436c-f319-426f-a3ae-6a87f94bd408.png)

This is happening because in cluster_events_bronze the num_workers are coming as null
![Screenshot 2023-03-07 at 1 38 08 PM](https://user-images.githubusercontent.com/69749553/223362128-4e5b8694-292c-4e73-8965-0ae096de501b.png)

Solution:
We can see num_workers perfectly populated in clusters_snapshot_bronze.
![Screenshot 2023-03-07 at 1 40 03 PM](https://user-images.githubusercontent.com/69749553/223362409-42404b75-14ec-4c11-99f6-6f0528a2953d.png)
In 1st run for Overwatch if we find num_workers are coming as null in cluster_events_bronze then we should consider num_workers which is present in clusters_snapshot_bronze.

**Comment by souravbaner-da** [comment]
Currently this change should be put on hold as creating record for the cluster for which we are not getting any cluster event is complex task. May be we would take this up in future release.

Cost in CLSF will not appear until cluster_state is changed to a state that will change the no of workers(i.e. until the Cluster is Restarted or Resized(auto scale or Manual)
The above detail has been mentioned in overwatch doc. Below is the issue for the same is:
#869
