### ISSUE TITLE
Only Bronze_AuditLogs module is executed

### ISSUE THREAD

**Issue by ankitshah-db** [databrickslabs/overwatch#804]
Got the Overwatch environment set up and ran the Bronze deployment. They are using use version 0.7.1.1. However, somehow only Bronze_AuditLogs module is executed. Rest of the modules are not running

The audit logs are coming from this location s3a://security-databricks-audit-logs/dev/workspaceId=XXXXXXX4237.
I just tried changing workspace_name to customerXXX-development but it does not seem to help

Here are the logs on my notebook after running MultiWorkspaceDeployment(updatedConfigCsvPath, tempLocation).deploy(parallelism, zones="Bronze")

**Comment by ankitshah-db** [comment]
@overwatch support team - also check the ES ticket - ES-618457 for more details

**Comment by GeekSheikh** [comment]
Here's the diagnostics report from the customer.
[GenericTicket_Diagnostics.zip](https://github.com/databrickslabs/overwatch/files/10914202/GenericTicket_Diagnostics.zip)

**Comment by mohanbaabu1996** [comment]
Hi @ankitshah-db ,

Does you PAT has the admin access to read the cluster & jobs from the workspace ?
Please validate with the help of below notebook.
Also 0711 is deprecated, so please do the clean up and start as a fresh with 0712. I could see your primordial date as March 03.
[ReadinessReview.dbc.zip](https://github.com/databrickslabs/overwatch/files/10929177/ReadinessReview.dbc.zip)

**Comment by mohanbaabu1996** [comment]
Hi @ankitshah-db,

Just following up here about the status.

Thanks,
Mohan Baabu

**Comment by mohanbaabu1996** [comment]
Hi @ankitshah-db,

Let me know if still you've issues.

**Comment by mohanbaabu1996** [comment]
Hi @ankitshah-db ,

Please let us know, if you have any issue.
Thanks!
