### ISSUE TITLE
Redefine the logic to derive cloud provider

### ISSUE THREAD

**Issue by aman-db** [databrickslabs/overwatch#820]
As per the current logic cloud provider is getting derived using apiURL using the below logic - 
```
workspaceURL.toLowerCase match {
  case cloudType if cloudType.contains("azure") => "azure"
  case cloudType if cloudType.contains("aws") => "aws"
  case cloudType if cloudType.contains("gcp") => "gcp"
  case _ => throw new BadConfigException(s"${workspaceURL.toLowerCase} NOT SUPPORTED: Supported clouds at this time " +
    s"include azure, aws, gcp")
}
```
which is failing for aws apiURL's. Need to come up with a different logic to get cloud provider.

**Comment by alexott** [comment]
You can get cloud provider from cluster tags - via Spark.conf

**Comment by GeekSheikh** [comment]
For multi-workspace deployments, the user provides the cloud provider. No GCP deployments should use legacy; so this might simplify the solution a little bit. 

@alexott are all cluster tags always available in all contexts? Another spark conf that may work is `spark.conf.get("spark.databricks.cloudProvider")`. Regardless of the path chosen we just need to make sure it's available from ALL Clouds in ALL CONTEXTS (i.e. JAR / Notebook Job / etc). I know some spark confs are only present via certain entry-point contexts.

![image](https://user-images.githubusercontent.com/10840635/226725428-f3fc3560-3cc1-4bd4-b78a-5ea7610f9f62.png)

**Comment by alexott** [comment]
Yes. That’s property. I believe I’ve tested it in both notebooks and jar context, but it makes sense to double check

**Comment by alexott** [comment]
dbutils context is a different beast
