### ISSUE TITLE
[DOCS] - Column Description Verbosity

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#864]
Review the column names in the data dictionary and increase clarity where necessary. Example is SQL Query History table -- improvements can be made.

**Comment by artemsheiko** [comment]
Context : As an example, sqlqueryhistory - there’s duration, compilation_time_ms , execution_time_ms , photon_total_time_ms , total_time_ms , task_total_time_ms  with no clear relation between them explained.
Information available today : 

- duration : Duration of the query execution
- compilation_time_ms : Query compilation time in ms
- execution_time_ms : Query execution time in ms
- photon_total_time_ms : Total time in ms Photon engine executed
- total_time_ms : Total time taken by query in ms
- task_total_time_ms : Total time taken by task to complete in ms

does it mean that the following is true :
total_time_ms = duration = N task * task_total_time_ms = N task * (compilation_time_ms + execution_time_ms)
photon_total_time_ms <= execution_time_ms
?
