### ISSUE TITLE
0711 Upgrade script failing

### ISSUE THREAD

**Issue by sambanks** [databrickslabs/overwatch#885]
**Overwatch Version**
0.7.1.0

**Describe the bug**
When using the upgrade script from https://databrickslabs.github.io/overwatch/changelog/#0711

The Helpers.getWorkspaceByDatabase() function gives the following error:

```
NoSuchElementException: next on empty iterator
```

**Screenshots**
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/3905846/232963761-3e174a36-4ef7-4764-be53-5260a7f555c8.png">

**Comment by Aaditya-Mishra** [comment]
Hi @sambanks ,

Where are you running this notebook in master/remove workspace ?
Which version of jar used for running for this script ?

Regards,
Aaditya

**Comment by sambanks** [comment]
Hey @Aaditya-Mishra thanks for coming back to me :) 

This is a single workspace installation (our dev) which I am testing before upgrading our multi-workspace installation.

I have tried with jars com.databricks.labs:overwatch_2.12:0.7.1.0 and com.databricks.labs:overwatch_2.12:0.7.1.2

**Comment by Aaditya-Mishra** [comment]
Hi @sambanks ,

Can you share the pipeline report of your first run from dev workspace which you have created for testing upgradation ?
May be your first run was not loaded properly.

query - Select * from etl_db.pipeline_report order by Pipeline_SnapTS Desc;

Regards,
Aaditya

**Comment by sambanks** [comment]
Sure here you go
[export.csv](https://github.com/databrickslabs/overwatch/files/11291151/export.csv)

**Comment by Aaditya-Mishra** [comment]
Hi @sambanks ,

As per the pipeline report, first time you ran on 2023-04-12 and  mentioned the primordial date as 2022 -12-31. But  the EventHub  contains only 7 days of retention period(Standard or premium tier) . In this case primordial date should be 7 days before the overwatch running date for the first run.
So I will suggest you to run the clean up [script ](https://databrickslabs.github.io/overwatch/faq/#q1-how-to-clean-re-deploy) and do the same process with new [version ](https://databrickslabs.github.io/overwatch/changelog/) of overwatch with correct config.

Are you using legacy process or multi deployment process ?
Let me know if you have any doubt ?

Regards,
Aaditya

**Comment by sambanks** [comment]
Thanks @Aaditya-Mishra sorry for the delay, been off, will try this today.

**Comment by GeekSheikh** [comment]
@sambanks are you taken care of?

**Comment by sambanks** [comment]
Hi There

We ended up deleting the whole installation and starting again. Thanks for the help.
