### ISSUE TITLE
Overwatch data in accruate 

### ISSUE THREAD

**Issue by Frank-China** [databrickslabs/overwatch#897]
**Sensitive Content Alert**
###Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.
Job run completed without sliver/brown jobs been run and the result data is not updated 
**Overwatch Version**
###Tell us the version of Overwatch used when you received the issue
overwatch_2.12:0.7.1.2
**Describe the bug**
###A clear and concise description of what the bug is.
Job completed but the result data is not updated 
**Screenshots**
###If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.
Run log can be provided later 
**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by mohanbaabu1996** [comment]
Hi @Frank-China ,

Not able to open the link which you've attached in the ticket.
Please use the 0713 overwatch library to run the repair [script](https://databrickslabs.github.io/overwatch/assets/ChangeLog/0713_Repair_Historical.html) to resolve the job's related issue

**Comment by mohanbaabu1996** [comment]
Hi @Frank-China ,
Let me know if you're still facing the issue.

**Comment by Frank-China** [comment]
Yes we still have the problem . We had submitted a ticket 00323160 to databricks

**Comment by mohanbaabu1996** [comment]
Thanks for the update, one of the team mate is looking into your issue. We will keep posted you in the ticket about the progress. As of now i'll close the ticket and and will chat on the ticket.
Thanks!
