### ISSUE TITLE
Overwatch Multi Config Deployment generating 70k tasks

### ISSUE THREAD

**Issue by SomanathSankaran** [databrickslabs/overwatch#898]
We tried Databricks overwatch with multiple deployment
with below config

Dependencies
com.databricks.labs:overwatch_2.12:0.7.1.3 (Maven)

com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.22 (Maven)

DBR:11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12)

![image](https://user-images.githubusercontent.com/25737263/233983302-c05c9051-fe5f-4c89-b5ea-9282ffbee826.png)

**Comment by GeekSheikh** [comment]
Is there some issue? 77K tasks is fine as many of them will be skipped. How much historical data are you trying to load? If you're going back a long way on several workspaces -- this is expected as we load all the data in parallel to allow for greater parallelism; thus allowing you to use larger clusters and complete faster if you desire.

How many workspaces?
How much history?

if loading a lot of history there will be many more spark tasks -- after the pipeline is caught up to current the daily runs will likely have substantially less tasks.

@mohanbaabu1996 -- please help the customer find this out.

**Comment by SomanathSankaran** [comment]
@mohanbaabu1996 @GeekSheikh we just run for 1 week it is quite strange why we have 70K+tasks spanned

**Comment by SomanathSankaran** [comment]
@GeekSheikh  we ran with 0.63 overwatch and it completed within 30 mins.

**Comment by mohanbaabu1996** [comment]
@SomanathSankaran Let me know if you've the issue. Also please upgrade the overwatch to the latest [version](https://databrickslabs.github.io/overwatch/changelog/).
Thanks!

**Comment by mohanbaabu1996** [comment]
Hi @SomanathSankaran ,
Please let me know if you've any doubt in upgrade process.
