### ISSUE TITLE
Need assistance analyzing Audit logs in Overwatch

### ISSUE THREAD

**Issue by shaikharbaaz101** [databrickslabs/overwatch#908]
**Overwatch Version**
0.7.1.0

**Describe the bug**
In Overwatch, we have Audit logs tables. However, we are having trouble efficiently analyzing these logs. Is there any way to analyze these logs in a dashboard or other alternative solution?

Additionally, we are curious to learn more about how Overwatch can help with auditing beyond cost tracking. If there are any resources or documentation available on this topic, we would greatly appreciate it.

Thank you for your help.

**Comment by mohanbaabu1996** [comment]
Hi @shaikharbaaz101 ,

All the audit logs are captured and split those logs into the gold layer after few transformations.
You can use the consumer database to create dashboards.

Also make sure to [upgrade](https://databrickslabs.github.io/overwatch/changelog/) overwatch to the latest version (0720)

**Comment by shaikharbaaz101** [comment]
Hi @mohanbaabu1996,
Can we do Databricks Auditing from Overwatch? if yes can we get some python script or a notebook, to create a chart from audit logs table.
if possible can we connect over a call and discuss about this? please provide your contact so that we can reach you.
you can connect with me on arbaaz.shaikh@mckesson.com

**Comment by mohanbaabu1996** [comment]
Sure, are you from which timezone ?

**Comment by shaikharbaaz101** [comment]
Hi Mohan, it's IST.

**Comment by mohanbaabu1996** [comment]
Are you available at 4:30 PM IST ?

**Comment by shaikharbaaz101** [comment]
Sure, lets connect at 4:30pm IST

**Comment by mohanbaabu1996** [comment]
Thanks, sent invite
