### ISSUE TITLE
[BUG] - Several non-API errors are reporting API CALL Failed

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#911]
To my recollection, module 1004 audit_log_bronze never hits an API. If this is accurate, why are we getting an API Call Failed error in the STDOUT? Please review the exception logic -- I feel like I'm seeing this error message erroneously in several places now, please double check.

![image](https://user-images.githubusercontent.com/10840635/234631900-b1bdc5f1-fc9d-434a-adaf-c67e4e6a3a19.png)

**Comment by GeekSheikh** [comment]
Here's another example with a full stack trace. The issue is schema merge but it's showing API Call Fail in the message.
[issue911.txt](https://github.com/databrickslabs/overwatch/files/11334919/issue911.txt)

**Comment by gueniai** [comment]
Fixed in #944
