### ISSUE TITLE
outdated plugins ( assembly and jacoco)

### ISSUE THREAD

**Issue by kashif-itv** [databrickslabs/overwatch#913]
**Overwatch Version**
7.2

**Describe the issue**
I am getting compilation issue because you are using old versions of plugins which are not available in repo.
Minimum version in repo for jacoco is 3.4.0  and you  are using 3.0.3
Minimum version in repo for assembly is 1.0.0 and you are using 0.14.9

**Comment by mohanbaabu1996** [comment]
Hi @kashif-itv ,

Hope you doing good, please let us know if you need any help.
Thanks!
