### ISSUE TITLE
[DOCS] AAD documentation Include maven coordinates: com.microsoft.azure:msal4j:1.10.1

### ISSUE THREAD

**Issue by sriram251-code** [databrickslabs/overwatch#920]
Update the documentation for AAD.For AAD Include maven coordinates: com.microsoft.azure:msal4j:1.10.1 as dependency.

**Comment by alexott** [comment]
if it's only for EventHubs AAD tokens, then it should be optional dependency...

**Comment by GeekSheikh** [comment]
already handled
