### ISSUE TITLE
[BUG] - JRCP - cluster_type derive logic

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#928]
It appears the cluster_type derivation logic is incomplete. This can affect cost accuracy in JRCP due to downstream photon calculations.

https://github.com/databrickslabs/overwatch/blob/a00b68e84c1c5603159cc40f7e64e31bf476bc4f/src/main/scala/com/databricks/labs/overwatch/pipeline/WorkflowsTransforms.scala#L1462-L1466

**Comment by brij-raghuwanshi-db** [comment]
Are we expecting:

Type of cluster as Serverless, SQL Analytics, Single Node, Standard [url](https://databrickslabs.github.io/overwatch/dataengineer/definitions/)

or 

New, Existing, Interactive, Automated?

**Comment by brij-raghuwanshi-db** [comment]
Made the following change and testing the same:

```
    df
      .withColumn("cluster_type",
        when('cluster_type.isin("new", "job_cluster"), lit("automated"))
          .otherwise(lit("interactive"))
      )
```

Added job_cluster in the automated section.
