### ISSUE TITLE
User question: Where exactly to apply Azure Storage Auth Config?

### ISSUE THREAD

**Issue by followingell** [databrickslabs/overwatch#929]
Hello Overwatch maintainers,

As part of Overwatch's deployment guide, under the [Configure Overwatch -> Security Considerations -> Azure Storage Auth Config subsection](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/securityconsiderations/#azure-storage-auth-config) it mentions that the below spark config should be applied to "your cluster".

- What does "your cluster" mean exactly, where should I be applying this config? _To all Compute (All-purpose and Job compute) on the Overwatch-Workflow-running-Databrick-workspace. Just for the Cluster used by the Overwatch job..?_

Just looking for some clarification, thanks!

**Spark Config:**
```
fs.azure.account.auth.type OAuth
fs.azure.account.oauth.provider.type org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider
fs.azure.account.oauth2.client.id <application-id>
fs.azure.account.oauth2.client.secret {{secrets/<SCOPE_NAME>/<KEY_NAME>}}
fs.azure.account.oauth2.client.endpoint https://login.microsoftonline.com/<directory-id>/oauth2/token

spark.hadoop.fs.azure.account.auth.type OAuth
spark.hadoop.fs.azure.account.oauth.provider.type org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider
spark.hadoop.fs.azure.account.oauth2.client.id <application-id>
spark.hadoop.fs.azure.account.oauth2.client.secret {{secrets/<SCOPE_NAME>/<KEY_NAME>}}
spark.hadoop.fs.azure.account.oauth2.client.endpoint https://login.microsoftonline.com/<directory-id>/oauth2/token

```

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,

The spark configuration which mentioned below, that has to added to overwatch job cluster which has to be run on daily basis.

```
fs.azure.account.auth.type OAuth
fs.azure.account.oauth.provider.type org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider
fs.azure.account.oauth2.client.id <application-id>
fs.azure.account.oauth2.client.secret {{secrets/<SCOPE_NAME>/<KEY_NAME>}}
fs.azure.account.oauth2.client.endpoint https://login.microsoftonline.com/<directory-id>/oauth2/token

spark.hadoop.fs.azure.account.auth.type OAuth
spark.hadoop.fs.azure.account.oauth.provider.type org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider
spark.hadoop.fs.azure.account.oauth2.client.id <application-id>
spark.hadoop.fs.azure.account.oauth2.client.secret {{secrets/<SCOPE_NAME>/<KEY_NAME>}}
spark.hadoop.fs.azure.account.oauth2.client.endpoint https://login.microsoftonline.com/<directory-id>/oauth2/token
```

But to capture the logs from each cluster, you need to enabling the logging path from all the clusters(all purpose & job cluster) under advancedOptions -> logging.

**Comment by shravanshibu90** [comment]
@followingell your are right with the first question you had and the second it's not about the key name it's about the key value. As a PAT token starts normally with dapi...

**Comment by followingell** [comment]
> @followingell your are right with the first question you had and the second **it's not about the key name it's about the key value**. As a PAT token starts normally with dapi...

@shravanshibu90 Thanks for the quick response!

In that case then IMO the documentation should be changed since _`"The key should be present in the `secret_scope` and should start with dapi."`_ is misleading. The **key** should be in the secret scope and the **value** (not the key), should start with `dapi...`

**Comment by shravanshibu90** [comment]
@followingell will definitely take your suggestion into consideration, if everything is good from your end can I close the ticket?

**Comment by GeekSheikh** [comment]
Created #932 to get docs updated. Thank you for the suggestion @followingell

**Comment by followingell** [comment]
Just following up here but, unless I'm misunderstanding, despite the previous [comment stating that this should be a Databricks PAT](https://github.com/databrickslabs/overwatch/issues/929#issuecomment-1543793849) that actually the value of `fs.azure.account.oauth2.client.secret`/`spark.hadoop.fs.azure.account.oauth2.client.secret` needs to be an Enterprise Application Secret no and not a Databricks PAT..? _cc: @GeekSheikh _

**Comment by mohanbaabu1996** [comment]
Yes, it's not a Databricks PAT. 
https://learn.microsoft.com/en-us/azure/databricks/dbfs/mounts#--mount-adls-gen2-or-blob-storage-with-abfs

<img width="755" alt="image" src="https://github.com/databrickslabs/overwatch/assets/87074323/7d6550f6-5970-4603-8580-eac213bca5c2">
