### ISSUE TITLE
User question: How to correctly set up Cluster Logging?

### ISSUE THREAD

**Issue by followingell** [databrickslabs/overwatch#930]
_This issue is similar to https://github.com/databrickslabs/overwatch/issues/929 in that it is asking for clarification related to deployment documentation_

---

Hello Overwatch maintainers,

As part of Overwatch's deployment guide, under the [Cloud Infrastructure -> Azure -> Configuring Overwatch on Azure Databricks subsection](https://databrickslabs.github.io/overwatch/deployoverwatch/cloudinfra/azure/#configuring-overwatch-on-azure-databricks) it shows that [Cluster log delivery](https://docs.databricks.com/clusters/configure.html?searchString=&from=0&sortby=_score&orderBy=desc&pageNo=1&aggregations=%5B%5D&uid=7dc8d13f-90bb-11e9-98a5-06d762ad9a62&resultsPerPage=10&exactPhrase=&withOneOrMore=&withoutTheWords=&pageSize=10&language=en&state=1&suCaseCreate=false#cluster-log-delivery-1) should be enabled.

Related to Cluster log delivery configuration I have a few questions that aren't clear to me from the documentation:

1. Where should I be enabling  Cluster log delivery? _To all Compute (All-purpose and Job compute) on the Overwatch-Workflow-running-Databrick-workspace?_
2. What should be the Logging `Destination` _(I only have `DBFS` listed)_ and `Cluster log path` values? _The guide states that "It’s not recommended to store these on DBFS directly (dbfs mount points are ok)" and shows a mount point being used but in the FAQ under [Q4: How to config the cluster logs path?](https://databrickslabs.github.io/overwatch/faq/#q4-how-to-config-the-cluster-logs-path) it states that "The cluster logging paths are automatically acquired within Overwatch. There’s no need to tell Overwatch where to load those from." and the `Destination` value is `DBFS` with no mount point..._

    -  What is the recommended setup to ensure that my logs make it to the cluster-log-specific dedicated storage account (as per the [Reference Architecture diagram](https://databrickslabs.github.io/overwatch/deployoverwatch/cloudinfra/azure/#reference-architecture))?

As before, just looking for some clarification, thanks!

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,

1. It's in the cluster configuration, AdvancedOptions -> logging
2. If you're using azure cloud then the logging path will be `dbfs:// <mounted path that pointed to storage account and container for the cluster logs>>/<if cluster triggers any logs then the sub folder will automatically create based on the clusterID>>`. If AWS, then you can directly provide the full S3 path

Recommend architecture as mentioned you can maintain the cluster logs based on the regional level or a common storage account and different container for each workspace.
More information please refer [docs](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics/#cluster-logs-ingest-details).
Thank you!

**Comment by followingell** [comment]
Hey @mohanbaabu1996 thanks for the reply.

> 1. It's in the cluster configuration, AdvancedOptions -> logging

I'm aware that this is how you enable logging, but to confirm I'd need to enable this separately for every single cluster I want logging for no?

> 2. If you're using azure cloud then the logging path will be dbfs:// <mounted path that pointed to storage account and container for the cluster logs>>/<if cluster triggers any logs then the sub folder will automatically create based on the clusterID>>. If AWS, then you can directly provide the full S3 path

Got you, thanks. Do you have any recommendation r.e. on Azure choosing between a single container per-region _(multiple (same-region) workspaces outputting into a single container)_  vs. a container per-workspace _(individual, (same-region) workspaces outputting into separate containers under a single storage account)_.

Please let me know, thank you!

**Comment by shravanshibu90** [comment]
@followingell 

1. You need to enable this separately for every single cluster
2. And regarding logging container, you can use single container per-region. An in case if you need a container per-workspace, that too works. It will not make any difference with overwatch data collect. In the second case kindly provide sufficient access for cluster to read data from all the containers.

**Comment by shravanshibu90** [comment]
@followingell Hope the above info given you more clarity, can close the ticket?

**Comment by followingell** [comment]
> @followingell Hope the above info given you more clarity, can close the ticket?

It has, thank you!

**Comment by GeekSheikh** [comment]
@followingell -- feel free to reach back out once you have a strategy to ensure logging is enabled for all future clusters. We have some scripts that will help you update the logging location for all existing jobs and interactive clusters.

**Comment by followingell** [comment]
Hello all again,

Can you please provide more clarity on what this means [within the FAQ](https://databrickslabs.github.io/overwatch/faq/#q4-how-to-config-the-cluster-logs-path)?

> **Q4: How to config the cluster logs path?**
> 
> The cluster logging paths are automatically acquired within Overwatch. There’s no need to tell Overwatch where to load those from. [Click here](https://databrickslabs.github.io/overwatch/deployoverwatch/cloudinfra/azure//#configuring-overwatch-on-azure-databricks) for more details.
> ![Overwatch FAQ Image](https://databrickslabs.github.io/overwatch/images/_index/faq4.png)

- For what Cluster(s) is it stating that I don't have to apply the Cluster Logs path? I assume this just for (Overwatch-job-running) Cluster only?

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,

In general, If you enable any path in the cluster config and if you perform some actions with the cluster, then automatically folder will create with clusterID and logs will be saved.  

`Example: dbfs:/mnt/cluster-logs/0000-1111-2222 (cluster ID)
`  

Once logs are present inside the path, Overwatch should have necessary [permissions](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/securityconsiderations/#storage-access) to read from the location. So no need to provide any configuration related to cluster logs. Overwatch will read automatically from the location.  

The logging path has to enabled to all the clusters, only then right [side](https://databrickslabs.github.io/overwatch/dataengineer/definitions/#erd) set of tables will be generated from ERD.
 
More [details](https://databrickslabs.github.io/overwatch/dataengineer/productionizing/#cluster-logging) about cluster logs.  

Thanks!

**Comment by followingell** [comment]
> The cluster logging paths are automatically acquired within Overwatch. There’s no need to tell Overwatch where to load those from. [Click here](https://databrickslabs.github.io/overwatch/deployoverwatch/cloudinfra/azure//#configuring-overwatch-on-azure-databricks) for more details.

@mohanbaabu1996 Maybe I'm missing something... Then why does the image show an empty Cluster Log path? 🤔

**Comment by followingell** [comment]
> The image represents where to update the logging path. We will update the docs for clear information. Thanks!

Thanks. To me I'd remove the image from the question's response since you don't have to specify in that config area anything for Overwatch to fetch the logs and including it is rather ocnfusing 👍
