### ISSUE TITLE
Alternative solutions apart from mount point for databricks Overwatch!!

### ISSUE THREAD

**Issue by Jagadheswara** [databrickslabs/overwatch#939]
**Sensitive Content Alert**

**Overwatch Version**
Tell us the version of Overwatch used when you received the issue  - (0.71XRunner)

**Describe the bug**

OVERWATCH is using mountpoints to collect cluster and workspace logs and this is against DA&P standard. However mount points have been approved as an exception, but need a timeline and alternative permanent solution from Databricks. 

**Issue [Reports**]
Provided the reports requested.

**Comment by mohanbaabu1996** [comment]
Hi @Jagadheswara ,

As we discussed, i've escalated to the account's team because dbfs is the only option to collect cluster logs.

Regards,
Mohan Baabu

**Comment by mohanbaabu1996** [comment]
Hi @Jagadheswara ,

As we discussed briefly in the call that this is a platform issue (not an overwatch issue). Kindly work with the databricks account's team for the updates. Thanks!
