### ISSUE TITLE
Jobrun without corresponding cluster on clusters table

### ISSUE THREAD

**Issue by AndreSepulveda** [databrickslabs/overwatch#946]
**Overwatch Version**
- 0.7.2.0.1

It's running on aws deployed using the jar and it's split into a bronze and silver+gold tasks.

**Describe the bug**
I've found entries on jobrun_gold without the corresponding the corresponding cluster on the cluster_gold table. I notice that it only happens for jobs that run in the 5 minutes that succeed the overwatch job run.

I did check the tables clusters_snapshot_bronze and clusterstatefact_gold and the cluster appear in both of them.

**Issue Reports**

[export-4.csv](https://github.com/databrickslabs/overwatch/files/11616722/export-4.csv)

**Comment by Arfa-1999** [comment]
Let me know if the issue is resolved? The previous ticket is closed.

**Comment by mohanbaabu1996** [comment]
Hi @AndreSepulveda , 

Let us know if you need any help
