### ISSUE TITLE
Driver Node Type ID with wrong value

### ISSUE THREAD

**Issue by AndreSepulveda** [databrickslabs/overwatch#949]
**Overwatch Version**
0.7.2.0.1

**Describe the bug**
driver_node_type_id from clusters_gold table not matching real value from cluster after an edit happened. Did check the cluster_events_bronze table and the value there is correct on the details column.

**Screenshots**
cluster_events_bronze:
![cluster_events_bronze](https://github.com/databrickslabs/overwatch/assets/59960185/37e814fe-60a7-4f7e-b320-47e397ee5cbd)

clusterstatefact_gold:
![clusterstatefact_gold](https://github.com/databrickslabs/overwatch/assets/59960185/b7b705e1-2baa-4240-be38-9b886bc6e7ae)

cluster_gold:
![cluster_gold](https://github.com/databrickslabs/overwatch/assets/59960185/ae58b43e-7501-4f15-9827-62d8e2f84c7e)

**Issue Reports**
[Troubleshooting](https://github.com/databrickslabs/overwatch/files/11637831/export-6.csv)

**Comment by mohanbaabu1996** [comment]
Hi @AndreSepulveda ,

Did you checked the node type ID from cluster_gold table when action column is edit ?

Regards,
Mohan Baabu

**Comment by AndreSepulveda** [comment]
Yes, I did. That's what the cluster_gold print was.

Values on the cluster_gold table aren't matching what we have on databricks. I'm not sure if the cluster_gold table is built using the cluster_events_bronze table, but the events on have the correct values, so it might be some issue on the ETL.

<img width="491" alt="Screen Shot 2023-06-05 at 09 57 17" src="https://github.com/databrickslabs/overwatch/assets/59960185/3e615f04-a17f-4522-8483-fabd2fca4e08">

**Comment by AndreSepulveda** [comment]
#00332111

**Comment by mohanbaabu1996** [comment]
Thanks, will check and update you

**Comment by mohanbaabu1996** [comment]
I've replied you in the ticket

**Comment by mohanbaabu1996** [comment]
Hi @AndreSepulveda ,

I hope our team is communicating with you on slack.
Will close this ticket and we can communicate either on slack or the ticket (00332111)
Thanks!
