### ISSUE TITLE
Overwatch consumption layer misses tables

### ISSUE THREAD

**Issue by mingshi-wang** [databrickslabs/overwatch#950]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
The version is "0.7.1.2"

**Describe the bug**
The consumption layer misses many tables, e.g. "jobRunCostPotentialFact", and all the spark events tables documented on the official website https://databrickslabs.github.io/overwatch/dataengineer/definitions/#consumption-layer-tables-views. 

**Screenshots**
1. The screenshot below shows the list of tables generated by the job run:
![Screenshot 2023-06-02 at 1 25 26 PM](https://github.com/databrickslabs/overwatch/assets/80255099/95fb8333-59af-4f42-a486-eeb17c48b2e3)

2. The second screenshot shows the bronze, silver, gold data:
![Screenshot 2023-06-02 at 1 23 59 PM](https://github.com/databrickslabs/overwatch/assets/80255099/33e6ad1d-544d-4f22-b1d9-f5ed243d4418)

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by mohanbaabu1996** [comment]
Hi @mingshi-wang ,

Is this a fresh deployment run ?
The report attached in the link is not working, can you send me the report to troubleshoot ?

`select • from ETL_DB.pipeline_report order by pipeline_snapts desc`

Spark tables will be populate only if the cluster logging path is enabled and overwatch should have read access. More details [here](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics/#cluster-logs-ingest-details)
