### ISSUE TITLE
Link to Changelog in new version does not work

### ISSUE THREAD

**Issue by Mpicca** [databrickslabs/overwatch#952]
Clicking on Changelog to see what is covered results in the following:

![image](https://github.com/databrickslabs/overwatch/assets/24516226/9ce5e514-34dd-482c-92ef-84836c5eef61)

This used to work when viewing changelogs in prior versions.

**Comment by mohanbaabu1996** [comment]
This is the [link](https://databrickslabs.github.io/overwatch/changelog/) for change log page. Let me know which link is causing the issue. Thanks!

**Comment by Mpicca** [comment]
@mohanbaabu1996 the link you pasted does not work for me, I've tried on chrome, edge and incognito mode.

**Comment by Mpicca** [comment]
Update: Anti Virus software was blocking site, apologies.
