### ISSUE TITLE
Procedure to update Azure InstanceDetails table based on CSV from github

### ISSUE THREAD

**Issue by anogues-danone** [databrickslabs/overwatch#956]
Hello.

I wrote a small notebook to update it. It should be possible to do it for AWS/GCloud too easily.

It takes the different workspaces and adds the new instances with a merge with the same current dates:
I can also take the databases from the parameter file and so on, so let me know if you ar einterested and i can create a notebook, or you can use it to bundle it. I think you have work in progress to achieve something similar here: https://github.com/databrickslabs/overwatch/issues/906

url = "https://raw.githubusercontent.com/databrickslabs/overwatch/main/src/main/resources/Azure_Instance_Details.csv"
from pyspark import SparkFiles
spark.sparkContext.addFile(url)
df = spark.read.csv("file://"+SparkFiles.get("Azure_Instance_Details.csv"), header=True, inferSchema= True)
df_orgs = spark.sql("select distinct organization_id, activeFrom, activeUntil, isActive, Pipeline_SnapTS, Overwatch_RunID, Overwatch_RunID, workspace_name from  overwatch_etl.instanceDetails")
df_newinstances = df.crossJoin(df_orgs)

from delta.tables import *
instanceDetails = DeltaTable.forName(spark,'overwatch_etl.instanceDetails')
instanceDetails.alias("id").merge(
    source = df_newinstances.alias("newid"),
    condition = "id.API_Name = newid.API_Name AND id.organization_id=newid.organization_id"
  ).whenNotMatchedInsertAll().execute()

I'm not updating any value but i can tune it to update existing instances with new prices and so on.

**Comment by mohanbaabu1996** [comment]
Hi @anogues-danone ,

We are working on the script and will let you know the updates in 1-2 working days.
If you don’t have any customizations, you can just delete from the table for the relevant org ids and it will be recreated on next run with the latest values (assuming you’re on the overwatch latest version)

**Comment by anogues** [comment]
Hello  @mohanbaabu1996 

Thanks. Well currently i am not running the last version but an outdated one from a year ago 0.6.1.0 if i recall.
I asked my team several times to create required infra with terraform to be able to move to single workspace to multi workspacxe dpeloyment, I have all ready but they are not moving with my request so for the moment, the only option i have is to update the table by myself.

This piece of code is part of a bigger script that connects to all our azure subscriptions, fetches all databricks workspaces, and sets up a run-now job to launch this piece of code to update the table.

I don't think in the latestt versions the structure of the table has changed so far,s o it will be quite useful for us (and i guess for everybody) if we can set up a job with th elatest overwatch version that is able to recreate tables in an old version. Unfortunately not everybody can keep up with latest versions when you are managing 250+ workspaces, hence my script.

BR,
Albert

**Comment by mohanbaabu1996** [comment]
Hi @anogues,

Sorry for the delay, we're working on the script.
Do you made any customizations to the instance details?
