### ISSUE TITLE
`INVALID_PARAMETER_VALUE Missing cloud file system scheme` Exception while Deploying

### ISSUE THREAD

**Issue by followingell** [databrickslabs/overwatch#967]
**Overwatch Version**
`com.databricks.labs:overwatch_2.12:0.7.2.0.1` _(in conjunction with `com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.21` since I am using Azure)_.

**Describe the bug**
After following the [deployment steps](https://databrickslabs.github.io/overwatch/deployoverwatch/) for Unity Catalog and running a successful [Deployment Validation](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/validation/):
```
select * from delta.`/mnt/<name>/report/validationReport` where validated = 'false'
order by snapTS desc

-- Query returned no results
``` 

...and running [Overwatch As A JAR On Databricks Workflows](https://databrickslabs.github.io/overwatch/deployoverwatch/runningoverwatch/jar/) the Workflow completes but the deployment is unsuccessful:
```python
display(
  spark.read.format("delta").load("/mnt/<name>/report/deploymentReport")
    .orderBy('snapTS.desc)
)
```

**`errorMsg`:**
```
Got Exception while Deploying,
[RequestId=3bfdd49d-9ce2-4546-8de6-b438e0cdf78e ErrorClass=INVALID_PARAMETER_VALUE] Missing cloud file system scheme
com.databricks.sql.managedcatalog.UnityCatalogServiceException: [RequestId=8a4356e3-dd60-4817-9322-5ca2dfb62ac3 ErrorClass=INVALID_PARAMETER_VALUE] Missing cloud file system scheme
	at com.databricks.managedcatalog.ErrorDetailsHandler.wrapServiceException(ErrorDetailsHandler.scala:33)
...
```

After investigating the logs for the listed `RequestId` I see _(amongst other details)_:
- `ActionName`: `generateTemporaryPathCredential`
- `Response`: `{"statusCode":400,"errorMessage":"DatabricksServiceException: INVALID_PARAMETER_VALUE: Missing cloud file system scheme"}`

Unfortunately I am at a loss what might be causing this error and what to do to fix.... As such, I am reaching out here.

I'm more than happy to provide extra details/file an Issue Report/jump on a call etc. as required/if needed.

Thanks!

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,
If possible, can you send the HTML copy of [this](https://databrickslabs.github.io/overwatch/assets/DeployOverwatch/071x_Runner.html) notebook after running all the commands. Also the job snippet how it's configured.

Thanks,
Mohan Baabu

**Comment by followingell** [comment]
> Hi @followingell , If possible, can you send the HTML copy of [this](https://databrickslabs.github.io/overwatch/assets/DeployOverwatch/071x_Runner.html) notebook after running all the commands. Also the job snippet how it's configured.
> 
> Thanks, Mohan Baabu

Hey Mohan,

Thanks for your response.

If needed I will share this. For now, after reviewing GitHub issues I am investigating another option:
- https://github.com/databrickslabs/overwatch/issues/951

I believe that I may need to adjust the `storage_prefix`. I have asked for some clarification on the ticket: https://github.com/databrickslabs/overwatch/issues/951#issuecomment-1600656701

I look forward to hearing back!

**Comment by mohanbaabu1996** [comment]
Thanks, you can differently use the abfss path to storage prefix column

**Comment by followingell** [comment]
@mohanbaabu1996 This resolved my issue, thanks!
