### ISSUE TITLE
Overwatch jobs failing after upgrade to 0.7.2

### ISSUE THREAD

**Issue by RamlaSuhra123** [databrickslabs/overwatch#978]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
0.7.2.0

**Describe the bug**
Daily run Job is shown as completed successfully. However data is not getting populated in the cluster tables. Error log from driver attached. 

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
[overwatchDiagnosticreport.csv](https://github.com/databrickslabs/overwatch/files/11877709/overwatchDiagnosticreport.csv)

Please provide the reports req
[OverwatchFailure_June262023.zip](https://github.com/databrickslabs/overwatch/files/11877718/OverwatchFailure_June262023.zip)
Also attached the diagnostic report

**Comment by mohanbaabu1996** [comment]
Hi @RamlaSuhra123 ,

I guess you've created the Databricks support ticket (00339724 ) as well, right ?

**Comment by RamlaSuhra123** [comment]
Yes. I have a ticket as well. 

https://urldefense.com/v3/__https://help.databricks.com/s/case/5008Y00002EIhQ9QAL__;!!D38LNok!zKe8TzK24YAC00pfFhICULOgDH3aHaR7QsG8dHiNOdYzhyhkwbI5kSeJQQqS8mLTYtEf3vJU9uL9gA$

**Comment by mohanbaabu1996** [comment]
Thanks, I've replied to that ticket and will continue communicating there. 
Closing the ticket here.
Thank you!
