### ISSUE TITLE
User Question: "Optimizing Overwatch" recommendations validity as of `v0.7.2.0.2`

### ISSUE THREAD

**Issue by followingell** [databrickslabs/overwatch#979]
**Overwatch Version**
`v0.7.2.0.2`

**Question**
As part of Overwatch's documentation there exists a section [Optimizing Overwatch](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics//#optimizing-overwatch).

This section lists many topics related to improving Overwatch's runtime/stability etc. however, many of the suggestions seem that they could potentially be out of date _e.g. recommending Set `externalizeOptimize` to true which [is only referenced in the legacy configuration](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/configurationlegacy/)._

As such, I'd like clarification as to which of the below optimizations are still relevant and recommended as of `v0.7.2.0.2`:
1. [Multi-task deployment for `Bronze`, `Silver` & `Gold`](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics//#optimization-limitations-bronze).
2. Utilizing [External Optimize](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics//#externalize-optimize--z-order-as-of-060).
2i. _If so, how do I enable this with a Spark JAR/non-notebook deployment?_

I look forward to hearing back and appreciate the ongoing support I've gotten through here 🙂

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,

That's the optimizer [job](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics//#externalize-optimize--z-order-as-of-060) which you've to configure it for optimization.

**Comment by mohanbaabu1996** [comment]
```
Set externalizeOptimize to true in the runner notebook config (All Workspaces)
If running as a job don’t forget to update the job parameters with the new escaped JSON config string
```

Yes, need to set config externally, if you're using legacy method. Are you following legacy method or Multi Workspace method ?

Yes, you can split the job task for Bronze, Silver & Gold

**Comment by followingell** [comment]
1. @mohanbaabu1996 I am not using the legacy method, I am using the latest documented, `MultiWorkspaceRunner` method: [Deploying Overwatch As A JAR On Databricks Workflows](https://databrickslabs.github.io/overwatch/deployoverwatch/runningoverwatch/jar/) as per the documentation.
2. Thanks for the clarification.

**Comment by followingell** [comment]
Hey @mohanbaabu1996,

It wasn't clear to me over the last conversations:

- If I am using the Multi Workspace method can I not Utilizine [External Optimize](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics//#externalize-optimize--z-order-as-of-060)?

**Comment by mohanbaabu1996** [comment]
Yes, you can use

**Comment by followingell** [comment]
> Yes, you can use

@mohanbaabu1996 Would you be able to tell me how? I can't figure this out from the docs...

Also, to your point: _"Yes, you can split the job task for Bronze, Silver & Gold"_ the question is what is the recommended solution? I ask because from the docs:
> **Running all the pipelines together will maximize cluster utilization** but there are often reasons to split the pipelines thus we’ve added support.

**Comment by mohanbaabu1996** [comment]
- This is [link](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics/#externalize-optimize--z-order-as-of-060) for setting up overwatch optimization job
- Splitting up different task helps to reduce the running time and cluster cost. For example, if bronze takes long time to run, then we can use specific cluster size, whereas silver and gold doesn't take much time, so you can modify the cluster size. Recommended option is to split the task for each layer

**Comment by followingell** [comment]
> * This is [link](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics/#externalize-optimize--z-order-as-of-060) for setting up overwatch optimization job

I feel like maybe we are going round in circles a bit here...

The link you shared explains how to do this for the **legacy** notebook setup _(unless I am missing something / misunderstanding)_: _"Set `externalizeOptimize` to true in the **runner notebook config** (All Workspaces). If running as a job don’t forget to update the job parameters with the new escaped JSON config string"_.

I am asking if/how it is possible to do this in the non-legacy, currently documented,  Spark JAR based deployment.

- Can you please share if/how this can be done (or link to where in the documentation above it explains how to do this).

> * Splitting up different task helps to reduce the running time and cluster cost. For example, if bronze takes long time to run, then we can use specific cluster size, whereas silver and gold doesn't take much time, so you can modify the cluster size. Recommended option is to split the task for each layer

Thanks I'll split the Workflow 👍

**Comment by mohanbaabu1996** [comment]
1. You've mentioned you're using multi workspace method, so directly create a optimizer job (direct approach)
2. Sure, split the job with 3 sub tasks with the below config

- ["dbfs:/path/to/config.csv", "Bronze"]
- ["dbfs:/path/to/config.csv", "Silver"]
- ["dbfs:/path/to/config.csv", "Gold"]

**Comment by followingell** [comment]
> 1. You've mentioned you're using multi workspace method, so directly create a optimizer job (direct approach)
> 2. Sure, split the job with 3 sub tasks with the below config
> 
> * ["dbfs:/path/to/config.csv", "Bronze"]
> * ["dbfs:/path/to/config.csv", "Silver"]
> * ["dbfs:/path/to/config.csv", "Gold"]

@mohanbaabu1996 Thanks for the reply.

R.e. 1. [Given](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics/#externalize-optimize--z-order-as-of-060):
> The Overwatch pipeline has always included the Optimize & Z-Order functions.

and 

> Set `externalizeOptimize` to true in the runner notebook config (All Workspaces)
If running as a job don’t forget to update the job parameters with the new escaped JSON config string

... do I not need to disable the Optimize & Z-Order functionality in the 'main' Overwatch _(`com.databricks.labs.overwatch.MultiWorkspaceRunner`)_ job before creating an optimizer job _(`com.databricks.labs.overwatch.Optimizer`)_?

How do I do that with the 'Multi Workspace method', that's what isn't clear to me 🙂

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,

No, don't disable the main job, that keeps collecting the data and optimizer is a different job. 
Two jobs have to created one for main overwatch and optimizer job.

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,

Are you available for a short call now ?
Thanks!

**Comment by followingell** [comment]
Hey @mohanbaabu1996,

Sorry I missed this message, I'm not available right now unfortunately.

Would next week work? How would we schedule / setup?

**Comment by mohanbaabu1996** [comment]
Hi @followingell ,

I'm from IST timezone and please share your availability with your email address.
Thank you!

**Comment by followingell** [comment]
@mohanbaabu1996 

_(All times are in IST)._

**Times:**
- Tuesday: 2:30pm - 4:30pm.
- Wednesday: 1:30pm - 4:30pm, 5:30pm - 9:30pm.
- Thursday: 2:30pm - 4:30pm, 5:30-6:30pm, 7:30-9:30pm.
- Friday: 2:30pm - 4:30pm.

My email is `elliot(dot)partridge@mews(dot)com`.

What platform are you planning on using to conduct the meeting?

I look forward to receiving an invite over email 🙂

**Comment by mohanbaabu1996** [comment]
Thanks, sent you invite

**Comment by followingell** [comment]
Thanks for the call @mohanbaabu1996.
