### ISSUE TITLE
Overwatch Data Issue - Support ticket - CASE NUMBER # 00340818

### ISSUE THREAD

**Issue by RamlaSuhra123** [databrickslabs/overwatch#984]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
[7.2.0.2]

**Describe the bug**
Cluster information missing in cluster table. Only 16 records in cluster table for a workspace.

select count( cluster_name) from overwatch.cluster; -- 900252
select count( cluster_name) from overwatch.cluster where workspace_name='ophie-heb-analytics-prd' ;  --16
select count( cluster_name) from overwatch_etl.cluster_gold where workspace_name='ophie-heb-analytics-prd' ;  --16
select count( cluster_name) from overwatch.clusterstatefact where workspace_name='ophie-heb-analytics-prd' ; --58416

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
Already created a support ticket for the same.

Support ticket - CASE NUMBER # 00340818

**Comment by mohanbaabu1996** [comment]
Hi Ramla,

Thanks for the ticket, will discuss over the Slack/Support ticket.
