### ISSUE TITLE
SparkEvents module not being populated

### ISSUE THREAD

**Issue by TheRealJimShady** [databrickslabs/overwatch#992]
**Overwatch Version**
0.7.2.0.2

**Cloud**
Azure

**Describe the bug**
None of the entities in the `SparkEvents` module are being populated, I have checked the badRecordsPath and it's empty. My suspicion is that the cluster log paths are not being correctly resolved, possibly due to the arrangement of our mount points. We have a storage container for cluster logs and another for the overwatch databases. Each source workspace has a consistently named mount point which outputs to a different suffix. It looks something like this;

- Source Workspace 1
  - Cluster logs mount alias : `/mnt/cluster-logs`
  - Cluster logs mount location : `dbfs:/mnt/cluster-logs/workspace-1`
  - Physical location : `abfss://cluster_logs@overwatch/workspace-1`
- Source Workspace 2
  - Cluster logs mount alias : `/mnt/cluster-logs`
  - Cluster logs mount location : `dbfs:/mnt/cluster-logs/workspace-2`
  - Physical location : `abfss://cluster_logs@overwatch/workspace-2`
- Source Workspace 3
  - Cluster logs mount alias : `/mnt/cluster-logs`
  - Cluster logs mount location : `dbfs:/mnt/cluster-logs/workspace-3`
  - Physical location : `abfss://cluster_logs@overwatch/workspace-3`
- Overwatch Workspace
  - ETL database mount alias : `/mnt/overwatch_databases`
  - ETL database mount location : `dbfs:/mnt/overwatch_databases`
  - Physical location : `abfss://databases@overwatch`

Logs state;

> Beginning: 1006-Bronze_SparkEventLogs --> Workspace ID: xxxxxx
> TIME RANGE: 2023-07-10 17:26:12 -> 2023-07-10 18:25:37
> 
> Bronze_SparkEventLogs: Validating Input Schemas
> Path Globs Empty, exiting

<img width="1509" alt="Screenshot 2023-07-10 at 20 14 50" src="https://github.com/databrickslabs/overwatch/assets/12716005/09dc5a5b-67c0-409a-8f82-6fb89d833242">

**Comment by TheRealJimShady** [comment]
Hi - thanks for your reply, please find the attachment below.
I've hashed the workspace id and deployment id columns and dropped validationRule since it contains sensitive data.
[validation_report.csv](https://github.com/databrickslabs/overwatch/files/12026949/validation_report.csv)

**Comment by mohanbaabu1996** [comment]
Hi @TheRealJimShady , 

Did you noticed any issues from pipReport ? Can you share that to validate.

`select * from ETL_DB_NAME.pipeline_report where status like "%FAILED%" order by PipelineSnapTs desc`

Also please share your input csv config file.

Thanks!

**Comment by TheRealJimShady** [comment]
I cannot provide any further information on this topic unfortunately as I have finished working for the client.

**Comment by mohanbaabu1996** [comment]
No problem @TheRealJimShady , let us know if you've any issues with Overwatch.
Thanks!
