### ISSUE TITLE
Switch jobs API from offset to token-based pagination

### ISSUE THREAD

**Issue by tatianaromanova-db** [databrickslabs/overwatch#994]
Currently overwatch uses offset based pagination to iterate over the list of jobs: [link](https://github.com/databrickslabs/overwatch/blame/736ec19767159f5204e78dc00b5c803259eae806/src/main/scala/com/databricks/labs/overwatch/api/ApiMeta.scala#L293)

Offset parameter in /jobs/list API call is going to be limited to 1000, so we need to make overwatch use page_token parameter instead: https://docs.databricks.com/api/workspace/jobs/list

**Comment by oleksiidav** [comment]
Hi @sriram251-code , is this getting prioritized soon? We have a soft deadline of Oct 9 when we broadly deprecate and limit the offset parameter

**Comment by DiegoMarcilloCruz** [comment]
Hello folks! Is there an estimated date for the release of the new version?
